<div style="background:#E9FFF6; color:#440404; padding:8px; border-radius: 4px; text-align: center; font-weight: 500;">IFN619 - Data Analytics for Strategic Decision Makers</div>

# IFN619 :: B3-Semi/unstructured Analytics (Part A)

For this session, the focus will be on analysis of unstructured text. However, the thinking required is similar to approaches to analysing images, video, sound and other unstructured data. Primarily, the analysis is based on the notion that there are useful patterns in the unstructured data which can be obtained computationally.

Most of the time, working with semi-structured or unstructured data involves a process of incrementally structuring it to the point where we can obtain meaningful information. Algorithms like topic modelling algorithms (which we will look at in Part B) allow more complex analysis of semi/unstructured data. For now, we will look at some basic approaches.

In [1]:
# Import the necessary libraries
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
import pandas as pd
import json
import random

### Basic incremental structuring

Before using the imported Python libraries, let's look at how we can work with unstructured text data by taking a simple (unstructured) string of characters and modify it to be more structured.

In [2]:
# selected from David Bohm's 1990 paper: "A new theory of the relationship of mind and matter" (p.281)

bohm_text = "Thus, for example, when we read a printed page, we do not assimilate the substance of the paper, but only the forms of the letters, and it is these forms which give rise to an information content in the reader which is manifested actively in his or her subsequent activities. A similar mind-like quality of matter reveals itself strongly at the quantum level, in the sense that the form of the wave function manifests itself in the movements of the particles. This quality does not, however, appear to a significant extent at the level at which classical physics is a valid approximation."

# show the contents of the variable
bohm_text

'Thus, for example, when we read a printed page, we do not assimilate the substance of the paper, but only the forms of the letters, and it is these forms which give rise to an information content in the reader which is manifested actively in his or her subsequent activities. A similar mind-like quality of matter reveals itself strongly at the quantum level, in the sense that the form of the wave function manifests itself in the movements of the particles. This quality does not, however, appear to a significant extent at the level at which classical physics is a valid approximation.'

We can split the string into separate sentences using the `split()` function.

In [3]:
# Use an appropriate character to split text into sentences
bohm_sents = bohm_text.split('.')
bohm_sents

['Thus, for example, when we read a printed page, we do not assimilate the substance of the paper, but only the forms of the letters, and it is these forms which give rise to an information content in the reader which is manifested actively in his or her subsequent activities',
 ' A similar mind-like quality of matter reveals itself strongly at the quantum level, in the sense that the form of the wave function manifests itself in the movements of the particles',
 ' This quality does not, however, appear to a significant extent at the level at which classical physics is a valid approximation',
 '']

We can then process each sentence to extract words, adding them to a list

In [4]:
bohm_words = []
for sent in bohm_sents:
    # Use an appropriate character to split sentences into words
    sent_words = sent.split(' ')
    for word in sent_words:
        bohm_words.append(word)
        
bohm_words

['Thus,',
 'for',
 'example,',
 'when',
 'we',
 'read',
 'a',
 'printed',
 'page,',
 'we',
 'do',
 'not',
 'assimilate',
 'the',
 'substance',
 'of',
 'the',
 'paper,',
 'but',
 'only',
 'the',
 'forms',
 'of',
 'the',
 'letters,',
 'and',
 'it',
 'is',
 'these',
 'forms',
 'which',
 'give',
 'rise',
 'to',
 'an',
 'information',
 'content',
 'in',
 'the',
 'reader',
 'which',
 'is',
 'manifested',
 'actively',
 'in',
 'his',
 'or',
 'her',
 'subsequent',
 'activities',
 '',
 'A',
 'similar',
 'mind-like',
 'quality',
 'of',
 'matter',
 'reveals',
 'itself',
 'strongly',
 'at',
 'the',
 'quantum',
 'level,',
 'in',
 'the',
 'sense',
 'that',
 'the',
 'form',
 'of',
 'the',
 'wave',
 'function',
 'manifests',
 'itself',
 'in',
 'the',
 'movements',
 'of',
 'the',
 'particles',
 '',
 'This',
 'quality',
 'does',
 'not,',
 'however,',
 'appear',
 'to',
 'a',
 'significant',
 'extent',
 'at',
 'the',
 'level',
 'at',
 'which',
 'classical',
 'physics',
 'is',
 'a',
 'valid',
 'approximation',
 '']

We can clean up this list by removing empty elements, dropping commas, and making all words lowercase

In [5]:
# Only keep words that are not '' (empty string), make them lower case and remove any comma characters
bohm_clean_words = [w.lower().replace(',','') for w in bohm_words if w!='']
bohm_clean_words

['thus',
 'for',
 'example',
 'when',
 'we',
 'read',
 'a',
 'printed',
 'page',
 'we',
 'do',
 'not',
 'assimilate',
 'the',
 'substance',
 'of',
 'the',
 'paper',
 'but',
 'only',
 'the',
 'forms',
 'of',
 'the',
 'letters',
 'and',
 'it',
 'is',
 'these',
 'forms',
 'which',
 'give',
 'rise',
 'to',
 'an',
 'information',
 'content',
 'in',
 'the',
 'reader',
 'which',
 'is',
 'manifested',
 'actively',
 'in',
 'his',
 'or',
 'her',
 'subsequent',
 'activities',
 'a',
 'similar',
 'mind-like',
 'quality',
 'of',
 'matter',
 'reveals',
 'itself',
 'strongly',
 'at',
 'the',
 'quantum',
 'level',
 'in',
 'the',
 'sense',
 'that',
 'the',
 'form',
 'of',
 'the',
 'wave',
 'function',
 'manifests',
 'itself',
 'in',
 'the',
 'movements',
 'of',
 'the',
 'particles',
 'this',
 'quality',
 'does',
 'not',
 'however',
 'appear',
 'to',
 'a',
 'significant',
 'extent',
 'at',
 'the',
 'level',
 'at',
 'which',
 'classical',
 'physics',
 'is',
 'a',
 'valid',
 'approximation']

Finally, we can count how many of each word we have to get an indication of David Bohm's vocabulary used in this quote

In [6]:
bohm_vocab = {}
for word in bohm_clean_words:
    bohm_vocab[word] = bohm_vocab.get(word, 0) + 1

# Sort vocab by count (value)
bohm_vocab_sorted = dict(sorted(bohm_vocab.items(), key=lambda item: item[1]))

# Show the final dictionary
bohm_vocab_sorted

{'thus': 1,
 'for': 1,
 'example': 1,
 'when': 1,
 'read': 1,
 'printed': 1,
 'page': 1,
 'do': 1,
 'assimilate': 1,
 'substance': 1,
 'paper': 1,
 'but': 1,
 'only': 1,
 'letters': 1,
 'and': 1,
 'it': 1,
 'these': 1,
 'give': 1,
 'rise': 1,
 'an': 1,
 'information': 1,
 'content': 1,
 'reader': 1,
 'manifested': 1,
 'actively': 1,
 'his': 1,
 'or': 1,
 'her': 1,
 'subsequent': 1,
 'activities': 1,
 'similar': 1,
 'mind-like': 1,
 'matter': 1,
 'reveals': 1,
 'strongly': 1,
 'quantum': 1,
 'sense': 1,
 'that': 1,
 'form': 1,
 'wave': 1,
 'function': 1,
 'manifests': 1,
 'movements': 1,
 'particles': 1,
 'this': 1,
 'does': 1,
 'however': 1,
 'appear': 1,
 'significant': 1,
 'extent': 1,
 'classical': 1,
 'physics': 1,
 'valid': 1,
 'approximation': 1,
 'we': 2,
 'not': 2,
 'forms': 2,
 'to': 2,
 'quality': 2,
 'itself': 2,
 'level': 2,
 'is': 3,
 'which': 3,
 'at': 3,
 'a': 4,
 'in': 4,
 'of': 5,
 'the': 12}

What do you notice about the words in the vocabulary? 
Which words are meaningful? Which are not?

How do you think we could extract the meaning from the unstructured text?

---

## Using vectorizors to work with unstructured text

#### Accessing the data via The Guardian API

See the `Accessing_the_Guardian_API.ipynb` notebook file for details on getting the data. **Note:** This approach may be used for additional data for Assignment 2.

### Read in pre-saved data

To save time, we're loading in pre-saved data that was fetched using the Guardian API. Load data from the `winter_olympics_articles.json` file in the data folder.

In [7]:
# Load the data - articles from The Guardian
file_path = "data/"
file_name = "winter_olympics_articles.json"

with open(f"{file_path}{file_name}",'r', encoding='utf-8') as fp:
    articles = json.load(fp)

print(f"Loaded {len(articles)} articles from {file_name}")

Loaded 13 articles from winter_olympics_articles.json

Each dictionary entry includes the *title [date]* as `key` and the *body text* from the article as `value`.

In [8]:
article1 = list(articles.items())[0]
print("Key:",article1[0])
print("Value:",article1[1][:300],"...") # Just show first 300 characters

Key: Winter Olympics 2026: what you need to know if following from Australia [2026-02-02T14:00:10Z]
Value: When do the 2026 Winter Olympics start? The 2026 Winter Olympics officially open in the early hours of Saturday 7 February, Australian time, with the opening ceremony at Milan’s San Siro stadium. The Games run for two weeks, culminating in the closing ceremony on 23 February in Verona at the same ti ...

So the values gives us a list of documents that we can analyse.

In [9]:
# Get a list of documents
documents = list(articles.values())

# View first 400 characters of the 1st document
documents[0][:400]

'When do the 2026 Winter Olympics start? The 2026 Winter Olympics officially open in the early hours of Saturday 7 February, Australian time, with the opening ceremony at Milan’s San Siro stadium. The Games run for two weeks, culminating in the closing ceremony on 23 February in Verona at the same time of 6am AEDT. Several sports with packed schedules, including curling and ice hockey, begin a coup'

### Term Count 

**Finding important terms by the frequency of their occurance**

Using `CountVectorizer` create a `vector` for each document where the dimensionality of the vector is the `vocabulary` (all terms in the collection), and the value of each component is the number of times that the `term` occurs in the document.

All of these analyses, approach the document as a [Bag of Words](https://en.wikipedia.org/wiki/Bag-of-words_model) model. In this approach, the order of the words don't matter. A popular approach that takes into account order is [Word embedding](https://en.wikipedia.org/wiki/Word_embedding). This session does not explore word embedding.

In [10]:
# Only count terms that in maximum of 80% of documents, and a minimum of 2 documents. 
# Count a maximum of 10000 terms, and remove common english stop words
count_vectorizer = CountVectorizer(max_df=0.8, min_df=2, max_features=10000, stop_words="english")
count_dt_matrix = count_vectorizer.fit_transform(articles.values())

It is always important to understand the data we are working with

In [11]:
# Take a look at the vector for the first document
doc001_vector = count_dt_matrix.toarray()[0]
doc001_vector

array([1, 1, 0, 3, 2, 1, 0, 0, 0, 0, 0, 1, 0, 3, 0, 0, 6, 0, 0, 2, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0,
       0, 0, 1, 2, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       5, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 2, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 4, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       3, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 2, 0, 3, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 3, 0, 6, 0, 0, 0, 0, 1, 2,
       0, 2, 0, 0, 0, 1, 0, 0, 1, 0, 4, 0, 1, 2, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 2, 2, 0, 0, 0, 0,
       0, 2, 0, 1, 0, 0, 0, 1, 1, 0, 0, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 1, 1, 0, 0, 2, 1, 0, 0, 0, 0,
       0, 1, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 2, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 3, 0, 0, 0, 0, 4, 1,
       0, 4, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 2, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 2, 1, 0, 2, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 3, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 4, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 1])

In [12]:
# Get the 10000 terms identified during the vectorization process
feature_names = count_vectorizer.get_feature_names_out()
feature_names

array(['000', '10', '10th', '12', '15', '16', '17', '1994', '1998', '20',
       '2002', '2006', '2010', '2022', '2024', '2025', '2026', '20th',
       '21', '23', '25', '26', '27', '28', '30', '31', '50', '53', 'able',
       'accepted', 'according', 'accused', 'achieve', 'acknowledged',
       'acl', 'action', 'actually', 'added', 'adelaide', 'advertiser',
       'advice', 'aedt', 'aerial', 'aerials', 'afternoon', 'age', 'ago',
       'ahead', 'ahmad', 'air', 'alisa', 'allegedly', 'alongside',
       'alpine', 'alps', 'america', 'american', 'amid', 'annual',
       'anthony', 'appeal', 'arms', 'arrived', 'asian', 'assessment',
       'athlete', 'athletes', 'attack', 'attempt', 'attention',
       'australians', 'awarded', 'away', 'backed', 'baff', 'base',
       'based', 'battling', 'bearer', 'beat', 'beating', 'began', 'begin',
       'beijing', 'ben', 'best', 'better', 'bid', 'big', 'biggest', 'bit',
       'blood', 'blow', 'body', 'bradbury', 'brain', 'breadth',
       'breakthrough', 'briefing', 'bring', 'british', 'broken', 'bronze',
       'brought', 'brown', 'brutal', 'cabinet', 'called', 'calm', 'came',
       'camp', 'camplin', 'canada', 'canadian', 'capital', 'captain',
       'career', 'catch', 'celebrated', 'ceremony', 'challenge',
       'champion', 'champions', 'chance', 'change', 'chasing', 'chef',
       'child', 'children', 'china', 'circuit', 'city', 'claim',
       'claiming', 'claims', 'climate', 'close', 'closer', 'closing',
       'club', 'coach', 'coady', 'coast', 'collecting', 'come', 'coming',
       'compete', 'competed', 'competing', 'competition', 'competitions',
       'competitor', 'concerns', 'consciousness', 'considered',
       'consistent', 'contest', 'continue', 'continues', 'control',
       'cool', 'cooper', 'corner', 'correspondent', 'costs', 'couldn',
       'country', 'couple', 'course', 'covered', 'covid', 'crash',
       'crashed', 'cross', 'crossword', 'crosswords', 'crown', 'cruel',
       'cryptic', 'currently', 'daisy', 'day', 'days', 'debut', 'decades',
       'december', 'decision', 'decorated', 'deep', 'defend', 'defending',
       'definitely', 'degrees', 'depth', 'despite', 'did', 'didn',
       'different', 'discipline', 'distance', 'does', 'doesn', 'doing',
       'dominated', 'don', 'donald', 'double', 'dream', 'dropped', 'dual',
       'earlier', 'early', 'ease', 'edged', 'editor', 'efforts', 'eighth',
       'elite', 'elizabeth', 'email', 'end', 'ensure', 'entered',
       'entertained', 'entirely', 'etched', 'europe', 'event', 'events',
       'excited', 'expectations', 'expected', 'explains', 'extend',
       'face', 'failing', 'failure', 'family', 'far', 'fashion',
       'favourite', 'favourites', 'february', 'federal', 'feeling',
       'feels', 'fellow', 'field', 'final', 'finalists', 'finally',
       'finals', 'financial', 'finding', 'finish', 'finished',
       'finishing', 'flag', 'flying', 'follow', 'following', 'football',
       'foreign', 'forest', 'form', 'foundation', 'fourth', 'france',
       'freeski', 'freestyle', 'french', 'friday', 'friends', 'funding',
       'future', 'game', 'germany', 'given', 'glide', 'global', 'glory',
       'going', 'good', 'got', 'government', 'graham', 'great',
       'greatest', 'green', 'grew', 'growing', 'guardian', 'gun',
       'guseli', 'half', 'halfpipe', 'hamilton', 'happened', 'happening',
       'hard', 'harder', 'haul', 'having', 'head', 'heading', 'heating',
       'heavy', 'help', 'high', 'higher', 'highest', 'highly', 'hiking',
       'hill', 'historic', 'history', 'hit', 'home', 'hope', 'hopes',
       'host', 'hours', 'huge', 'ice', 'imagine', 'immigration',
       'improved', 'inbox', 'include', 'including', 'individual', 'indra',
       'injured', 'injury', 'instead', 'interactive', 'international',
       'invested', 'involves', 'involving', 'italy', 'jaelin', 'jakara',
       'james', 'january', 'japan', 'job', 'joined', 'josie', 'journey',
       'judged', 'judges', 'jump', 'jumping', 'jumps', 'just', 'kauf',
       'key', 'knee', 'knew', 'know', 'known', 'laffont', 'lake',
       'landed', 'landing', 'lara', 'largest', 'late', 'later', 'latest',
       'launching', 'laura', 'lead', 'leading', 'league', 'learn',
       'leave', 'leaving', 'led', 'left', 'legs', 'lemley', 'let',
       'liberal', 'life', 'like', 'likely', 'line', 'little', 'live',
       'livigno', 'living', 'll', 'local', 'long', 'looking', 'losing',
       'lost', 'lot', 'love', 'luge', 'mail', 'make', 'makes', 'making',
       'man', 'mark', 'martin', 'matt', 'matter', 'medallist',
       'medallists', 'medals', 'media', 'medical', 'meet', 'melbourne',
       'member', 'men', 'metres', 'milan', 'minister', 'minutes', 'miss',
       'missed', 'missing', 'mission', 'mix', 'mixed', 'mogul', 'moguls',
       'moment', 'moments', 'month', 'months', 'morning', 'moscow',
       'mother', 'mount', 'mountain', 'mountaineering', 'mountains',
       'nailed', 'nation', 'national', 'neck', 'need', 'needed', 'needs',
       'nervous', 'new', 'news', 'newsletter', 'nice', 'night',
       'northern', 'norway', 'nsw', 'number', 'occasion', 'officials',
       'ok', 'olympian', 'open', 'opening', 'opportunity', 'overall',
       'overcame', 'overcome', 'overcoming', 'overnight', 'pace', 'pain',
       'pair', 'parents', 'partner', 'pass', 'past', 'peak', 'peel',
       'pegan', 'people', 'perfect', 'performance', 'perisher', 'perrine',
       'peter', 'pictures', 'place', 'playing', 'podium', 'podiums',
       'point', 'points', 'political', 'politics', 'position',
       'possibility', 'power', 'practice', 'pre', 'pressure',
       'prestigious', 'pretty', 'prices', 'pride', 'process',
       'professional', 'program', 'progress', 'progression', 'proud',
       'public', 'pulled', 'push', 'pyeongchang', 'qualifying', 'quarter',
       'queensland', 'quick', 'quickly', 'quite', 'race', 'raised',
       'ranked', 'rare', 'realised', 'really', 'receive', 'recent',
       'record', 'recorded', 'recover', 'refused', 'reged', 'regrets',
       'regular', 'reigning', 'related', 'relay', 'remains', 'remarkable',
       'repeat', 'reports', 'rest', 'results', 'return', 'returning',
       'richard', 'right', 'rise', 'round', 'rounds', 'roundup', 'row',
       'run', 'running', 'runs', 'ruptured', 'said', 'sarah', 'saturday',
       'saw', 'say', 'says', 'schedule', 'school', 'score', 'scoring',
       'scotty', 'season', 'second', 'secured', 'seen', 'semi', 'set',
       'seven', 'seventh', 'shadow', 'sharing', 'shock', 'short', 'shown',
       'sign', 'significant', 'signing', 'silver', 'single', 'singles',
       'site', 'skater', 'ski', 'skier', 'skiers', 'skiing', 'skills',
       'skimo', 'skins', 'skis', 'slalom', 'slip', 'slopes', 'smile',
       'smith', 'snow', 'snowboard', 'snowboarder', 'snowboarders',
       'snowboarding', 'social', 'sort', 'south', 'speaks', 'special',
       'speed', 'sporting', 'sports', 'spot', 'spotlight', 'sprint',
       'staff', 'standing', 'star', 'start', 'started', 'starting',
       'starts', 'state', 'statement', 'stay', 'staying', 'step',
       'steven', 'stoked', 'story', 'strategy', 'strength', 'strong',
       'stuck', 'stuff', 'success', 'successful', 'summit', 'sun',
       'sunday', 'support', 'swept', 'switzerland', 'sydney', 'table',
       'taking', 'team', 'teammates', 'teaser', 'tech', 'teenager',
       'tess', 'thing', 'things', 'think', 'thomas', 'thought', 'threat',
       'thursday', 'time', 'times', 'title', 'today', 'told', 'tomorrow',
       'took', 'topalovic', 'total', 'tougher', 'town', 'track',
       'training', 'trick', 'triumph', 'trump', 'trumpland', 'try',
       'trying', 'turin', 'turn', 'turned', 'turns', 'twice', 'uk',
       'unable', 'unlikely', 'unprecedented', 'update', 'use',
       'valentino', 'valley', 've', 'veteran', 'victoria', 'victory',
       'wales', 'want', 'wanted', 'war', 'wasn', 'watch', 'water',
       'waterville', 'way', 'week', 'weekday', 'weeks', 'weight', 'went',
       'win', 'winner', 'winning', 'wins', 'woman', 'women', 'won',
       'woods', 'work', 'worst', 'years', 'yellow', 'youngest', 'zealand'],
      dtype=object)

In [13]:
# Look at how the counts match up to the terms (for the 1st doc)
doc001_term_counts = list(zip(feature_names,doc001_vector))
doc001_term_counts

[('000', np.int64(1)),
 ('10', np.int64(1)),
 ('10th', np.int64(0)),
 ('12', np.int64(3)),
 ('15', np.int64(2)),
 ('16', np.int64(1)),
 ('17', np.int64(0)),
 ('1994', np.int64(0)),
 ('1998', np.int64(0)),
 ('20', np.int64(0)),
 ('2002', np.int64(0)),
 ('2006', np.int64(1)),
 ('2010', np.int64(0)),
 ('2022', np.int64(3)),
 ('2024', np.int64(0)),
 ('2025', np.int64(0)),
 ('2026', np.int64(6)),
 ('20th', np.int64(0)),
 ('21', np.int64(0)),
 ('23', np.int64(2)),
 ('25', np.int64(0)),
 ('26', np.int64(0)),
 ('27', np.int64(0)),
 ('28', np.int64(0)),
 ('30', np.int64(0)),
 ('31', np.int64(0)),
 ('50', np.int64(0)),
 ('53', np.int64(1)),
 ('able', np.int64(0)),
 ('accepted', np.int64(0)),
 ('according', np.int64(0)),
 ('accused', np.int64(0)),
 ('achieve', np.int64(0)),
 ('acknowledged', np.int64(0)),
 ('acl', np.int64(0)),
 ('action', np.int64(0)),
 ('actually', np.int64(0)),
 ('added', np.int64(0)),
 ('adelaide', np.int64(0)),
 ('advertiser', np.int64(0)),
 ('advice', np.int64(0)),
 ('aedt', np.int64(4)),
 ('aerial', np.int64(0)),
 ('aerials', np.int64(0)),
 ('afternoon', np.int64(0)),
 ('age', np.int64(0)),
 ('ago', np.int64(1)),
 ('ahead', np.int64(2)),
 ('ahmad', np.int64(0)),
 ('air', np.int64(0)),
 ('alisa', np.int64(0)),
 ('allegedly', np.int64(0)),
 ('alongside', np.int64(0)),
 ('alpine', np.int64(1)),
 ('alps', np.int64(1)),
 ('america', np.int64(1)),
 ('american', np.int64(0)),
 ('amid', np.int64(0)),
 ('annual', np.int64(0)),
 ('anthony', np.int64(1)),
 ('appeal', np.int64(0)),
 ('arms', np.int64(0)),
 ('arrived', np.int64(0)),
 ('asian', np.int64(1)),
 ('assessment', np.int64(0)),
 ('athlete', np.int64(1)),
 ('athletes', np.int64(5)),
 ('attack', np.int64(0)),
 ('attempt', np.int64(1)),
 ('attention', np.int64(0)),
 ('australians', np.int64(1)),
 ('awarded', np.int64(0)),
 ('away', np.int64(0)),
 ('backed', np.int64(0)),
 ('baff', np.int64(0)),
 ('base', np.int64(0)),
 ('based', np.int64(0)),
 ('battling', np.int64(0)),
 ('bearer', np.int64(0)),
 ('beat', np.int64(0)),
 ('beating', np.int64(0)),
 ('began', np.int64(0)),
 ('begin', np.int64(1)),
 ('beijing', np.int64(2)),
 ('ben', np.int64(0)),
 ('best', np.int64(1)),
 ('better', np.int64(0)),
 ('bid', np.int64(0)),
 ('big', np.int64(1)),
 ('biggest', np.int64(0)),
 ('bit', np.int64(0)),
 ('blood', np.int64(0)),
 ('blow', np.int64(0)),
 ('body', np.int64(0)),
 ('bradbury', np.int64(0)),
 ('brain', np.int64(0)),
 ('breadth', np.int64(0)),
 ('breakthrough', np.int64(0)),
 ('briefing', np.int64(1)),
 ('bring', np.int64(0)),
 ('british', np.int64(0)),
 ('broken', np.int64(0)),
 ('bronze', np.int64(2)),
 ('brought', np.int64(0)),
 ('brown', np.int64(2)),
 ('brutal', np.int64(0)),
 ('cabinet', np.int64(0)),
 ('called', np.int64(0)),
 ('calm', np.int64(0)),
 ('came', np.int64(0)),
 ('camp', np.int64(0)),
 ('camplin', np.int64(0)),
 ('canada', np.int64(0)),
 ('canadian', np.int64(0)),
 ('capital', np.int64(0)),
 ('captain', np.int64(0)),
 ('career', np.int64(0)),
 ('catch', np.int64(0)),
 ('celebrated', np.int64(0)),
 ('ceremony', np.int64(3)),
 ('challenge', np.int64(0)),
 ('champion', np.int64(0)),
 ('champions', np.int64(0)),
 ('chance', np.int64(0)),
 ('change', np.int64(0)),
 ('chasing', np.int64(0)),
 ('chef', np.int64(0)),
 ('child', np.int64(0)),
 ('children', np.int64(0)),
 ('china', np.int64(1)),
 ('circuit', np.int64(1)),
 ('city', np.int64(0)),
 ('claim', np.int64(0)),
 ('claiming', np.int64(0)),
 ('claims', np.int64(0)),
 ('climate', np.int64(0)),
 ('close', np.int64(0)),
 ('closer', np.int64(0)),
 ('closing', np.int64(1)),
 ('club', np.int64(0)),
 ('coach', np.int64(0)),
 ('coady', np.int64(1)),
 ('coast', np.int64(0)),
 ('collecting', np.int64(1)),
 ('come', np.int64(1)),
 ('coming', np.int64(1)),
 ('compete', np.int64(0)),
 ('competed', np.int64(0)),
 ('competing', np.int64(2)),
 ('competition', np.int64(1)),
 ('competitions', np.int64(0)),
 ('competitor', np.int64(0)),
 ('concerns', np.int64(0)),
 ('consciousness', np.int64(0)),
 ('considered', np.int64(0)),
 ('consistent', np.int64(0)),
 ('contest', np.int64(0)),
 ('continue', np.int64(0)),
 ('continues', np.int64(1)),
 ('control', np.int64(0)),
 ('cool', np.int64(0)),
 ('cooper', np.int64(0)),
 ('corner', np.int64(0)),
 ('correspondent', np.int64(0)),
 ('costs', np.int64(0)),
 ('couldn', np.int64(0)),
 ('country', np.int64(2)),
 ('couple', np.int64(1)),
 ('course', np.int64(0)),
 ('covered', np.int64(0)),
 ('covid', np.int64(1)),
 ('crash', np.int64(0)),
 ('crashed', np.int64(0)),
 ('cross', np.int64(1)),
 ('crossword', np.int64(0)),
 ('crosswords', np.int64(0)),
 ('crown', np.int64(0)),
 ('cruel', np.int64(0)),
 ('cryptic', np.int64(0)),
 ('currently', np.int64(0)),
 ('daisy', np.int64(0)),
 ('day', np.int64(4)),
 ('days', np.int64(1)),
 ('debut', np.int64(0)),
 ('decades', np.int64(0)),
 ('december', np.int64(1)),
 ('decision', np.int64(0)),
 ('decorated', np.int64(0)),
 ('deep', np.int64(0)),
 ('defend', np.int64(0)),
 ('defending', np.int64(0)),
 ('definitely', np.int64(0)),
 ('degrees', np.int64(0)),
 ('depth', np.int64(0)),
 ('despite', np.int64(1)),
 ('did', np.int64(0)),
 ('didn', np.int64(0)),
 ('different', np.int64(0)),
 ('discipline', np.int64(0)),
 ('distance', np.int64(0)),
 ('does', np.int64(0)),
 ('doesn', np.int64(0)),
 ('doing', np.int64(0)),
 ('dominated', np.int64(1)),
 ('don', np.int64(0)),
 ('donald', np.int64(0)),
 ('double', np.int64(0)),
 ('dream', np.int64(0)),
 ('dropped', np.int64(0)),
 ('dual', np.int64(0)),
 ('earlier', np.int64(0)),
 ('early', np.int64(1)),
 ('ease', np.int64(0)),
 ('edged', np.int64(0)),
 ('editor', np.int64(0)),
 ('efforts', np.int64(0)),
 ('eighth', np.int64(0)),
 ('elite', np.int64(0)),
 ('elizabeth', np.int64(0)),
 ('email', np.int64(0)),
 ('end', np.int64(1)),
 ('ensure', np.int64(0)),
 ('entered', np.int64(0)),
 ('entertained', np.int64(0)),
 ('entirely', np.int64(0)),
 ('etched', np.int64(0)),
 ('europe', np.int64(1)),
 ('event', np.int64(1)),
 ('events', np.int64(2)),
 ('excited', np.int64(0)),
 ('expectations', np.int64(0)),
 ('expected', np.int64(1)),
 ('explains', np.int64(0)),
 ('extend', np.int64(0)),
 ('face', np.int64(0)),
 ('failing', np.int64(0)),
 ('failure', np.int64(0)),
 ('family', np.int64(0)),
 ('far', np.int64(1)),
 ('fashion', np.int64(0)),
 ('favourite', np.int64(0)),
 ('favourites', np.int64(0)),
 ('february', np.int64(3)),
 ('federal', np.int64(0)),
 ('feeling', np.int64(1)),
 ('feels', np.int64(0)),
 ('fellow', np.int64(0)),
 ('field', np.int64(0)),
 ('final', np.int64(1)),
 ('finalists', np.int64(0)),
 ('finally', np.int64(0)),
 ('finals', np.int64(0)),
 ('financial', np.int64(0)),
 ('finding', np.int64(0)),
 ('finish', np.int64(0)),
 ('finished', np.int64(1)),
 ('finishing', np.int64(0)),
 ('flag', np.int64(0)),
 ('flying', np.int64(1)),
 ('follow', np.int64(0)),
 ('following', np.int64(0)),
 ('football', np.int64(0)),
 ('foreign', np.int64(0)),
 ('forest', np.int64(0)),
 ('form', np.int64(0)),
 ('foundation', np.int64(0)),
 ('fourth', np.int64(0)),
 ('france', np.int64(0)),
 ('freeski', np.int64(1)),
 ('freestyle', np.int64(1)),
 ('french', np.int64(1)),
 ('friday', np.int64(0)),
 ('friends', np.int64(0)),
 ('funding', np.int64(0)),
 ('future', np.int64(0)),
 ('game', np.int64(1)),
 ('germany', np.int64(1)),
 ('given', np.int64(0)),
 ('glide', np.int64(0)),
 ('global', np.int64(0)),
 ('glory', np.int64(0)),
 ('going', np.int64(1)),
 ('good', np.int64(0)),
 ('got', np.int64(0)),
 ('government', np.int64(0)),
 ('graham', np.int64(0)),
 ('great', np.int64(1)),
 ('greatest', np.int64(0)),
 ('green', np.int64(0)),
 ('grew', np.int64(0)),
 ('growing', np.int64(0)),
 ('guardian', np.int64(1)),
 ('gun', np.int64(0)),
 ('guseli', np.int64(2)),
 ('half', np.int64(0)),
 ('halfpipe', np.int64(3)),
 ('hamilton', np.int64(0)),
 ('happened', np.int64(0)),
 ('happening', np.int64(0)),
 ('hard', np.int64(0)),
 ('harder', np.int64(0)),
 ('haul', np.int64(1)),
 ('having', np.int64(0)),
 ('head', np.int64(0)),
 ('heading', np.int64(0)),
 ('heating', np.int64(0)),
 ('heavy', np.int64(0)),
 ('help', np.int64(0)),
 ('high', np.int64(0)),
 ('higher', np.int64(0)),
 ('highest', np.int64(1)),
 ('highly', np.int64(0)),
 ('hiking', np.int64(1)),
 ('hill', np.int64(0)),
 ('historic', np.int64(0)),
 ('history', np.int64(0)),
 ('hit', np.int64(0)),
 ('home', np.int64(1)),
 ('hope', np.int64(1)),
 ('hopes', np.int64(0)),
 ('host', np.int64(1)),
 ('hours', np.int64(3)),
 ('huge', np.int64(0)),
 ('ice', np.int64(6)),
 ('imagine', np.int64(0)),
 ('immigration', np.int64(0)),
 ('improved', np.int64(0)),
 ('inbox', np.int64(0)),
 ('include', np.int64(1)),
 ('including', np.int64(2)),
 ('individual', np.int64(0)),
 ('indra', np.int64(2)),
 ('injured', np.int64(0)),
 ('injury', np.int64(0)),
 ('instead', np.int64(0)),
 ('interactive', np.int64(1)),
 ('international', np.int64(0)),
 ('invested', np.int64(0)),
 ('involves', np.int64(1)),
 ('involving', np.int64(0)),
 ('italy', np.int64(4)),
 ('jaelin', np.int64(0)),
 ('jakara', np.int64(1)),
 ('james', np.int64(2)),
 ('january', np.int64(1)),
 ('japan', np.int64(0)),
 ('job', np.int64(0)),
 ('joined', np.int64(0)),
 ('josie', np.int64(0)),
 ('journey', np.int64(0)),
 ('judged', np.int64(0)),
 ('judges', np.int64(0)),
 ('jump', np.int64(0)),
 ('jumping', np.int64(1)),
 ('jumps', np.int64(0)),
 ('just', np.int64(4)),
 ('kauf', np.int64(0)),
 ('key', np.int64(0)),
 ('knee', np.int64(0)),
 ('knew', np.int64(0)),
 ('know', np.int64(0)),
 ('known', np.int64(0)),
 ('laffont', np.int64(0)),
 ('lake', np.int64(0)),
 ('landed', np.int64(0)),
 ('landing', np.int64(0)),
 ('lara', np.int64(0)),
 ('largest', np.int64(1)),
 ('late', np.int64(0)),
 ('later', np.int64(0)),
 ('latest', np.int64(0)),
 ('launching', np.int64(0)),
 ('laura', np.int64(0)),
 ('lead', np.int64(0)),
 ('leading', np.int64(0)),
 ('league', np.int64(0)),
 ('learn', np.int64(0)),
 ('leave', np.int64(0)),
 ('leaving', np.int64(0)),
 ('led', np.int64(0)),
 ('left', np.int64(0)),
 ('legs', np.int64(0)),
 ('lemley', np.int64(0)),
 ('let', np.int64(0)),
 ('liberal', np.int64(0)),
 ('life', np.int64(0)),
 ('like', np.int64(0)),
 ('likely', np.int64(0)),
 ('line', np.int64(0)),
 ('little', np.int64(0)),
 ('live', np.int64(1)),
 ('livigno', np.int64(1)),
 ('living', np.int64(0)),
 ('ll', np.int64(0)),
 ('local', np.int64(1)),
 ('long', np.int64(0)),
 ('looking', np.int64(0)),
 ('losing', np.int64(0)),
 ('lost', np.int64(0)),
 ('lot', np.int64(0)),
 ('love', np.int64(1)),
 ('luge', np.int64(1)),
 ('mail', np.int64(0)),
 ('make', np.int64(0)),
 ('makes', np.int64(0)),
 ('making', np.int64(0)),
 ('man', np.int64(0)),
 ('mark', np.int64(1)),
 ('martin', np.int64(1)),
 ('matt', np.int64(0)),
 ('matter', np.int64(0)),
 ('medallist', np.int64(0)),
 ('medallists', np.int64(2)),
 ('medals', np.int64(2)),
 ('media', np.int64(0)),
 ('medical', np.int64(0)),
 ('meet', np.int64(0)),
 ('melbourne', np.int64(0)),
 ('member', np.int64(0)),
 ('men', np.int64(2)),
 ('metres', np.int64(0)),
 ('milan', np.int64(1)),
 ('minister', np.int64(0)),
 ('minutes', np.int64(0)),
 ('miss', np.int64(0)),
 ('missed', np.int64(1)),
 ('missing', np.int64(1)),
 ('mission', np.int64(0)),
 ('mix', np.int64(0)),
 ('mixed', np.int64(2)),
 ('mogul', np.int64(1)),
 ('moguls', np.int64(0)),
 ('moment', np.int64(0)),
 ('moments', np.int64(0)),
 ('month', np.int64(0)),
 ('months', np.int64(0)),
 ('morning', np.int64(0)),
 ('moscow', np.int64(0)),
 ('mother', np.int64(0)),
 ('mount', np.int64(0)),
 ('mountain', np.int64(0)),
 ('mountaineering', np.int64(3)),
 ('mountains', np.int64(0)),
 ('nailed', np.int64(0)),
 ('nation', np.int64(0)),
 ('national', np.int64(0)),
 ('neck', np.int64(0)),
 ('need', np.int64(0)),
 ('needed', np.int64(0)),
 ('needs', np.int64(0)),
 ('nervous', np.int64(0)),
 ('new', np.int64(5)),
 ('news', np.int64(1)),
 ('newsletter', np.int64(1)),
 ('nice', np.int64(0)),
 ('night', np.int64(0)),
 ('northern', np.int64(2)),
 ('norway', np.int64(1)),
 ('nsw', np.int64(0)),
 ('number', np.int64(0)),
 ('occasion', np.int64(0)),
 ('officials', np.int64(0)),
 ('ok', np.int64(0)),
 ('olympian', np.int64(1)),
 ('open', np.int64(1)),
 ('opening', np.int64(2)),
 ('opportunity', np.int64(0)),
 ('overall', np.int64(0)),
 ('overcame', np.int64(0)),
 ('overcome', np.int64(0)),
 ('overcoming', np.int64(0)),
 ('overnight', np.int64(0)),
 ('pace', np.int64(0)),
 ('pain', np.int64(0)),
 ('pair', np.int64(0)),
 ('parents', np.int64(0)),
 ('partner', np.int64(0)),
 ('pass', np.int64(0)),
 ('past', np.int64(0)),
 ('peak', np.int64(0)),
 ('peel', np.int64(0)),
 ('pegan', np.int64(1)),
 ('people', np.int64(0)),
 ('perfect', np.int64(0)),
 ('performance', np.int64(0)),
 ('perisher', np.int64(0)),
 ('perrine', np.int64(0)),
 ('peter', np.int64(0)),
 ('pictures', np.int64(1)),
 ('place', np.int64(1)),
 ('playing', np.int64(1)),
 ('podium', np.int64(0)),
 ('podiums', np.int64(0)),
 ('point', np.int64(0)),
 ('points', np.int64(0)),
 ('political', np.int64(0)),
 ('politics', np.int64(0)),
 ('position', np.int64(0)),
 ('possibility', np.int64(0)),
 ('power', np.int64(0)),
 ('practice', np.int64(0)),
 ('pre', np.int64(0)),
 ('pressure', np.int64(0)),
 ('prestigious', np.int64(0)),
 ('pretty', np.int64(0)),
 ('prices', np.int64(0)),
 ('pride', np.int64(0)),
 ('process', np.int64(0)),
 ('professional', np.int64(0)),
 ('program', np.int64(0)),
 ('progress', np.int64(0)),
 ('progression', np.int64(0)),
 ('proud', np.int64(0)),
 ('public', np.int64(0)),
 ('pulled', np.int64(0)),
 ('push', np.int64(0)),
 ('pyeongchang', np.int64(0)),
 ('qualifying', np.int64(1)),
 ('quarter', np.int64(0)),
 ('queensland', np.int64(0)),
 ('quick', np.int64(0)),
 ('quickly', np.int64(0)),
 ('quite', np.int64(1)),
 ('race', np.int64(0)),
 ('raised', np.int64(0)),
 ('ranked', np.int64(2)),
 ('rare', np.int64(0)),
 ('realised', np.int64(0)),
 ('really', np.int64(0)),
 ('receive', np.int64(0)),
 ('recent', np.int64(1)),
 ('record', np.int64(1)),
 ('recorded', np.int64(0)),
 ('recover', np.int64(0)),
 ('refused', np.int64(0)),
 ('reged', np.int64(0)),
 ('regrets', np.int64(0)),
 ('regular', np.int64(0)),
 ('reigning', np.int64(0)),
 ('related', np.int64(2)),
 ('relay', np.int64(2)),
 ('remains', np.int64(0)),
 ('remarkable', np.int64(0)),
 ('repeat', np.int64(0)),
 ('reports', np.int64(0)),
 ('rest', np.int64(0)),
 ('results', np.int64(0)),
 ('return', np.int64(0)),
 ('returning', np.int64(0)),
 ('richard', np.int64(0)),
 ('right', np.int64(0)),
 ('rise', np.int64(0)),
 ('round', np.int64(0)),
 ('rounds', np.int64(0)),
 ('roundup', np.int64(0)),
 ('row', np.int64(0)),
 ('run', np.int64(2)),
 ('running', np.int64(1)),
 ('runs', np.int64(0)),
 ('ruptured', np.int64(0)),
 ('said', np.int64(0)),
 ('sarah', np.int64(0)),
 ('saturday', np.int64(1)),
 ('saw', np.int64(0)),
 ('say', np.int64(0)),
 ('says', np.int64(0)),
 ('schedule', np.int64(1)),
 ('school', np.int64(0)),
 ('score', np.int64(0)),
 ('scoring', np.int64(0)),
 ('scotty', np.int64(1)),
 ('season', np.int64(0)),
 ('second', np.int64(1)),
 ('secured', np.int64(0)),
 ('seen', np.int64(0)),
 ('semi', np.int64(0)),
 ('set', np.int64(0)),
 ('seven', np.int64(0)),
 ('seventh', np.int64(0)),
 ('shadow', np.int64(0)),
 ('sharing', np.int64(0)),
 ('shock', np.int64(0)),
 ('short', np.int64(0)),
 ('shown', np.int64(0)),
 ('sign', np.int64(1)),
 ('significant', np.int64(0)),
 ('signing', np.int64(0)),
 ('silver', np.int64(3)),
 ('single', np.int64(0)),
 ('singles', np.int64(0)),
 ('site', np.int64(0)),
 ('skater', np.int64(0)),
 ('ski', np.int64(4)),
 ('skier', np.int64(1)),
 ('skiers', np.int64(0)),
 ('skiing', np.int64(4)),
 ('skills', np.int64(0)),
 ('skimo', np.int64(1)),
 ('skins', np.int64(1)),
 ('skis', np.int64(1)),
 ('slalom', np.int64(0)),
 ('slip', np.int64(0)),
 ('slopes', np.int64(0)),
 ('smile', np.int64(0)),
 ('smith', np.int64(0)),
 ('snow', np.int64(0)),
 ('snowboard', np.int64(2)),
 ('snowboarder', np.int64(0)),
 ('snowboarders', np.int64(1)),
 ('snowboarding', np.int64(0)),
 ('social', np.int64(0)),
 ('sort', np.int64(0)),
 ('south', np.int64(0)),
 ('speaks', np.int64(0)),
 ('special', np.int64(0)),
 ('speed', np.int64(0)),
 ('sporting', np.int64(1)),
 ('sports', np.int64(2)),
 ('spot', np.int64(1)),
 ('spotlight', np.int64(0)),
 ('sprint', np.int64(2)),
 ('staff', np.int64(0)),
 ('standing', np.int64(0)),
 ('star', np.int64(0)),
 ('start', np.int64(1)),
 ('started', np.int64(0)),
 ('starting', np.int64(0)),
 ('starts', np.int64(1)),
 ('state', np.int64(0)),
 ('statement', np.int64(0)),
 ('stay', np.int64(0)),
 ('staying', np.int64(0)),
 ('step', np.int64(0)),
 ('steven', np.int64(0)),
 ('stoked', np.int64(0)),
 ('story', np.int64(0)),
 ('strategy', np.int64(0)),
 ('strength', np.int64(0)),
 ('strong', np.int64(0)),
 ('stuck', np.int64(0)),
 ('stuff', np.int64(0)),
 ('success', np.int64(0)),
 ('successful', np.int64(0)),
 ('summit', np.int64(0)),
 ('sun', np.int64(0)),
 ('sunday', np.int64(0)),
 ('support', np.int64(0)),
 ('swept', np.int64(0)),
 ('switzerland', np.int64(0)),
 ('sydney', np.int64(0)),
 ('table', np.int64(3)),
 ('taking', np.int64(0)),
 ('team', np.int64(3)),
 ('teammates', np.int64(0)),
 ('teaser', np.int64(0)),
 ('tech', np.int64(0)),
 ('teenager', np.int64(1)),
 ('tess', np.int64(1)),
 ('thing', np.int64(0)),
 ('things', np.int64(0)),
 ('think', np.int64(0)),
 ('thomas', np.int64(0)),
 ('thought', np.int64(0)),
 ('threat', np.int64(0)),
 ('thursday', np.int64(0)),
 ('time', np.int64(4)),
 ('times', np.int64(0)),
 ('title', np.int64(0)),
 ('today', np.int64(0)),
 ('told', np.int64(0)),
 ('tomorrow', np.int64(0)),
 ('took', np.int64(0)),
 ('topalovic', np.int64(0)),
 ('total', np.int64(0)),
 ('tougher', np.int64(0)),
 ('town', np.int64(0)),
 ('track', np.int64(0)),
 ('training', np.int64(0)),
 ('trick', np.int64(0)),
 ('triumph', np.int64(0)),
 ('trump', np.int64(0)),
 ('trumpland', np.int64(0)),
 ('try', np.int64(0)),
 ('trying', np.int64(0)),
 ('turin', np.int64(1)),
 ('turn', np.int64(0)),
 ('turned', np.int64(0)),
 ('turns', np.int64(0)),
 ('twice', np.int64(0)),
 ('uk', np.int64(0)),
 ('unable', np.int64(0)),
 ('unlikely', np.int64(0)),
 ('unprecedented', np.int64(0)),
 ('update', np.int64(0)),
 ('use', np.int64(0)),
 ('valentino', np.int64(1)),
 ('valley', np.int64(0)),
 ('ve', np.int64(0)),
 ('veteran', np.int64(0)),
 ('victoria', np.int64(0)),
 ('victory', np.int64(0)),
 ('wales', np.int64(0)),
 ('want', np.int64(0)),
 ('wanted', np.int64(0)),
 ('war', np.int64(0)),
 ('wasn', np.int64(0)),
 ('watch', np.int64(4)),
 ('water', np.int64(0)),
 ('waterville', np.int64(0)),
 ('way', np.int64(0)),
 ('week', np.int64(0)),
 ('weekday', np.int64(0)),
 ('weeks', np.int64(2)),
 ('weight', np.int64(0)),
 ('went', np.int64(0)),
 ('win', np.int64(0)),
 ('winner', np.int64(0)),
 ('winning', np.int64(0)),
 ('wins', np.int64(0)),
 ('woman', np.int64(0)),
 ('women', np.int64(1)),
 ('won', np.int64(1)),
 ('woods', np.int64(0)),
 ('work', np.int64(0)),
 ('worst', np.int64(0)),
 ('years', np.int64(1)),
 ('yellow', np.int64(0)),
 ('youngest', np.int64(1)),
 ('zealand', np.int64(1))]

In [14]:
# Take a look at the vocabulary which shows the total counts for whole collection
count_vectorizer.vocabulary_

{'2026': np.int64(16),
 'start': np.int64(624),
 'open': np.int64(464),
 'early': np.int64(211),
 'hours': np.int64(321),
 'saturday': np.int64(562),
 'february': np.int64(242),
 'time': np.int64(665),
 'opening': np.int64(465),
 'ceremony': np.int64(119),
 'milan': np.int64(421),
 'run': np.int64(556),
 'weeks': np.int64(712),
 'closing': np.int64(138),
 '23': np.int64(19),
 'aedt': np.int64(41),
 'sports': np.int64(617),
 'including': np.int64(329),
 'ice': np.int64(323),
 'begin': np.int64(82),
 'couple': np.int64(167),
 'days': np.int64(182),
 'mixed': np.int64(429),
 'team': np.int64(652),
 'just': np.int64(355),
 'missed': np.int64(425),
 'qualifying': np.int64(517),
 'despite': np.int64(194),
 'ranked': np.int64(525),
 'december': np.int64(185),
 'won': np.int64(721),
 'italy': np.int64(340),
 'final': np.int64(248),
 'event': np.int64(227),
 'men': np.int64(419),
 'game': np.int64(275),
 '12': np.int64(3),
 'related': np.int64(539),
 'youngest': np.int64(727),
 'olympian': np.int64(463),
 'indra': np.int64(331),
 'brown': np.int64(104),
 'love': np.int64(400),
 'feeling': np.int64(244),
 'flying': np.int64(258),
 'martin': np.int64(408),
 'pegan': np.int64(481),
 'place': np.int64(489),
 'northern': np.int64(456),
 'livigno': np.int64(391),
 'athletes': np.int64(66),
 '15': np.int64(4),
 'competing': np.int64(148),
 'host': np.int64(320),
 'turin': np.int64(684),
 '2006': np.int64(11),
 'interactive': np.int64(335),
 'watch': np.int64(706),
 'guardian': np.int64(291),
 'live': np.int64(390),
 'day': np.int64(181),
 '10': np.int64(1),
 'schedule': np.int64(566),
 'starts': np.int64(627),
 'local': np.int64(394),
 'sign': np.int64(584),
 'briefing': np.int64(98),
 'newsletter': np.int64(453),
 'best': np.int64(85),
 'come': np.int64(144),
 'new': np.int64(451),
 'ski': np.int64(592),
 'mountaineering': np.int64(441),
 'skimo': np.int64(597),
 'involves': np.int64(338),
 'skiing': np.int64(595),
 'skins': np.int64(598),
 'hiking': np.int64(312),
 'skis': np.int64(599),
 'athlete': np.int64(65),
 'events': np.int64(228),
 'sprint': np.int64(620),
 'women': np.int64(720),
 'relay': np.int64(540),
 'luge': np.int64(401),
 'jumping': np.int64(353),
 'freestyle': np.int64(269),
 'alpine': np.int64(53),
 '000': np.int64(0),
 'medals': np.int64(413),
 'hope': np.int64(318),
 'cross': np.int64(173),
 'country': np.int64(166),
 'running': np.int64(557),
 'french': np.int64(270),
 'alps': np.int64(54),
 'going': np.int64(281),
 'table': np.int64(650),
 'norway': np.int64(457),
 'spot': np.int64(618),
 'collecting': np.int64(143),
 '16': np.int64(5),
 'silver': np.int64(587),
 'bronze': np.int64(102),
 '2022': np.int64(13),
 'ahead': np.int64(47),
 'germany': np.int64(276),
 'beijing': np.int64(83),
 'dominated': np.int64(203),
 'europe': np.int64(226),
 'america': np.int64(55),
 'china': np.int64(129),
 'highest': np.int64(310),
 'asian': np.int64(63),
 'second': np.int64(572),
 'largest': np.int64(367),
 '53': np.int64(27),
 'recent': np.int64(530),
 'circuit': np.int64(130),
 'record': np.int64(531),
 'haul': np.int64(301),
 'years': np.int64(725),
 'ago': np.int64(46),
 'finished': np.int64(255),
 'zealand': np.int64(728),
 'great': np.int64(286),
 'coming': np.int64(145),
 'home': np.int64(317),
 'pictures': np.int64(488),
 'medallists': np.int64(412),
 'mogul': np.int64(430),
 'skier': np.int64(593),
 'jakara': np.int64(342),
 'anthony': np.int64(59),
 'snowboarders': np.int64(608),
 'scotty': np.int64(570),
 'james': np.int64(343),
 'tess': np.int64(657),
 'coady': np.int64(141),
 'missing': np.int64(426),
 'include': np.int64(328),
 'teenager': np.int64(656),
 'freeski': np.int64(268),
 'halfpipe': np.int64(295),
 'valentino': np.int64(695),
 'guseli': np.int64(293),
 'snowboard': np.int64(606),
 'mark': np.int64(407),
 'end': np.int64(220),
 'january': np.int64(344),
 'big': np.int64(88),
 'news': np.int64(452),
 'covid': np.int64(170),
 'far': np.int64(238),
 'sporting': np.int64(616),
 'competition': np.int64(149),
 'playing': np.int64(490),
 'continues': np.int64(158),
 'attempt': np.int64(68),
 'australians': np.int64(70),
 'expected': np.int64(231),
 'quite': np.int64(522),
 'wasn': np.int64(705),
 'cruel': np.int64(177),
 'moguls': np.int64(431),
 'left': np.int64(380),
 'field': np.int64(247),
 'podium': np.int64(491),
 'success': np.int64(641),
 'failure': np.int64(236),
 'hard': np.int64(299),
 'snow': np.int64(605),
 'defending': np.int64(190),
 'medallist': np.int64(411),
 'thursday': np.int64(664),
 'morning': np.int64(436),
 'week': np.int64(710),
 '27': np.int64(22),
 'recorded': np.int64(532),
 'score': np.int64(568),
 'round': np.int64(552),
 'didn': np.int64(196),
 'couldn': np.int64(165),
 'stay': np.int64(630),
 'course': np.int64(168),
 'slip': np.int64(601),
 'costs': np.int64(164),
 'title': np.int64(667),
 'flag': np.int64(257),
 'bearer': np.int64(78),
 'things': np.int64(659),
 'yellow': np.int64(726),
 'green': np.int64(288),
 'staff': np.int64(621),
 'training': np.int64(677),
 'base': np.int64(75),
 'began': np.int64(81),
 'officials': np.int64(461),
 'pre': np.int64(501),
 'entirely': np.int64(224),
 'medical': np.int64(415),
 'aerials': np.int64(43),
 'veteran': np.int64(698),
 'laura': np.int64(372),
 'peel': np.int64(480),
 'significant': np.int64(585),
 'knee': np.int64(358),
 'injury': np.int64(333),
 'doing': np.int64(202),
 'recover': np.int64(533),
 'compete': np.int64(146),
 'fourth': np.int64(266),
 'daisy': np.int64(180),
 'thomas': np.int64(661),
 'landed': np.int64(364),
 'jump': np.int64(352),
 'injured': np.int64(332),
 'right': np.int64(550),
 'pulled': np.int64(514),
 'hopes': np.int64(319),
 'air': np.int64(49),
 'discipline': np.int64(198),
 'broken': np.int64(101),
 'neck': np.int64(446),
 'snowboarder': np.int64(607),
 'hit': np.int64(316),
 'head': np.int64(303),
 'failing': np.int64(235),
 'assessment': np.int64(64),
 'looking': np.int64(396),
 'losing': np.int64(397),
 'control': np.int64(159),
 'hill': np.int64(313),
 'twice': np.int64(688),
 'leaving': np.int64(378),
 'reigning': np.int64(538),
 'champion': np.int64(121),
 'finalists': np.int64(249),
 'degrees': np.int64(192),
 'short': np.int64(582),
 'unlikely': np.int64(691),
 'bid': np.int64(87),
 'seventh': np.int64(578),
 'alongside': np.int64(52),
 'favourite': np.int64(240),
 '31': np.int64(25),
 'entered': np.int64(222),
 'performance': np.int64(484),
 'american': np.int64(56),
 'thought': np.int64(662),
 'told': np.int64(669),
 'think': np.int64(660),
 'peak': np.int64(479),
 'added': np.int64(37),
 'like': np.int64(386),
 'future': np.int64(274),
 'high': np.int64(308),
 'slopes': np.int64(602),
 'work': np.int64(723),
 'progress': np.int64(510),
 'secured': np.int64(573),
 'track': np.int64(676),
 '1994': np.int64(7),
 'remains': np.int64(541),
 'chef': np.int64(126),
 'mission': np.int64(427),
 'alisa': np.int64(50),
 'camplin': np.int64(111),
 'breadth': np.int64(96),
 'depth': np.int64(193),
 'international': np.int64(336),
 'months': np.int64(435),
 'dual': np.int64(209),
 'nation': np.int64(444),
 'consciousness': np.int64(153),
 'turn': np.int64(685),
 'lead': np.int64(373),
 'foundation': np.int64(265),
 'lara': np.int64(366),
 'hamilton': np.int64(296),
 'brought': np.int64(103),
 'sarah': np.int64(561),
 '21': np.int64(18),
 'professional': np.int64(508),
 'support': np.int64(646),
 'federal': np.int64(243),
 'government': np.int64(284),
 'make': np.int64(403),
 'opportunity': np.int64(466),
 'miss': np.int64(424),
 'foreign': np.int64(262),
 'winning': np.int64(717),
 'thing': np.int64(658),
 'appeal': np.int64(60),
 'moment': np.int64(432),
 'long': np.int64(395),
 'nice': np.int64(454),
 'brutal': np.int64(105),
 'known': np.int64(361),
 'little': np.int64(389),
 'claiming': np.int64(133),
 'national': np.int64(445),
 'turned': np.int64(686),
 'learn': np.int64(376),
 'overcoming': np.int64(470),
 'single': np.int64(588),
 'family': np.int64(237),
 'friends': np.int64(272),
 'teammates': np.int64(653),
 'later': np.int64(369),
 'smile': np.int64(603),
 'face': np.int64(234),
 'bit': np.int64(90),
 'happened': np.int64(297),
 'said': np.int64(560),
 'triumph': np.int64(679),
 'really': np.int64(528),
 'singles': np.int64(589),
 'came': np.int64(109),
 'chance': np.int64(123),
 'taking': np.int64(651),
 'step': np.int64(632),
 'elite': np.int64(217),
 'know': np.int64(360),
 'able': np.int64(28),
 'help': np.int64(307),
 'pretty': np.int64(504),
 'makes': np.int64(404),
 'special': np.int64(614),
 'arrived': np.int64(62),
 'history': np.int64(315),
 'following': np.int64(260),
 'set': np.int64(576),
 'rounds': np.int64(553),
 'prices': np.int64(505),
 'winner': np.int64(716),
 'amid': np.int64(57),
 'rare': np.int64(526),
 'worst': np.int64(724),
 'corner': np.int64(162),
 'decades': np.int64(184),
 'competed': np.int64(147),
 'half': np.int64(294),
 'heading': np.int64(304),
 'lot': np.int64(399),
 'glory': np.int64(280),
 'got': np.int64(283),
 'needed': np.int64(448),
 'different': np.int64(197),
 'trying': np.int64(683),
 'swept': np.int64(647),
 'judges': np.int64(351),
 'quarter': np.int64(518),
 'closer': np.int64(137),
 'pair': np.int64(474),
 'way': np.int64(709),
 'huge': np.int64(322),
 'statement': np.int64(629),
 'beating': np.int64(80),
 'elizabeth': np.int64(218),
 'lemley': np.int64(382),
 'semi': np.int64(575),
 'runs': np.int64(558),
 'win': np.int64(715),
 'jaelin': np.int64(341),
 'kauf': np.int64(356),
 'instead': np.int64(334),
 'etched': np.int64(225),
 'victory': np.int64(700),
 'making': np.int64(405),
 'successful': np.int64(642),
 'cooper': np.int64(161),
 'woods': np.int64(722),
 'josie': np.int64(348),
 'baff': np.int64(74),
 'ease': np.int64(212),
 'pain': np.int64(473),
 'shock': np.int64(581),
 'eighth': np.int64(216),
 'finish': np.int64(254),
 'given': np.int64(277),
 'overcome': np.int64(469),
 'started': np.int64(625),
 'child': np.int64(127),
 'parents': np.int64(475),
 'let': np.int64(383),
 'went': np.int64(714),
 'school': np.int64(567),
 'south': np.int64(612),
 'wales': np.int64(701),
 'town': np.int64(675),
 'perisher': np.int64(485),
 'children': np.int64(128),
 'debut': np.int64(183),
 'pace': np.int64(472),
 'says': np.int64(565),
 'saw': np.int64(563),
 'heavy': np.int64(306),
 'invested': np.int64(337),
 'stuff': np.int64(640),
 'knew': np.int64(359),
 'mountain': np.int64(440),
 'quickly': np.int64(521),
 'key': np.int64(357),
 'journey': np.int64(349),
 'race': np.int64(523),
 '17': np.int64(6),
 'ok': np.int64(462),
 'actually': np.int64(36),
 'good': np.int64(282),
 'better': np.int64(86),
 'sydney': np.int64(649),
 'results': np.int64(546),
 'point': np.int64(493),
 'starting': np.int64(626),
 'catch': np.int64(117),
 'highly': np.int64(311),
 'cool': np.int64(160),
 'try': np.int64(682),
 'distance': np.int64(199),
 'mix': np.int64(428),
 'need': np.int64(447),
 'life': np.int64(385),
 'pass': np.int64(477),
 'forest': np.int64(263),
 'say': np.int64(564),
 'sun': np.int64(644),
 'calm': np.int64(108),
 'coach': np.int64(140),
 '2025': np.int64(15),
 'improved': np.int64(326),
 'excited': np.int64(229),
 'finding': np.int64(253),
 'achieve': np.int64(32),
 'strong': np.int64(638),
 'state': np.int64(628),
 'feels': np.int64(245),
 'living': np.int64(392),
 'covered': np.int64(169),
 'funding': np.int64(273),
 'job': np.int64(346),
 'season': np.int64(571),
 'rest': np.int64(545),
 'challenge': np.int64(120),
 'called': np.int64(107),
 'progression': np.int64(511),
 'times': np.int64(666),
 'month': np.int64(434),
 'having': np.int64(302),
 'competitions': np.int64(150),
 'line': np.int64(388),
 'individual': np.int64(330),
 'does': np.int64(200),
 'stuck': np.int64(639),
 'don': np.int64(204),
 'snowboarding': np.int64(609),
 'star': np.int64(623),
 'landing': np.int64(365),
 'continue': np.int64(157),
 'fashion': np.int64(239),
 '20': np.int64(9),
 'unable': np.int64(690),
 'jumps': np.int64(354),
 'night': np.int64(455),
 '10th': np.int64(2),
 'japan': np.int64(345),
 'harder': np.int64(300),
 'wanted': np.int64(703),
 'regrets': np.int64(536),
 'stoked': np.int64(634),
 'competitor': np.int64(151),
 'canadian': np.int64(113),
 'man': np.int64(406),
 'repeat': np.int64(543),
 'pressure': np.int64(502),
 'number': np.int64(459),
 'nailed': np.int64(443),
 '50': np.int64(26),
 'wins': np.int64(718),
 'today': np.int64(668),
 'did': np.int64(195),
 'trick': np.int64(678),
 'ruptured': np.int64(559),
 'acl': np.int64(34),
 'late': np.int64(368),
 '2024': np.int64(14),
 'biggest': np.int64(89),
 'definitely': np.int64(191),
 'edged': np.int64(213),
 'total': np.int64(673),
 'points': np.int64(494),
 'contest': np.int64(156),
 'considered': np.int64(154),
 'blow': np.int64(92),
 'crash': np.int64(171),
 'coast': np.int64(142),
 'proud': np.int64(512),
 'aerial': np.int64(42),
 'crashed': np.int64(172),
 'switzerland': np.int64(648),
 'based': np.int64(76),
 'strength': np.int64(637),
 '20th': np.int64(17),
 'position': np.int64(497),
 'follow': np.int64(259),
 'sunday': np.int64(645),
 'consistent': np.int64(155),
 'global': np.int64(279),
 'seven': np.int64(577),
 'celebrated': np.int64(118),
 'moments': np.int64(433),
 'bradbury': np.int64(94),
 'steven': np.int64(633),
 'accepted': np.int64(29),
 'legs': np.int64(381),
 'speed': np.int64(615),
 'power': np.int64(499),
 'lake': np.int64(363),
 'city': np.int64(131),
 '2002': np.int64(10),
 'finals': np.int64(251),
 'higher': np.int64(309),
 '28': np.int64(23),
 'metres': np.int64(420),
 'took': np.int64(671),
 'arms': np.int64(61),
 'glide': np.int64(278),
 'claim': np.int64(132),
 'pride': np.int64(506),
 'breakthrough': np.int64(97),
 'prestigious': np.int64(503),
 'slalom': np.int64(600),
 'earlier': np.int64(210),
 'woman': np.int64(719),
 '1998': np.int64(8),
 'finishing': np.int64(256),
 'skiers': np.int64(594),
 'advice': np.int64(40),
 'double': np.int64(206),
 'overcame': np.int64(468),
 '2010': np.int64(12),
 'extend': np.int64(233),
 'skater': np.int64(591),
 'richard': np.int64(549),
 'backed': np.int64(73),
 'strategy': np.int64(636),
 'staying': np.int64(631),
 'battling': np.int64(77),
 'smith': np.int64(604),
 'change': np.int64(124),
 'canada': np.int64(112),
 'age': np.int64(45),
 'tech': np.int64(655),
 'claims': np.int64(134),
 'sort': np.int64(611),
 'scoring': np.int64(569),
 'leave': np.int64(377),
 'champions': np.int64(122),
 'joined': np.int64(347),
 'overnight': np.int64(471),
 'dropped': np.int64(208),
 'launching': np.int64(371),
 'favourites': np.int64(241),
 'bring': np.int64(99),
 'member': np.int64(418),
 'want': np.int64(702),
 've': np.int64(697),
 'mother': np.int64(438),
 'imagine': np.int64(324),
 'occasion': np.int64(460),
 'attention': np.int64(69),
 'minutes': np.int64(423),
 'captain': np.int64(115),
 'chasing': np.int64(125),
 'allegedly': np.int64(51),
 'melbourne': np.int64(417),
 'shown': np.int64(583),
 'away': np.int64(72),
 'spotlight': np.int64(619),
 'camp': np.int64(110),
 'meet': np.int64(416),
 'crown': np.int64(176),
 'pyeongchang': np.int64(516),
 'returning': np.int64(548),
 'regular': np.int64(537),
 'mountains': np.int64(442),
 'annual': np.int64(58),
 'mount': np.int64(439),
 'victoria': np.int64(699),
 'sharing': np.int64(580),
 'podiums': np.int64(492),
 'grew': np.int64(289),
 'push': np.int64(515),
 'realised': np.int64(527),
 'skills': np.int64(596),
 'close': np.int64(136),
 'leading': np.int64(374),
 'nervous': np.int64(450),
 'process': np.int64(507),
 'practice': np.int64(500),
 'standing': np.int64(622),
 'deep': np.int64(188),
 'quick': np.int64(520),
 'doesn': np.int64(201),
 'historic': np.int64(314),
 'overall': np.int64(467),
 'weight': np.int64(713),
 'currently': np.int64(179),
 'action': np.int64(35),
 'unprecedented': np.int64(692),
 'decorated': np.int64(187),
 'matt': np.int64(409),
 'graham': np.int64(285),
 'program': np.int64(509),
 'dream': np.int64(207),
 'peter': np.int64(487),
 'topalovic': np.int64(672),
 'ensure': np.int64(221),
 'queensland': np.int64(519),
 'water': np.int64(707),
 'explains': np.int64(232),
 'past': np.int64(478),
 'tougher': np.int64(674),
 'concerns': np.int64(152),
 'acknowledged': np.int64(33),
 'minister': np.int64(422),
 'blood': np.int64(91),
 'public': np.int64(513),
 'latest': np.int64(370),
 'financial': np.int64(252),
 'body': np.int64(93),
 'efforts': np.int64(215),
 'partner': np.int64(476),
 'possibility': np.int64(498),
 'summit': np.int64(643),
 '30': np.int64(24),
 'defend': np.int64(189),
 'greatest': np.int64(287),
 'fellow': np.int64(246),
 'decision': np.int64(186),
 'row': np.int64(555),
 'people': np.int64(482),
 '25': np.int64(20),
 'cabinet': np.int64(106),
 '26': np.int64(21),
 'awarded': np.int64(71),
 'raised': np.int64(524),
 'judged': np.int64(350),
 'turns': np.int64(687),
 'perfect': np.int64(483),
 'waterville': np.int64(708),
 'valley': np.int64(696),
 'france': np.int64(267),
 'perrine': np.int64(486),
 'laffont': np.int64(362),
 'threat': np.int64(663),
 'career': np.int64(116),
 'remarkable': np.int64(542),
 'form': np.int64(264),
 'media': np.int64(414),
 'expectations': np.int64(230),
 'likely': np.int64(387),
 'seen': np.int64(574),
 'll': np.int64(393),
 'nsw': np.int64(458),
 'friday': np.int64(271),
 'club': np.int64(139),
 'beat': np.int64(79),
 'use': np.int64(694),
 'lost': np.int64(398),
 'growing': np.int64(290),
 'tomorrow': np.int64(670),
 'rise': np.int64(551),
 'refused': np.int64(534),
 'site': np.int64(590),
 'social': np.int64(610),
 'matter': np.int64(410),
 'story': np.int64(635),
 'liberal': np.int64(384),
 'shadow': np.int64(579),
 'gun': np.int64(292),
 'according': np.int64(30),
 'editor': np.int64(214),
 'climate': np.int64(135),
 'attack': np.int64(67),
 'capital': np.int64(114),
 'donald': np.int64(205),
 'trump': np.int64(680),
 'involving': np.int64(339),
 'accused': np.int64(31),
 'moscow': np.int64(437),
 'uk': np.int64(689),
 'british': np.int64(100),
 'immigration': np.int64(325),
 'war': np.int64(704),
 'political': np.int64(495),
 'reged': np.int64(535),
 'ahmad': np.int64(48),
 'speaks': np.int64(613),
 'correspondent': np.int64(163),
 'ben': np.int64(84),
 'needs': np.int64(449),
 'heating': np.int64(305),
 'return': np.int64(547),
 'led': np.int64(379),
 'football': np.int64(261),
 'league': np.int64(375),
 'roundup': np.int64(554),
 'adelaide': np.int64(38),
 'reports': np.int64(544),
 'advertiser': np.int64(39),
 'happening': np.int64(298),
 'receive': np.int64(529),
 'mail': np.int64(402),
 'update': np.int64(693),
 'email': np.int64(219),
 'inbox': np.int64(327),
 'weekday': np.int64(711),
 'afternoon': np.int64(44),
 'politics': np.int64(496),
 'signing': np.int64(586),
 'trumpland': np.int64(681),
 'brain': np.int64(95),
 'teaser': np.int64(654),
 'finally': np.int64(250),
 'crosswords': np.int64(175),
 'entertained': np.int64(223),
 'crossword': np.int64(174),
 'cryptic': np.int64(178)}

#### Display matrix in dataframe

Take the term count matrix and display in a dataframe to make visible the structure

In [15]:
# Create a new dataframe with the matrix - use titles for the index and terms for the columns
count_df = pd.DataFrame(count_dt_matrix.toarray(), columns=feature_names)
count_df

,000,10,10th,12,15,16,17,1994,1998,20,...,woman,women,won,woods,work,worst,years,yellow,youngest,zealand
0,1,1,0,3,2,1,0,0,0,0,...,0,1,1,0,0,0,1,0,1,1
1,3,0,0,0,0,1,0,1,0,0,...,0,1,3,0,1,0,0,1,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,2,0,1,0,1,2,0,0,0
3,0,0,0,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,0,0
4,0,0,1,1,0,1,0,0,0,1,...,0,1,1,0,0,0,0,0,0,0
5,0,0,0,1,1,0,0,1,1,0,...,1,0,0,0,0,0,3,0,0,0
6,0,0,0,0,2,2,0,0,0,0,...,0,1,1,0,0,0,2,0,1,1
7,0,0,0,1,0,2,0,1,1,0,...,0,0,3,2,0,0,2,0,1,0
8,0,0,0,0,1,2,1,0,0,3,...,3,1,1,0,0,0,1,0,0,0
9,0,0,0,0,1,0,0,0,0,0,...,0,0,0,11,1,0,0,0,0,0
10,0,0,0,0,1,0,0,0,0,1,...,0,0,3,1,0,0,2,1,0,0
11,0,1,1,0,1,0,0,0,0,0,...,0,2,1,0,0,0,1,0,0,0
12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,1,0,0,0

Keep a list of the titles of the articles to make it easy to see the headline that relates to the topics. We can always go back to the original documents if we need to.

In [16]:
titles=list(articles.keys())
titles

['Winter Olympics 2026: what you need to know if following from Australia [2026-02-02T14:00:10Z]',
 'Australia’s upward trajectory slips off course as Winter Olympics medal search goes on | Jack Snape [2026-02-12T03:36:06Z]',
 '‘Even more special’: Jakara Anthony dusts off Winter Olympics heartbreak for historic triumph [2026-02-15T01:32:16Z]',
 'A part-time job and DJ gigs helped Lara Hamilton reach the Winter Olympics. Now she wants to put Australia on the map [2026-02-17T14:00:15Z]',
 'Valentino Guseli’s unexpected big air dream ends without a medal in all-or-nothing final: ‘I left it all out there’ [2026-02-08T00:27:13Z]',
 'From Bradbury to Bright: five of Australia’s best Winter Olympic moments | Martin Pegan [2026-02-03T14:00:08Z]',
 'Australia’s youngest Winter Olympian Indra Brown: ‘I just love the feeling of flying’ | Martin Pegan [2026-02-01T14:00:34Z]',
 'How did Australia – better known for its beaches than snow – become a consistent Winter Olympics performer? | Kieran Pender [2026-02-17T01:14:10Z]',
 '‘Put the blinders on’: how Jakara Anthony can make Winter Olympics history [2026-02-10T02:32:34Z]',
 'Ice in his veins: Australian skier Cooper Woods embraces pressure to realise Winter Olympic dream [2026-02-13T02:17:26Z]',
 'Australia’s Jakara Anthony clinches first ever dual moguls Olympics gold [2026-02-14T11:40:32Z]',
 'Morning Mail: Lake Cargelligo suspect’s past revealed, supermarket ‘per unit’ prices under scrutiny, shark attack spike [2026-02-18T20:23:22Z]',
 'Morning Mail: Taylor sets up Liberal spill, millionaires call for higher taxes, Australia’s skiing hope slips up [2026-02-11T19:40:12Z]']

By selecting a row from the dataframe and sorting the values (counts), we can identify the top 10 terms

In [17]:
# Sample 5 random article numbers
samples = random.sample(range(0,len(count_df)),5)
samples

[2, 9, 5, 0, 7]

In [18]:
# View the associated terms
for sample in samples:
    doc = count_df.iloc[sample]
    title = titles[sample]
    top_terms = dict(count_df.iloc[sample].sort_values(ascending=False).head(10))
    print(f"[{sample}] {title}")
    print("\t- Top terms:",top_terms)
    print()

[2] ‘Even more special’: Jakara Anthony dusts off Winter Olympics heartbreak for historic triumph [2026-02-15T01:32:16Z]
	- Top terms: {'moguls': np.int64(13), 'anthony': np.int64(11), 'dual': np.int64(6), 'single': np.int64(5), 'event': np.int64(5), 'just': np.int64(4), 'final': np.int64(4), 'time': np.int64(4), 'course': np.int64(4), 'lot': np.int64(3)}

[9] Ice in his veins: Australian skier Cooper Woods embraces pressure to realise Winter Olympic dream [2026-02-13T02:17:26Z]
	- Top terms: {'woods': np.int64(11), 'said': np.int64(7), 'just': np.int64(7), 'cooper': np.int64(5), 'lot': np.int64(5), 'final': np.int64(4), 'win': np.int64(4), 'time': np.int64(4), 'perisher': np.int64(3), 'people': np.int64(3)}

[5] From Bradbury to Bright: five of Australia’s best Winter Olympic moments | Martin Pegan [2026-02-03T14:00:08Z]
	- Top terms: {'bradbury': np.int64(6), 'event': np.int64(5), 'high': np.int64(4), 'bronze': np.int64(4), 'skiing': np.int64(4), 'way': np.int64(3), 'speed': np.int64(3), 'snowboard': np.int64(3), 'snow': np.int64(3), 'silver': np.int64(3)}

[0] Winter Olympics 2026: what you need to know if following from Australia [2026-02-02T14:00:10Z]
	- Top terms: {'2026': np.int64(6), 'ice': np.int64(6), 'new': np.int64(5), 'athletes': np.int64(5), 'aedt': np.int64(4), 'day': np.int64(4), 'ski': np.int64(4), 'watch': np.int64(4), 'skiing': np.int64(4), 'time': np.int64(4)}

[7] How did Australia – better known for its beaches than snow – become a consistent Winter Olympics performer? | Kieran Pender [2026-02-17T01:14:10Z]
	- Top terms: {'medals': np.int64(8), 'moguls': np.int64(7), 'sports': np.int64(6), 'team': np.int64(5), 'funding': np.int64(5), 'olympian': np.int64(5), 'success': np.int64(4), 'aerial': np.int64(4), 'snow': np.int64(4), 'skiing': np.int64(4)}

#### Create a top10 terms dataframe

Using the index from the documents, create a dataframe that can hold the top10 terms for each document. We also include columns for our other analysis (tfidf, lda, nmf)

In [19]:
# Create a dataframe to hold top terms for each analysis type
terms_df = pd.DataFrame(index=count_df.index,columns=['title','count','tfidf','lda','nmf'])
terms_df['title'] = titles
terms_df

                                                title count tfidf  lda  nmf
0   Winter Olympics 2026: what you need to know if...   NaN   NaN  NaN  NaN
1   Australia’s upward trajectory slips off course...   NaN   NaN  NaN  NaN
2   ‘Even more special’: Jakara Anthony dusts off ...   NaN   NaN  NaN  NaN
3   A part-time job and DJ gigs helped Lara Hamilt...   NaN   NaN  NaN  NaN
4   Valentino Guseli’s unexpected big air dream en...   NaN   NaN  NaN  NaN
5   From Bradbury to Bright: five of Australia’s b...   NaN   NaN  NaN  NaN
6   Australia’s youngest Winter Olympian Indra Bro...   NaN   NaN  NaN  NaN
7   How did Australia – better known for its beach...   NaN   NaN  NaN  NaN
8   ‘Put the blinders on’: how Jakara Anthony can ...   NaN   NaN  NaN  NaN
9   Ice in his veins: Australian skier Cooper Wood...   NaN   NaN  NaN  NaN
10  Australia’s Jakara Anthony clinches first ever...   NaN   NaN  NaN  NaN
11  Morning Mail: Lake Cargelligo suspect’s past r...   NaN   NaN  NaN  NaN
12  Morning Mail: Taylor sets up Liberal spill, mi...   NaN   NaN  NaN  NaN

Populate the count column with data created by the count vectorizer.

In [20]:
#For each doc, get the 10 columns with the largest counts
for idx in terms_df.index:
    counts = dict(count_df.loc[idx].sort_values(ascending=False).head(10))
    #print(counts)
    terms_df.at[idx,'count'] = list(counts.keys()) # Just the list of terms

terms_df

,title,count,tfidf,lda,nmf
0,Winter Olympics 2026: what you need to know if...,"[2026, ice, new, athletes, aedt, day, ski, wat...",NaN,NaN,NaN
1,Australia’s upward trajectory slips off course...,"[team, anthony, final, competition, medals, tr...",NaN,NaN,NaN
2,‘Even more special’: Jakara Anthony dusts off ...,"[moguls, anthony, dual, single, event, just, f...",NaN,NaN,NaN
3,A part-time job and DJ gigs helped Lara Hamilt...,"[hamilton, ski, skimo, just, running, says, sk...",NaN,NaN,NaN
4,Valentino Guseli’s unexpected big air dream en...,"[final, guseli, said, time, score, air, best, ...",NaN,NaN,NaN
5,From Bradbury to Bright: five of Australia’s b...,"[bradbury, event, high, bronze, skiing, way, s...",NaN,NaN,NaN
6,Australia’s youngest Winter Olympian Indra Bro...,"[just, indra, brown, time, says, want, halfpip...",NaN,NaN,NaN
7,How did Australia – better known for its beach...,"[medals, moguls, sports, team, funding, olympi...",NaN,NaN,NaN
8,‘Put the blinders on’: how Jakara Anthony can ...,"[anthony, moguls, says, ski, win, field, seaso...",NaN,NaN,NaN
9,Ice in his veins: Australian skier Cooper Wood...,"[woods, said, just, cooper, lot, final, win, t...",NaN,NaN,NaN
10,Australia’s Jakara Anthony clinches first ever...,"[anthony, second, moguls, james, halfpipe, tra...",NaN,NaN,NaN
11,Morning Mail: Lake Cargelligo suspect’s past r...,"[morning, history, including, new, government,...",NaN,NaN,NaN
12,"Morning Mail: Taylor sets up Liberal spill, mi...","[morning, smith, shock, australians, today, ab...",NaN,NaN,NaN

We should take a look at how some of the terms match up with the titles

In [21]:
# Sample 5 random articles
samples = random.sample(range(0,len(terms_df)),5)

for sample in samples:
    doc = terms_df.iloc[sample]
    print(f"[{sample}] {doc['title']}")
    print("\t>> Counts:\t",doc['count'])
    print()

[12] Morning Mail: Taylor sets up Liberal spill, millionaires call for higher taxes, Australia’s skiing hope slips up [2026-02-11T19:40:12Z]
	>> Counts:	 ['morning', 'smith', 'shock', 'australians', 'today', 'able', 'sydney', 'set', 'action', 'week']

[6] Australia’s youngest Winter Olympian Indra Brown: ‘I just love the feeling of flying’ | Martin Pegan [2026-02-01T14:00:34Z]
	>> Counts:	 ['just', 'indra', 'brown', 'time', 'says', 'want', 'halfpipe', 've', 'family', 'ski']

[4] Valentino Guseli’s unexpected big air dream ends without a medal in all-or-nothing final: ‘I left it all out there’ [2026-02-08T00:27:13Z]
	>> Counts:	 ['final', 'guseli', 'said', 'time', 'score', 'air', 'best', 'big', 'run', 'round']

[5] From Bradbury to Bright: five of Australia’s best Winter Olympic moments | Martin Pegan [2026-02-03T14:00:08Z]
	>> Counts:	 ['bradbury', 'event', 'high', 'bronze', 'skiing', 'way', 'speed', 'snowboard', 'snow', 'silver']

[8] ‘Put the blinders on’: how Jakara Anthony can make Winter Olympics history [2026-02-10T02:32:34Z]
	>> Counts:	 ['anthony', 'moguls', 'says', 'ski', 'win', 'field', 'season', 'woman', 'skiers', 'skier']

### Term Frequency / Inverse Document Frequency (TF/IDF)

**Finding terms that are very common in a document, but less common in the whole collection**

The [TF/IDF](https://en.wikipedia.org/wiki/Tf–idf) algorithm takes the term frequencies for a document and divides them by the frequencies of the terms in the whole collection.

In [22]:
# Only count terms that in maximum of 80% of documents, and a minimum of 2 documents. 
# Count a maximum of 10000 terms, and remove common english stop words
tfidf_vectorizer = TfidfVectorizer(
    max_df=0.8, min_df=2, max_features=10000, stop_words="english"
)

In [23]:
# Get the document vectors
tfidf_dt_matrix = tfidf_vectorizer.fit_transform(articles.values())

# Display the vector for the first document
tfidf_dt_matrix.toarray()[0]

array([0.05782947, 0.05782947, 0.        , 0.13860385, 0.07100469,
       0.03854199, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.05782947, 0.        , 0.10650704, 0.        ,
       0.        , 0.19692714, 0.        , 0.        , 0.10256164,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.05782947, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.2313179 , 0.        , 0.        , 0.        ,
       0.        , 0.042051  , 0.09240257, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.04620128, 0.05782947,
       0.05782947, 0.        , 0.        , 0.        , 0.03282119,
       0.        , 0.        , 0.        , 0.05782947, 0.        ,
       0.03854199, 0.17751174, 0.        , 0.05782947, 0.        ,
       0.042051  , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.04620128, 0.07100469, 0.        ,
       0.03282119, 0.        , 0.        , 0.03854199, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.05782947, 0.        ,
       0.        , 0.        , 0.08410201, 0.        , 0.09240257,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.12615301,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.05782947,
       0.05128082, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.05782947, 0.        ,
       0.        , 0.05782947, 0.        , 0.05782947, 0.042051  ,
       0.04620128, 0.        , 0.        , 0.08410201, 0.03550235,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.05782947, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.06084563, 0.042051  , 0.        , 0.        ,
       0.05782947, 0.        , 0.        , 0.03550235, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.13128476, 0.042051  , 0.        , 0.        ,
       0.05782947, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.03854199,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.05782947, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.05128082, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.05128082, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.05782947, 0.02825322, 0.07100469, 0.        ,
       0.        , 0.05782947, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.04620128, 0.        ,
       0.        , 0.        , 0.13860385, 0.        , 0.04620128,
       0.        , 0.        , 0.        , 0.02825322, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.042051  , 0.        , 0.        , 0.04620128, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.05782947, 0.03282119,
       0.04620128, 0.        , 0.        , 0.        , 0.        ,
       0.05782947, 0.05782947, 0.        , 0.        , 0.        ,
       0.        , 0.03550235, 0.        , 0.        , 0.        ,
       0.        , 0.042051  , 0.        , 0.        , 0.        ,
       0.        , 0.05128082, 0.        , 0.10256164, 0.        ,
       0.09846357, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.05782947, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.04620128, 0.        , 0.05128082, 0.        , 0.        ,
       0.        , 0.        , 0.03282119, 0.03854199, 0.        ,
       0.05782947, 0.15384245, 0.        , 0.25230603, 0.        ,
       0.        , 0.        , 0.        , 0.05782947, 0.07100469,
       0.        , 0.09240257, 0.        , 0.        , 0.        ,
       0.05128082, 0.        , 0.        , 0.05782947, 0.        ,
       0.14200939, 0.        , 0.03282119, 0.07100469, 0.05128082,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.05782947, 0.        ,
       0.12169126, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.05782947, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.05128082, 0.03550235, 0.        , 0.        , 0.05782947,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.05782947, 0.05782947, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.05128082, 0.05782947, 0.        ,
       0.        , 0.        , 0.11565895, 0.06084563, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.07100469,
       0.        , 0.05782947, 0.        , 0.        , 0.        ,
       0.05128082, 0.05782947, 0.        , 0.        , 0.11565895,
       0.04620128, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.17348842, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.15211407, 0.04620128, 0.05128082, 0.        ,
       0.        , 0.11565895, 0.05782947, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.03854199, 0.05128082,
       0.09240257, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.05782947, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.05782947, 0.04620128,
       0.05782947, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.04620128, 0.        , 0.        ,
       0.        , 0.        , 0.05782947, 0.        , 0.        ,
       0.08410201, 0.        , 0.        , 0.        , 0.        ,
       0.03854199, 0.042051  , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.05650644,
       0.09240257, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.05650644, 0.05128082, 0.        , 0.        ,
       0.        , 0.        , 0.03854199, 0.        , 0.        ,
       0.        , 0.05128082, 0.        , 0.        , 0.        ,
       0.03550235, 0.        , 0.02825322, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.04620128,
       0.        , 0.        , 0.09846357, 0.        , 0.        ,
       0.        , 0.        , 0.12169126, 0.03282119, 0.        ,
       0.12169126, 0.        , 0.05782947, 0.05782947, 0.05128082,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.07100469, 0.        , 0.05782947, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.042051  , 0.06564238, 0.05128082, 0.        ,
       0.10256164, 0.        , 0.        , 0.        , 0.05128082,
       0.        , 0.        , 0.05782947, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.17348842, 0.        , 0.08475966, 0.        , 0.        ,
       0.        , 0.05782947, 0.05782947, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.11301288, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.05782947,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.05782947, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.20512327, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.07708398, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.03550235, 0.03042281, 0.        , 0.        , 0.        ,
       0.03042281, 0.        , 0.05128082, 0.05782947])

#### Display matrix in dataframe

In [24]:
tfidf_df = pd.DataFrame(tfidf_dt_matrix.toarray(), columns=tfidf_vectorizer.get_feature_names_out())
tfidf_df

,000,10,10th,12,15,16,17,1994,1998,20,...,woman,women,won,woods,work,worst,years,yellow,youngest,zealand
0,0.057829,0.057829,0.000000,0.138604,0.071005,0.038542,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.035502,0.030423,0.000000,0.000000,0.000000,0.030423,0.000000,0.051281,0.057829
1,0.171316,0.000000,0.000000,0.000000,0.000000,0.038059,0.000000,0.050639,0.000000,0.000000,...,0.000000,0.035058,0.090126,0.000000,0.057105,0.000000,0.000000,0.057105,0.000000,0.000000
2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.071324,0.000000,0.046409,0.000000,0.058089,0.061119,0.000000,0.000000,0.000000
3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.046877,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.024661,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,0.000000,0.000000,0.053532,0.042768,0.000000,0.035678,0.000000,0.000000,0.000000,0.047470,...,0.000000,0.032864,0.028162,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
5,0.000000,0.000000,0.000000,0.046800,0.035962,0.000000,0.000000,0.051945,0.058579,0.000000,...,0.058579,0.000000,0.000000,0.000000,0.000000,0.000000,0.092451,0.000000,0.000000,0.000000
6,0.000000,0.000000,0.000000,0.000000,0.058372,0.063369,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.029186,0.025010,0.000000,0.000000,0.000000,0.050020,0.000000,0.042157,0.047541
7,0.000000,0.000000,0.000000,0.043702,0.000000,0.072914,0.000000,0.048507,0.054701,0.000000,...,0.000000,0.000000,0.086331,0.087404,0.000000,0.000000,0.057554,0.000000,0.048507,0.000000
8,0.000000,0.000000,0.000000,0.000000,0.033186,0.072055,0.054057,0.000000,0.000000,0.143806,...,0.162171,0.033186,0.028438,0.000000,0.000000,0.000000,0.028438,0.000000,0.000000,0.000000
9,0.000000,0.000000,0.000000,0.000000,0.032916,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.471197,0.053617,0.000000,0.000000,0.000000,0.000000,0.000000
10,0.000000,0.000000,0.000000,0.000000,0.040470,0.000000,0.000000,0.000000,0.000000,0.058456,...,0.000000,0.000000,0.104038,0.052666,0.000000,0.000000,0.069359,0.065921,0.000000,0.000000
11,0.000000,0.063379,0.063379,0.000000,0.038909,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.077818,0.033342,0.000000,0.000000,0.000000,0.033342,0.000000,0.000000,0.000000
12,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.058838,0.030953,0.000000,0.000000,0.000000

#### Update the terms matrix

In [25]:
for idx in terms_df.index:
    tfidf = dict(tfidf_df.loc[idx].sort_values(ascending=False).head(10))
    #print(counts)
    terms_df.at[idx,'tfidf'] = list(tfidf.keys()) 

terms_df

,title,count,tfidf,lda,nmf
0,Winter Olympics 2026: what you need to know if...,"[2026, ice, new, athletes, aedt, day, ski, wat...","[ice, aedt, watch, 2026, athletes, table, moun...",NaN,NaN
1,Australia’s upward trajectory slips off course...,"[team, anthony, final, competition, medals, tr...","[anthony, team, competition, air, snowboarder,...",NaN,NaN
2,‘Even more special’: Jakara Anthony dusts off ...,"[moguls, anthony, dual, single, event, just, f...","[moguls, anthony, dual, single, course, event,...",NaN,NaN
3,A part-time job and DJ gigs helped Lara Hamilt...,"[hamilton, ski, skimo, just, running, says, sk...","[hamilton, skimo, running, ski, mountaineering...",NaN,NaN
4,Valentino Guseli’s unexpected big air dream en...,"[final, guseli, said, time, score, air, best, ...","[guseli, final, air, 50, landing, score, said,...",NaN,NaN
5,From Bradbury to Bright: five of Australia’s b...,"[bradbury, event, high, bronze, skiing, way, s...","[bradbury, smith, high, bronze, city, event, s...",NaN,NaN
6,Australia’s youngest Winter Olympian Indra Bro...,"[just, indra, brown, time, says, want, halfpip...","[indra, want, just, brown, says, ve, time, fam...",NaN,NaN
7,How did Australia – better known for its beach...,"[medals, moguls, sports, team, funding, olympi...","[medals, moguls, funding, aerial, sports, olym...",NaN,NaN
8,‘Put the blinders on’: how Jakara Anthony can ...,"[anthony, moguls, says, ski, win, field, seaso...","[anthony, says, moguls, field, makes, woman, s...",NaN,NaN
9,Ice in his veins: Australian skier Cooper Wood...,"[woods, said, just, cooper, lot, final, win, t...","[woods, cooper, said, just, lot, perisher, nsw...",NaN,NaN
10,Australia’s Jakara Anthony clinches first ever...,"[anthony, second, moguls, james, halfpipe, tra...","[anthony, ok, second, peel, james, moguls, sin...",NaN,NaN
11,Morning Mail: Lake Cargelligo suspect’s past r...,"[morning, history, including, new, government,...","[morning, children, government, history, peopl...",NaN,NaN
12,"Morning Mail: Taylor sets up Liberal spill, mi...","[morning, smith, shock, australians, today, ab...","[morning, shock, smith, today, australians, se...",NaN,NaN

#### Compare approaches

In [26]:
# Sample 5 random articles
samples = random.sample(range(0,len(terms_df)),5)

for sample in samples:
    doc = terms_df.iloc[sample]
    print(f"[{sample}] {doc['title']}")
    print("\t>> Counts:\t",doc['count'])
    print("\t>> TFIDF:\t",doc['tfidf'])
    print()

[11] Morning Mail: Lake Cargelligo suspect’s past revealed, supermarket ‘per unit’ prices under scrutiny, shark attack spike [2026-02-18T20:23:22Z]
	>> Counts:	 ['morning', 'history', 'including', 'new', 'government', 'people', 'day', 'children', 'crossword', 'asian']
	>> TFIDF:	 ['morning', 'children', 'government', 'history', 'people', 'update', 'reports', 'allegedly', 'uk', 'asian']

[5] From Bradbury to Bright: five of Australia’s best Winter Olympic moments | Martin Pegan [2026-02-03T14:00:08Z]
	>> Counts:	 ['bradbury', 'event', 'high', 'bronze', 'skiing', 'way', 'speed', 'snowboard', 'snow', 'silver']
	>> TFIDF:	 ['bradbury', 'smith', 'high', 'bronze', 'city', 'event', 'speed', 'nation', 'national', 'later']

[12] Morning Mail: Taylor sets up Liberal spill, millionaires call for higher taxes, Australia’s skiing hope slips up [2026-02-11T19:40:12Z]
	>> Counts:	 ['morning', 'smith', 'shock', 'australians', 'today', 'able', 'sydney', 'set', 'action', 'week']
	>> TFIDF:	 ['morning', 'shock', 'smith', 'today', 'australians', 'set', 'cabinet', 'shadow', 'update', 'queensland']

[6] Australia’s youngest Winter Olympian Indra Brown: ‘I just love the feeling of flying’ | Martin Pegan [2026-02-01T14:00:34Z]
	>> Counts:	 ['just', 'indra', 'brown', 'time', 'says', 'want', 'halfpipe', 've', 'family', 'ski']
	>> TFIDF:	 ['indra', 'want', 'just', 'brown', 'says', 've', 'time', 'family', 'trick', 'landing']

[7] How did Australia – better known for its beaches than snow – become a consistent Winter Olympics performer? | Kieran Pender [2026-02-17T01:14:10Z]
	>> Counts:	 ['medals', 'moguls', 'sports', 'team', 'funding', 'olympian', 'success', 'aerial', 'snow', 'skiing']
	>> TFIDF:	 ['medals', 'moguls', 'funding', 'aerial', 'sports', 'olympian', 'success', 'federal', 've', 'snow']