<div style="background:#E9FFF6; color:#440404; padding:8px; border-radius: 4px; text-align: center; font-weight: 500;">IFN619 - Data Analytics for Strategic Decision Makers</div>

# IFN619 :: B3-Semi/unstructured Analytics Tutorial Exercises (Part A)

For this tutorial, you will use the lecture notebooks as a guide, and:

1. Use the Guardian API to undertake your own search and obtain a json file of documents
2. Create a TF/IDF document-term matrix for your documents

In [1]:
# Import the necessary libraries
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
import pandas as pd
import json
import random

## 1. Accessing the data via The Guardian API

Make a copy of the lecture notebook file (Accessing the Guardian API), and modify it to perform your own search of the Guardian API. **NOTE:** you will need to obtain your own developer API key first and put it in a file in the appropriate folder.

A suggested topic is "Brisbane 2032 Olympics", or come up with another that is of interest to you and will return a fair amount of data.

Save your search results in a json file, then read in that data below...

In [2]:
# Load the data - articles from The Guardian
file_path = "data/"
file_name = "brisbane_olympics_articles.json"

with open(f"{file_path}{file_name}",'r', encoding='utf-8') as fp:
    articles = json.load(fp)

print(f"Loaded {len(articles)} articles from {file_name}")

Loaded 126 articles from brisbane_olympics_articles.json

#### Discussion
Let's have a quick look what articles we have collected.

In [3]:
# An overview of article titles
for title in articles.keys():
    print(title)

Believe, belong, become, boring, bizarre: Brisbane Olympics motto panned as ‘lazy and weirdly evangelical’ [2025-12-04T06:05:28Z]
‘A big call for the IOC’: is the fight over Olympic rowing on Australia’s predator-inhabited Fitzroy River all a croc?  [2026-02-14T19:00:01Z]
Behind the scenes of Brisbane’s 2032 Olympics, a 19th-century story of politics and gay love [2026-01-02T14:00:13Z]
Queensland to repeal diversity quotas for Brisbane Olympics board [2025-06-19T14:43:14Z]
North Melbourne beat Brisbane: AFLW 2025 grand final – as it happened [2025-11-29T11:18:30Z]
First Nations group launches federal appeal to block construction of main Brisbane 2032 Olympics stadium [2025-08-05T03:39:12Z]
AOC appoints Mark Arbib as CEO for run-in to 2032 Brisbane Olympic Games [2025-04-01T23:52:32Z]
‘We’re seen as the underdogs’: the Australian skiers out on their own chasing an Olympic dream | Kieran Pender [2026-01-04T14:00:11Z]
‘Lovely gentle dinosaurs’: Brisbane 2032 Olympic rowing may be held in saltwater crocodile habitat [2025-03-25T08:31:39Z]
Federal government throws support behind LNP’s controversial new Olympic Games venue at Brisbane’s Victoria Park [2025-07-03T07:13:33Z]
AFL grand final 2025: ultimate guide to the flag decider between Geelong and Brisbane [2025-09-22T06:21:41Z]
‘Uneasy alliance’: why Brisbane’s Olympics has a former LNP premier and Greens radical fighting on the same side [2025-10-11T23:00:36Z]
NRLW 2025 grand final: Brisbane Broncos beat Sydney Roosters – as it happened [2025-10-05T07:15:36Z]
LNP denies decision has been made on Brisbane Olympic venues – as it happened [2025-01-23T06:55:26Z]
How did Australia – better known for its beaches than snow – become a consistent Winter Olympics performer? | Kieran Pender [2026-02-17T01:14:10Z]
Can crocodiles and canoeists coexist at Australia’s 2032 Olympic Games? [2025-08-16T20:00:13Z]
Brisbane Olympics 2032: David Crisafulli breaks election promise and announces controversial new stadium [2025-03-25T02:26:54Z]
How the architect who made modern Brisbane shaped the city’s 2032 Olympics stadium plans [2025-03-30T14:00:23Z]
Brisbane Olympics infrastructure body urges LNP to fast-track controversial venues with special laws [2025-03-26T14:00:02Z]
Brisbane Olympics 2032: why these Games could turn out nothing like we had planned [2025-03-24T14:01:00Z]
Brisbane to be transformed by ‘explosion of extraordinary colour’ in citywide art takeover [2025-06-10T20:00:08Z]
More than 60 prominent sportspeople call for federal royal commission after Bondi attack [2026-01-04T02:02:34Z]
Brisbane Broncos break 19-year NRL premiership drought in thriller against Melbourne Storm [2025-10-05T10:56:36Z]
Thousands without power in Queensland as Victoria experiences ‘terrifying’ winds after year’s wettest day [2025-10-27T03:50:16Z]
AFL grand final 2025: Brisbane Lions crush Geelong Cats to win back-to-back premierships – as it happened [2025-09-27T08:01:25Z]
Unruffled, unstoppable: Gout Gout’s sparkling rise continues with 100m U20 title in Brisbane [2025-03-15T05:59:35Z]
Track and feud: Queensland to announce third 2032 Olympic stadium plan in four years. Will this one stick? [2025-03-23T14:00:25Z]
Afternoon Update: Olympic stadium election promise broken; outrage after White House blunder; and volunteering in a Paris bar [2025-03-25T05:48:57Z]
Gout Gout ‘can be one of the best’, says Olympic champion Letsile Tebogo [2025-03-26T02:35:37Z]
Queensland moves to crack down on windfarms and exempt Olympic venues from planning laws [2025-05-01T07:58:57Z]
Innovation in the sunshine state: what’s behind Brisbane’s economic boom? [2025-05-02T03:46:26Z]
The ‘hot mess’ Olympics? How Queensland’s 2032 Games planning descended into farce [2025-03-25T14:00:50Z]
Queensland plans to build 2032 Olympics stadium on significant Indigenous site [2025-03-24T23:17:11Z]
Money or the starter’s gun? AFL and NRL riches remain a lure for Olympic hopefuls | Nicole Jeffery [2025-01-09T14:00:30Z]
Wallabies to learn Rugby World Cup fate at draw that favours 2027 hosts [2025-12-01T14:00:12Z]
Brisbane bus drivers push back strike action – as it happened [2025-02-24T06:44:23Z]
Morning Mail: US report mulls not delivering Aukus subs, Australian war graves bulldozed in Gaza, ICE agents retreat [2026-02-04T19:46:48Z]
Morning Mail: US shoots down Iranian drone, Mandelson investigated over Epstein scandal, interest rates rise pain [2026-02-03T20:13:24Z]
Morning Mail: ‘sense of doom’ for NDIS families, Gout Gout out of Commonwealth Games, Coalition back but can Ley survive? [2026-02-08T19:41:08Z]
Gout Gout fanfare obscures depth of Australian athletics poised for world championships spotlight | Jack Snape [2025-09-12T15:00:46Z]
High and dry: the suburbs of Sydney, Melbourne and Brisbane where it’s hard to find a pool [2025-01-03T14:00:25Z]
Cate Campbell: ‘I think people who have no regrets in life haven’t lived exciting enough lives’ [2025-04-04T14:01:02Z]
Queensland Productivity Commission argues construction industry ‘reset’ needed to fix housing crisis and deliver Olympics [2025-07-31T03:47:55Z]
Morning Mail: Trump’s two-week window for Iran attack, Olympics ditch diversity, the five ways we’ve changed [2025-06-19T20:58:58Z]
Australia’s diminished world championships return fails to cloud athletics optimism | Jack Snape [2025-09-22T02:08:57Z]
‘King’ Kyle Chalmers out to reassert dominance over princeling upstarts at swimming worlds | Kieran Pender [2025-07-31T02:45:36Z]
Angus Taylor will challenge for the Liberal leadership – but who will be the deputy? [2026-02-12T06:55:54Z]
Noah Lyles: ‘The future of sprinting is hazy right now. Nobody knows which direction to go in’ | Jack Snape [2025-09-22T07:13:35Z]
Robert Forster: ‘You improve as a person as you get older. I think that’s a fact’ [2025-05-23T15:00:34Z]
Australia targets offshore wagering threat with major sporting events on horizon [2025-10-13T14:00:06Z]
A year on as Queensland premier, will David Crisafulli’s small-target strategy prove his undoing? [2025-10-25T19:00:42Z]
Australia pipped by US at world swimming titles but Dolphins’ golden era endures | Kieran Pender [2025-08-04T02:40:51Z]
‘I’m chilling’: Gout Gout passes first test as he qualifies for world 200m semi-finals [2025-09-17T12:26:13Z]
Sydney to host 2027 Rugby World Cup final as Melbourne settles for last-16 games [2025-01-30T02:16:02Z]
Gout Gout’s winds of change whip Australian athletics into frenzy [2025-04-13T15:55:56Z]
Queensland state budget 2025: LNP to boost spending and hire more frontline staff as debt projected to top $200bn [2025-06-24T04:00:33Z]
Morning Mail: Secret childcare ratings leave NSW parents in dark, Albanese poised for climate action, Sam Kerr scores on Chelsea return [2025-09-14T20:55:25Z]
Blues get bullied by Kangaroos in horror show for Michael Voss | Andrew Stafford [2025-06-22T15:00:43Z]
Gout Gout frenzy drives huge Australian interest in World Athletics Championships [2025-09-08T15:00:48Z]
Morning Mail: Albanese calls Whitlam dismissal ‘calculated plot’, Trump threatens to sue BBC for US$1bn, plan for more Melbourne trains [2025-11-10T19:53:21Z]
Morning Mail: Lidia Thorpe reveals complaint against Dorinda Cox, Victorian Liberals accused of hypocrisy, Putin ‘has to’ respond to drone attack [2025-06-04T20:54:47Z]
Morning Mail: Israel intercepts Gaza flotilla, the fight to repair gadgets designed to fail, Jane Goodall dies [2025-10-01T20:44:21Z]
After devastating BMX injury, Kai Sakakibara makes winning return as para cyclist | Kieran Pender [2025-04-02T14:00:05Z]
Matthew Denny: from a homemade discus circle in his country town to the brink of world records [2025-04-14T05:26:05Z]
World Cup buzz grows as steely Australia upstage Ilona Maher’s USA [2025-05-17T09:49:18Z]
Morning Mail: Trump clashes with ABC reporter, gambling lobby sponsors MP sports, Robert Redford dies at 89 [2025-09-16T20:58:44Z]
Australia’s pole vault queen Nina Kennedy: ‘I’m in full force to go to the world champs’ | Jack Snape [2025-08-31T15:00:35Z]
Gout Gout’s future races towards him as he introduces himself to the world | Jack Snape [2025-09-13T20:00:14Z]
Morning Mail: Adani’s ‘sustainable’ coal claim denounced, NSW religious school boom, tsunami fears subside [2025-07-30T20:55:40Z]
Afternoon Update: ALP’s social media backfire; Queensland signs education deal; and kindness at the airport baggage carousel [2025-03-24T05:41:12Z]
Football fans invading Bondi beach? Hosting the Club World Cup would do wonders for the game in Australia | Paul Williams [2025-06-27T15:00:01Z]
Rugby World Cup 2027 draw: Australia and New Zealand drawn in Pool A – as it happened [2025-12-03T10:30:17Z]
Australian sprinter Lachie Kennedy: ‘There’s rarely any beef. It’s all pretty light and pretty fun’ [2025-03-20T14:00:27Z]
Queensland police rejects diversity targets including ‘critical’ proposal to hold senior officers accountable [2025-03-25T23:28:16Z]
‘Gout-mania’ expected in Perth but rival Kennedy could miss finale [2025-04-12T20:00:57Z]
Man arrested over alleged antisemitic speech at protest in Sydney – As it happened [2026-01-26T07:20:45Z]
Queensland court bans pro-Palestine bridge rally; Chalmers reveals list of 10 priorities from the economic roundtable – as it happened [2025-08-21T08:36:51Z]
Steph Gilmore: ‘I was looking for something more, in myself and in my surfing’ | Kieran Pender [2025-05-07T15:00:51Z]
Southern Ocean winds to break stifling heatwave baking Australia’s south-east [2025-01-05T03:11:24Z]
Morning Mail: Trump confronts South African president, NSW floods warning, Spurs claim Europa trophy [2025-05-21T21:06:08Z]
How Dyson Daniels’ home town became an unlikely hotbed of Australian basketball talent | Jack Snape [2025-02-22T23:00:19Z]
Australia v England: Ashes second Test, day two – as it happened [2025-12-05T12:12:01Z]
‘It’s the best game ever invented’: is padel the new pickleball? [2025-05-24T20:00:10Z]
‘Perth is primed for fast times’: Australian athletics’ Generation Next set to light up nationals | Jack Snape [2025-04-09T15:00:05Z]
Police investigate illegal riding on Sydney Harbour Bridge – as it happened [2026-02-04T06:59:35Z]
Morning Mail: Sabsabi’s Biennale ‘torture’, election candidates on Rednote, Trump tariff countdown [2025-04-01T20:24:23Z]
Crisafulli urges residents to prepare as storm approaches – as it happened [2025-03-05T07:49:57Z]
Morning Mail: Coalition won’t back tax cuts, Black Sea truce agreed, a Perth power play [2025-03-25T20:00:42Z]
Morning Mail: Chalmers upbeat on debt, White House war chat blunder, green hydrogen’s uncertain future [2025-03-24T20:02:58Z]
Morning Mail: Australia’s Signal concern, supermarket prices compared, Dutton to reveal cost-of-living policy [2025-03-26T20:00:54Z]
Australian Open draw: Emma Raducanu on early collision course with Swiatek [2025-01-09T06:52:14Z]
Queensland government blames police for overstated figures on drop in crime – as it happened [2025-10-15T07:13:42Z]
‘Anyone can pickleball’: boom sport a hit over rugby ahead of Australian Open debut | Jack Snape [2025-01-09T01:00:16Z]
Australian high-speed rail has barely left the station – some experts say a new US project shows a better way [2025-06-01T15:00:17Z]
Morning Mail: Trump targets migrants on first full day, shock at antisemitic Sydney attack, Djokovic’s masterclass [2025-01-21T19:59:33Z]
Trump tariff announcement wipes $1bn from CSL value – as it happened [2025-09-26T07:41:27Z]
PM says Liberals will ‘despair’ at Ley’s premature exit – as it happened [2026-02-15T05:09:04Z]
Coalition pledges $10m for western Queensland weather radar – as it happened [2025-03-31T06:41:10Z]
Ley, Waters and Pocock condemn government’s emissions call – as it happened [2025-09-18T08:13:02Z]
Dodson says Indigenous deaths in custody ‘a national disgrace’ – as it happened [2025-12-11T07:21:03Z]
Police clash with protesters as thousands rally to oppose Israeli president’s visit – as it happened [2026-02-09T10:37:36Z]
Police investigating alleged online threats to third Sydney mosque – as it happened [2025-03-21T06:51:08Z]
Failed Liberal candidate for Kooyong to make tilt for state seat – as it happened [2025-10-17T06:13:06Z]
Labor approves 4.41% increase for health insurance premiums – as it happened [2026-02-17T07:08:17Z]
Dutton says Australians ‘shouldn’t be afraid’ to celebrate Australia Day – As it happened [2025-01-26T07:22:48Z]
Michele Bullock says ‘nothing I can do personally’ about house prices – as it happened [2025-09-30T08:39:23Z]
Labor announces new anti-bullying initiative for schools – as it happened [2025-02-16T04:30:10Z]
Albanese says RBA rate cut ‘won’t have an impact’ on timing of federal election – as it happened [2025-02-18T07:15:35Z]
Governor grants Rockliff’s request for early election – as it happened [2025-06-11T09:11:16Z]
Coalition plans to have two nuclear power plants operating by mid-2030s – as it happened [2025-05-01T07:56:06Z]
Murderer granted parole – as it happened [2025-08-05T08:01:05Z]
Second man charged over attempted arson of Sydney synagogue – as it happened [2025-01-24T06:28:42Z]
Littleproud says discussions about reuniting Coalition a ‘positive move’ – as it happened [2025-05-22T08:13:05Z]
Barnaby Joyce vows to wind back ‘lunatic crusade’ of net zero with private member’s bill – as it happened [2025-07-11T08:30:19Z]
Zionist Federation of Australia urges Israel to ensure flow of aid – as it happened [2025-07-30T08:51:43Z]
NSW police to investigate handling of domestic violence allegations against accused Lake Cargelligo shooter – as it happened [2026-02-02T07:26:38Z]
Australia news live: PM says his government ‘support the status quo’ for Taiwan – as it happened [2025-07-13T05:29:08Z]
Black Saturday-affected towns told to leave before predicted wind change causes ‘dangerous’ fire conditions – as it happened [2026-01-09T07:10:55Z]
Housing completions fall behind accord target – as it happened [2025-01-22T06:56:08Z]
Major delays for Sydney trains amid urgent repairs; human remains found at Sydney home – as it happened [2025-03-14T06:27:21Z]
Australian navy ship accidentally blocks wifi across parts of New Zealand – as it happened [2025-06-06T07:14:53Z]
Education minister intervenes to address crisis unfolding at ANU – as it happened [2025-06-20T07:31:32Z]
Jason Clare says growing number of public school students not finishing year 12 ‘a big challenge’ – as it happened [2025-03-24T06:15:16Z]
Government condemns planned anti-immigration rallies; Taylor defends focus on Marles-Hegseth meeting – as it happened [2025-08-28T07:42:32Z]
Australian Open 2025: Draper beats Vukic in another five-set thriller – as it happened [2025-01-17T14:21:12Z]
Death in custody investigated – as it happened [2025-05-27T07:49:26Z]

Did all the retrieved articles relevant to the topic? If not, what are the strategies we might use to filter articles that are relevant to our topic? 
- ???
- ???
- ???

In [4]:
# Implement some of your strategies - add more cells if needed

# e.g., refine search terms and apply appropriate filters when building a search URL
# DIY 

# e.g., remove articles contains 'as it happened' - why?
## get a list of article titles 
titles = list(articles.keys())
## create an empty list to store filtered titles
filtered_titles = []

for title in titles:
    if "as it happens" not in title:
        filtered_titles.append(title)
        
# e.g., include titles that contain 'Brisbane' and 'Olympic' - why?
filtered_titles_2 = [title for title in filtered_titles if 'Brisbane' in title and 'Olympic' in title]

filtered_titles_2

['Believe, belong, become, boring, bizarre: Brisbane Olympics motto panned as ‘lazy and weirdly evangelical’ [2025-12-04T06:05:28Z]',
 'Behind the scenes of Brisbane’s 2032 Olympics, a 19th-century story of politics and gay love [2026-01-02T14:00:13Z]',
 'Queensland to repeal diversity quotas for Brisbane Olympics board [2025-06-19T14:43:14Z]',
 'First Nations group launches federal appeal to block construction of main Brisbane 2032 Olympics stadium [2025-08-05T03:39:12Z]',
 'AOC appoints Mark Arbib as CEO for run-in to 2032 Brisbane Olympic Games [2025-04-01T23:52:32Z]',
 '‘Lovely gentle dinosaurs’: Brisbane 2032 Olympic rowing may be held in saltwater crocodile habitat [2025-03-25T08:31:39Z]',
 'Federal government throws support behind LNP’s controversial new Olympic Games venue at Brisbane’s Victoria Park [2025-07-03T07:13:33Z]',
 '‘Uneasy alliance’: why Brisbane’s Olympics has a former LNP premier and Greens radical fighting on the same side [2025-10-11T23:00:36Z]',
 'LNP denies decision has been made on Brisbane Olympic venues – as it happened [2025-01-23T06:55:26Z]',
 'Brisbane Olympics 2032: David Crisafulli breaks election promise and announces controversial new stadium [2025-03-25T02:26:54Z]',
 'How the architect who made modern Brisbane shaped the city’s 2032 Olympics stadium plans [2025-03-30T14:00:23Z]',
 'Brisbane Olympics infrastructure body urges LNP to fast-track controversial venues with special laws [2025-03-26T14:00:02Z]',
 'Brisbane Olympics 2032: why these Games could turn out nothing like we had planned [2025-03-24T14:01:00Z]']

Since we have filtered out some articles, we need to update the JSON file to remove the articles that are no longer relevant. If we don't do this, the code below might try to access articles that don't exist anymore, which could cause errors.

In [5]:
# Filter the JSON data to only include these titles
# advanced
# articles_filtered = {title: content for title, content in articles.items() if title in filtered_titles_2}

# an easier way
## Initialise an empty dictionary
articles_filtered = {}
## Loop through the articles and add the ones that are in the DataFrame's index
for title, content in articles.items():
    if title in filtered_titles_2:
        articles_filtered[title] = content

articles_filtered

{'Believe, belong, become, boring, bizarre: Brisbane Olympics motto panned as ‘lazy and weirdly evangelical’ [2025-12-04T06:05:28Z]': 'If you typed the words “believe, belong and become” into a Google video search on Thursday morning, the first return may have been a sermon by TJ Mauldin, the lead pastor of the First Baptist church of Tifton, Georgia. Directly below the bearded and blue-jeaned pastor’s video under that alliterative banner, you may have clicked through to a sermon by West Florida Baptist church’s Mike Brown, who had those three b-words emblazoned on a snug-fitting black T-shirt. “These aren’t just words on a shirt,” the tanned, fit and immaculately groomed senior pastor proclaims. “This is the message and the heartbeat and the passion of God’s word – and it oughta be the message and the heartbeat and the passion of his church!”   Related: Can crocodiles and canoeists coexist at Australia’s 2032 Olympic Games?    From Lewis Center for Church Leadership Rev Dexter Udell Nutall’s Belong, Believe, Become: Engaging Millennials and Gen Z in Faith to Father George from St Anastasia Catholic church’s Introduction to the Three Bs (Belong, Believe, Become) – scrolling down the list on the world’s predominant search engine, every video return on those three combined words, in fact, may have led you to the impassioned word of God. Later in the day, however, after the alchemical undertaking of the algorithms, those same three words may have returned a very different top search result: Believe. Belong. Become. Brisbane 2032. “This is our time,” the Paralympic swimming and wheelchair basketball champion Ellie Cole says in the two-and-a-half-minute hype reel. “Our moment to believe.” “Belong,” the sprinter Patrick Johnson adds. “Become,” the Paralympian Madison de Rozario concludes. Sign up: AU Breaking News email For this is the “Games vision” of the Brisbane 2032 Olympic and Paralympic Games, revealed on Wednesday afternoon, after what organisers described as “the largest consultation process Brisbane 2032 has undertaken to date”. Led by communication consultancy Rowland, this three-word vision was formed after “more than 6,000 Australians had their say”, according to the press release. For the Brisbane 2032 president, Andrew Liveris – as it was for West Florida Baptist church’s Mike Brown – they were more than just words. “Our Games Vision has significant symbolism behind it, with the genesis of each word acting as our north star towards the delivery of our Games in 2032 and an exciting era beyond,” Liveris said. The advertising director Dee Madigan, however, reckons those words may have had a different origin story. A regular panellist on Gruen Planet – the ABC show that unpicks the world of advertising – Madigan says the Olympic slogan feels “strange and Christian schooley”. “I think they’ve stolen the school motto from pretty much every Christian school in the country!” she tells the Guardian. “Become? Become what?!? Become someone stuck in a traffic queue? Become someone who is paying an inordinate amount of money for a bottle of water?”   Related: ‘Uneasy alliance’: why Brisbane’s Olympics has a former LNP premier and Greens radical fighting on the same side    After an involvement in Labor campaigns, including leading its advertising for the successful 2022 and 2025 federal efforts, Madigan says she understands that coming up with a slogan “where you have got a plethora of stakeholders” is a difficult task. In 2008 the Standing Committee of the Political Bureau of the Chinese Communist Party Central Committee announced the motto of the Beijing 2008 Games as the slightly ominous One World, One Dream. Organisers of Paris 2024 seemed to be riffing of a Stanley Kubrick erotic thriller when they created the motto Games Wide Open, while those of South Korea’s 2018 Winter Olympics might have commissioned a wifi provider to dream up theirs: Passion. Connected. “By the time everyone puts their two bobs in, you’ve usually ended with 27,000 words – I understand how difficult that can be,” Madigan says. “But they have done a terrible job. It feels lazy and weirdly evangelistic.” Madigan says the slogan is a missed opportunity that could have been a promotional tool for visitors, or stoked a sense of pride. It could have been a play on Australian vernacular. It might have been humorous, spoken to the Aussie spirit of Queensland idiosyncrasy. “People are gonna come here and think we’re all holy baby Jesus people,” she says.     ',
 'Behind the scenes of Brisbane’s 2032 Olympics, a 19th-century story of politics and gay love [2026-01-02T14:00:13Z]': 'Today the story would be unremarkable: two gay men, migrants from England, give their Queensland home a portmanteau of their last names. But in 1859, these two men, Robert Herbert and John Bramston, were the new state’s first premier (then called colonial secretary) and one of his attorneys general.   The name, Herston, was later used to name the modern suburb that covers the area, and in less than seven years, the suburb in Brisbane’s north will host the main stadium for the 2032 Olympic Games. As the city takes the world stage, gay historians argue that the long-forgotten history of Herston should finally get the recognition it deserves. The Herston story is recounted in the 2001 gay history of Queensland, Sunshine and Rainbows: the Development of Gay and Lesbian Culture in Queensland. Its author, Clive Moore, says he was not the only one to conclude that Herbert was in a gay relationship.  Sign up for a weekly email featuring our best reads  Herbert and Bramston met at Balliol College, Oxford, in the 1850s, and shared rooms there and in London. Moore describes their lives as a “gay love story”, though it would have been impossible to admit such a thing publicly. Herbert never married and had no children. In an 1864 letter to his sister, Herbert explained that marriage would risk “being wretched”, for a chance “of a little possible additional happiness”. “It does not seem to me reasonable to tell a man who is happy and content, to marry a woman who may turn out a great disappointment,” the letter reads.    “There must be a lot of gay men today who have explained it that way to their sisters and mothers,” Moore says. Herbert held his position until February 1866 and returned to England shortly afterwards, where he lived until his death in 1905. Bramston also returned briefly to England, but was back in Queensland by 1868, and married Eliza Russell in Brisbane in 1872. He died in Wimbledon in 1921. Herbert’s government showed an unusual degree of sympathy for gay men. Queensland was the first state in the country to remove the death penalty for the offence of male sodomy. NSW did not do so for two decades.   Related: Queensland to abolish clause used to discriminate against LGBTQ+ people     Moore argues their relationship was doubly unlawful, doubly secret, because it was within cabinet. Even then that was against the rules, he says. The president of the Australian Queer Archives, Timothy Jones, says there were many people in influential positions throughout history thought to have been gay. “Learning this history is super exciting for queer people today,” he says. Jones is one of many in the gay community who believes their story should be told at the Olympics. There are 64 countries where homosexuality remains illegal, many of which participate in the Games. But he cautions against lionising individuals simply because they are now thought to have been gay. “We need to be careful about celebrating people in the past who lived closeted lives,” Jones says. “We only know a limited amount about them, and they are ambivalent figures in perpetrating injustices of colonialism. But I think it’s a good opportunity to point to the progress that’s been made and what still needs to happen.” The president of Brisbane Pride, James McCarthy, says the Olympics gives us “the opportunity to project the image of the confident and inclusive city that we all know Brisbane to be”. “It is essential that LGBTQIA+ communities and histories are front and centre in the telling of Brisbane’s story,” he says. When Moore moved to Queensland in the 1980s, his sexuality was unlawful. Gay school teachers were being threatened with the sack; Greg Weir, an openly gay trainee teacher was refused employment due to his sexuality. Homophobia in politics escalated at the end of the decade, part of a desperate attempt to distract from revelations of corruption in cabinet and the police, by the conservative government of Russell Cooper. He said a Labor government would bring a “flood of gays crossing the border from the Southern states”. There was even a proposal to extend the state’s laws to cover women for the first time.  In 1989, Queensland police laid some of Australia’s last charges under anti-gay laws. In 2017, the state government apologised and quashed a century and a half of recorded convictions. Queensland’s first openly gay MP, Trevor Evans, was elected in 2016, 157 years after Herbert took office.  The Herston home is long gone – it is now the site of the Royal Brisbane and women’s hospital. Herbert’s name lives on, but more prominently in far north Queensland, which boasts a Herbert river, a Herbert range, the town of Herberton and the federal electorate of Herbert. In 1975, the Queensland Place Names Board approved the official naming of the Brisbane suburb as Herston. But there are no heritage sites in the area to commemorate the name, nor are Bramston and Herbert’s full names recognised anywhere in the suburb. “It’s time Queensland faced up to a few things,” Moore says. “The gay community knows about [Herbert and Bramston], but basically the straight community in Brisbane doesn’t know about it. It’s never been aired in a public sort of a way.”',
 'Queensland to repeal diversity quotas for Brisbane Olympics board [2025-06-19T14:43:14Z]': 'The Queensland government plans to repeal a requirement that half the board overseeing the organising of the Brisbane Olympics be women and at least one member Aboriginal or Torres Strait Islander. The change to the Organising Committee for the Olympic Games (OCOG) board is contained in an obscure clause in broad-ranging legislation sponsored by the deputy premier, Jarrod Bleijie, in May. It is not mentioned in either its explanatory speech or explanatory notes. According to a written briefing by the Department of State Development, Infrastructure and Planning, made during consideration by a parliamentary committee, the bill would “enhance efficiency and effectiveness” by “removing certain requirements for the appointment of OCOG board directors”. That includes “that 50% of nominated directors be women” and “that at least one of the independent directors is Aboriginal or Torres Strait Islander”. The bill has yet to pass parliament but is certain to do so if all government members vote for it. Renee Carr, the executive director of Fair Agenda, said “women should be an equal part of making the critical decisions that shape its legacy”. “There’s been important progress in recognising women’s contribution to sport – as athletes, coaches, and in leadership. We should be leaning into what’s possible, not going backwards,” she said.   Related: Queensland moves to crack down on windfarms and exempt Olympic venues from planning laws    “Hosting an event of this scale will impact Queensland’s economy, infrastructure and tourism. Women’s voices and expertise must be an equal part of planning a games that delivers for the whole community.” The executive director of QUT’s Carumba Institute, Prof Chelsea Watego, said the plan to remove the requirement was an “appalling decision”. She said the Sydney Olympics was able to make decisions with a board that included an Indigenous representative, Lowitja O’Donoghue, so there was no case that excluding them would make it more efficient. “It just tells you how far backwards Queensland has gone under an LNP government,” she said.  Sign up for Guardian Australia’s breaking news email  Watego said that Brisbane, Queensland and Australia would be on the international stage. “We’re under a microscope and we have to think very seriously about what this tells the world about who we are as a nation, who we are as a state, and the location of Indigenous peoples and women in relation to that.” The minister for the Olympic and Paralympic Games, Tim Mander, said: “The Crisafulli government has accepted the recommendation of the independent 100-day review of the Games to streamline governance arrangements. “The act is currently before the state development, infrastructure and works committee.” The Planning (Social Impact and Community Benefit) and Other Legislation Amendment bill 2025 has a wide-ranging scope and more than 700 individuals and groups made a submission during a parliamentary inquiry process. Among other changes, the bill will reduce the size of the OCOG board from 24 to 15. It also amends regulation of renewables projects to make them easier for opponents to challenge in court and exempts Olympic venues from legal challenge.   Related: AOC appoints Mark Arbib as CEO for run-in to 2032 Brisbane Olympic Games    The OCOG board is appointed by multiple different agencies separate from the state government, such as the federal sports minister and the president of the Australian Olympic Committee. A legal provision will still apply requiring consideration of the state government’s policy on gender equity on boards. The policy sets a non-binding target for gender equity and does not cover Indigenous representation. The Brisbane Olympics will be held from 23 July to 8 August 2032, with the Paralympics running from 24 August to 5 September. Queensland has never held an Olympics but has hosted the Commonwealth Games, most recently in 2018. A binding provision that the 2032 games be “climate positive” has also been reportedly removed from the Olympic host contract. It will now aim “at removing more carbon from the atmosphere than what the Games project emits”.',
 'First Nations group launches federal appeal to block construction of main Brisbane 2032 Olympics stadium [2025-08-05T03:39:12Z]': 'A First Nations group has applied to halt construction of the main stadium planned for the 2032 Brisbane Olympics. \nThe state and federal governments plan to spend $3.8bn on a 63,000-seat stadium at Victoria Park in inner-city Brisbane. It will host the opening and closing ceremonies and athletics events. \nThe park will also contain a 25,000-seat national aquatic centre, a warmup track, and other infrastructure. \nVictoria Park is one of the most significant Indigenous sites in inner-city Brisbane, according to historian Ray Kerkhove. It served as the town camp for up to 1,500 Indigenous people, who were victims of at least one massacre, and is on a songline, he said earlier this year. It is also known as Barrambin. \nSign up: AU Breaking News email \nIn May Queensland parliament passed legislation on party lines exempting Games-related development from a number of state planning laws, including the Aboriginal Cultural Heritage Act, and from legal challenge. \n \n  Related: The ‘hot mess’ Olympics? How Queensland’s 2032 Games planning descended into farce  \n \nOn Tuesday, the Yagara Magandjin Aboriginal Corporation (Ymac) lodged an application with the federal government for permanent legal protection of the park, under section 10 of the Aboriginal and Torres Strait Islander Heritage Protection Act. The decision lies with the federal environment minister, Murray Watt. \n“We know this is a place of great significance and history, not only for Yagara people, but for other First Nations and non-Aboriginal people as well,” said Ymac spokesperson and Yagarabul elder Gaja Kerry Charlton. \nThe LNP leader, David Crisafulli, had promised not to build any new stadiums for the Olympics, and not to build one in Victoria Park, before last year’s state election. It was also not mentioned during the May federal election campaign. \nCrisafulli apologised for breaking the election promise in March, saying the choice was between Victoria Park and a temporary facility in the city’s south that wouldn’t have proven suitable. \n  \n  \n   \n  \n  \n \nUsed as a golf course since 1931, Brisbane city council developed a master plan for the site in 2020, converting it back into a park. Local elders participated in a four-year consultation process for the scheme. The plan has been scrapped. \nPart of the park is heritage listed and the relevant department recommended in April that the protection be expanded to cover the entire area. May’s legislation exempts Olympics development from the state Heritage Act. \n“It was a complete shock when the premier came out with his stadium plans,” Charlton said. \n“He said the park would be protected from stadiums; I thought the park was safe. Now the government wants to destroy it. We are very concerned there are ancient trees, artefacts and very important ecosystems existing there. There may be ancestral remains. \n“We stand resolute in our responsibility to protect it.” \n \n  Related: Queensland Productivity Commission argues construction industry ‘reset’ needed to fix housing crisis and deliver Olympics  \n \nThe federal government threw its support behind the Olympic stadium plan last month, on condition that appropriate consultation was undertaken with stakeholders including First Nations groups. \n Federal infrastructure minister, Catherine King, was contacted for comment. \nA spokesperson for the state government said its new laws “provide a bespoke process that recognises Aboriginal and Torres Strait Islander cultural heritage matters, incorporating engagement and consultation with relevant parties and preparation of a cultural heritage management plan”.  \n“Once Victoria Park is gone, it’s gone forever,” Yagara elder Uncle Steven said. \n“Will photos be our only memory? Are we going to have to say to our children, our grandchildren: ‘this is what your grandparents experienced, but it’s not here for you any more?’ \n“We have so little left of our history, our culture, our social life that we cling to it. And we want to share that with non-Aboriginal people as well.” \nWhen built, the Victoria Park stadium will be Queensland’s biggest stadium and will serve as the home of cricket and the Brisbane Lions AFL team. \n "> \n',

In [6]:
len(articles_filtered)

13

#### Create a top10 terms dataframe

Using the index from the documents, create a dataframe that can hold the top10 terms for each document.

In [7]:
# Create a dataframe to hold top terms for each analysis type
# We are going to use the article titles as index
terms_df = pd.DataFrame(index=articles_filtered.keys(),columns=['count','tfidf'])
terms_df

                                                   count tfidf
Believe, belong, become, boring, bizarre: Brisb...   NaN   NaN
Behind the scenes of Brisbane’s 2032 Olympics, ...   NaN   NaN
Queensland to repeal diversity quotas for Brisb...   NaN   NaN
First Nations group launches federal appeal to ...   NaN   NaN
AOC appoints Mark Arbib as CEO for run-in to 20...   NaN   NaN
‘Lovely gentle dinosaurs’: Brisbane 2032 Olympi...   NaN   NaN
Federal government throws support behind LNP’s ...   NaN   NaN
‘Uneasy alliance’: why Brisbane’s Olympics has ...   NaN   NaN
LNP denies decision has been made on Brisbane O...   NaN   NaN
Brisbane Olympics 2032: David Crisafulli breaks...   NaN   NaN
How the architect who made modern Brisbane shap...   NaN   NaN
Brisbane Olympics infrastructure body urges LNP...   NaN   NaN
Brisbane Olympics 2032: why these Games could t...   NaN   NaN

## 2. Term Count

In [8]:
# Set parameters appropriate to your data
count_vectorizer = CountVectorizer(max_df=0.80,min_df=2,max_features=10000,stop_words="english")
count_dt_matrix = count_vectorizer.fit_transform(articles_filtered.values())

In [9]:
# Get the terms identified during the vectorization process
feature_names = count_vectorizer.get_feature_names_out()
feature_names

array(['000', '10', '100', '11', '12', '15', '1980s', '1990s', '1bn',
       '20', '2001', '2012', '2016', '2017', '2018', '2019', '2020',
       '2021', '2024', '2025', '2026', '2027', '23', '25', '27', '30',
       '40', '4bn', '50', '5bn', '63', '785bn', '8bn', 'abc', 'able',
       'aboriginal', 'absolutely', 'accepted', 'access', 'according',
       'acknowledges', 'act', 'acting', 'action', 'active', 'actually',
       'additional', 'address', 'advance', 'advertising', 'affairs',
       'affected', 'afl', 'afternoon', 'age', 'agencies', 'agenda', 'ago',
       'agree', 'agreement', 'ahead', 'albanese', 'alliance', 'allow',
       'alongside', 'alternative', 'amid', 'amp', 'andrew', 'angeles',
       'announce', 'announced', 'announcement', 'anthony', 'anti', 'aoc',
       'apologised', 'appear', 'appointed', 'appropriate', 'approval',
       'approve', 'approved', 'april', 'aquatic', 'arbib', 'area',
       'areas', 'aren', 'arena', 'argue', 'argued', 'argues',
       'arrangements', 'ask', 'asked', 'asking', 'assessment',
       'associated', 'athletes', 'athletics', 'attacked', 'attacks',
       'attempt', 'au', 'august', 'australia', 'australian',
       'australians', 'authority', 'awarded', 'away', 'baby', 'barrambin',
       'barristers', 'basically', 'basis', 'bay', 'began', 'begin',
       'behaviour', 'belief', 'believe', 'best', 'better', 'bid', 'big',
       'bigger', 'biggest', 'billions', 'bit', 'black', 'bleijie', 'blue',
       'board', 'botanic', 'bowen', 'break', 'breaking', 'briefed',
       'bring', 'broad', 'broadcaster', 'brought', 'brown', 'budget',
       'build', 'building', 'built', 'bureau', 'business', 'buy',
       'called', 'came', 'camp', 'campaign', 'campbell', 'capacity',
       'capital', 'case', 'catherine', 'caught', 'caused', 'cbd',
       'celebrating', 'centenary', 'central', 'centre', 'ceo',
       'ceremonies', 'ceremony', 'certainly', 'chair', 'challenge',
       'challenges', 'champion', 'change', 'changes', 'charges', 'chief',
       'children', 'choice', 'choose', 'chosen', 'cities', 'city',
       'claims', 'clause', 'clear', 'climate', 'closely', 'closing',
       'club', 'coalition', 'college', 'colour', 'come', 'comes',
       'coming', 'comment', 'comments', 'commercial', 'commission',
       'commissioned', 'commit', 'commitment', 'committed', 'committee',
       'commonwealth', 'communication', 'communities', 'community',
       'compared', 'compete', 'competing', 'competition', 'complete',
       'completed', 'concerned', 'concrete', 'condition', 'conditions',
       'conference', 'confident', 'confirmed', 'conservative', 'consider',
       'consideration', 'construct', 'construction', 'consult',
       'consultation', 'contacted', 'contain', 'content', 'continue',
       'contract', 'controversial', 'conversation', 'converting',
       'coordination', 'corporation', 'corruption', 'cost', 'costs',
       'council', 'country', 'couple', 'course', 'court', 'cover',
       'crack', 'create', 'cricket', 'crisafulli', 'crisis', 'critical',
       'crocodile', 'crocodiles', 'cultural', 'culture', 'current',
       'currently', 'david', 'day', 'deal', 'death', 'decade', 'decades',
       'decided', 'decision', 'decisions', 'deliver', 'delivered',
       'delivering', 'delivers', 'delivery', 'democracy', 'demolition',
       'department', 'deputy', 'descended', 'described', 'describes',
       'describing', 'designed', 'develop', 'developed', 'development',
       'did', 'didn', 'died', 'different', 'difficult', 'dinosaurs',
       'direct', 'director', 'directors', 'dismissed', 'divided', 'does',
       'doesn', 'dog', 'doing', 'dollars', 'don', 'dream', 'eagle', 'ear',
       'earlier', 'early', 'easier', 'economy', 'efficient', 'efforts',
       'elders', 'elected', 'election', 'electorate', 'enable', 'end',
       'ended', 'engagement', 'england', 'ensure', 'entire',
       'environment', 'equal', 'equity', 'essential', 'estimated',
       'event', 'events', 'evidence', 'exciting', 'excluding',
       'executive', 'exempting', 'exempts', 'existing', 'expected',
       'expensive', 'experience', 'experts', 'extent', 'face', 'faced',
       'facilities', 'facility', 'fact', 'fair', 'faith', 'fan', 'far',
       'farce', 'farm', 'fear', 'fears', 'february', 'federal', 'feeling',
       'fight', 'fighting', 'figures', 'final', 'finally', 'financial',
       'firm', 'firmly', 'fix', 'flagged', 'focus', 'following',
       'forever', 'forgotten', 'form', 'formal', 'formally', 'formed',
       'forward', 'free', 'freely', 'friend', 'fund', 'funded', 'funding',
       'funnily', 'future', 'gabba', 'garden', 'gardens', 'gender',
       'general', 'gentle', 'george', 'global', 'globe', 'god', 'going',
       'golf', 'gone', 'good', 'got', 'governance', 'governments',
       'grass', 'great', 'greater', 'green', 'greens', 'ground', 'group',
       'groups', 'guardian', 'habitat', 'half', 'halt', 'hand', 'happen',
       'happy', 'harness', 'having', 'head', 'heart', 'held', 'help',
       'helping', 'heritage', 'high', 'highly', 'hill', 'hills',
       'historic', 'history', 'hold', 'holding', 'holds', 'home',
       'hospital', 'host', 'hosting', 'hot', 'hours', 'housing', 'human',
       'idea', 'image', 'imitation', 'impact', 'imperative', 'importance',
       'important', 'include', 'included', 'includes', 'including',
       'inclusive', 'increase', 'incredible', 'independent', 'indigenous',
       'individual', 'individuals', 'indoor', 'influence',
       'infrastructure', 'inner', 'inquiry', 'instead', 'institute',
       'international', 'investment', 'involved', 'involvement', 'ioc',
       'islander', 'isn', 'issue', 'issues', 'james', 'jarrod', 'job',
       'john', 'join', 'jones', 'july', 'just', 'key', 'kind', 'king',
       'know', 'knowing', 'known', 'la', 'labor', 'land', 'large',
       'largely', 'larger', 'largest', 'later', 'latest', 'launch',
       'laws', 'lead', 'leader', 'leaders', 'leadership', 'leading',
       'led', 'left', 'legacy', 'legal', 'legislation', 'letter',
       'levels', 'liberal', 'life', 'like', 'likely', 'lines', 'linking',
       'listed', 'little', 'live', 'lived', 'liveris', 'living', 'll',
       'lnp', 'local', 'london', 'long', 'look', 'looking', 'los', 'lost',
       'lot', 'love', 'lovely', 'main', 'major', 'make', 'makes',
       'making', 'male', 'man', 'management', 'mander', 'manner', 'march',
       'mark', 'market', 'marriage', 'massacre', 'master', 'match',
       'matters', 'mayor', 'mccarthy', 'mean', 'meaning', 'means',
       'media', 'meet', 'meeting', 'member', 'members', 'men',
       'mentioned', 'mess', 'message', 'messenger', 'met', 'metropolis',
       'minister', 'minutes', 'missed', 'modern', 'moment', 'monday',
       'money', 'month', 'months', 'morning', 'moved', 'movement',
       'multiple', 'murray', 'nation', 'national', 'nations', 'natural',
       'nearby', 'necessarily', 'necessary', 'need', 'needed', 'needs',
       'new', 'newman', 'news', 'night', 'nominated', 'non', 'normal',
       'north', 'nose', 'nsw', 'number', 'numbers', 'occur', 'ocean',
       'october', 'offence', 'office', 'official', 'officials', 'old',
       'open', 'opening', 'operations', 'opinion', 'opponents',
       'opportunities', 'opportunity', 'opposition', 'options',
       'organisers', 'organising', 'outcome', 'outside', 'overall',
       'packed', 'paralympic', 'paris', 'park', 'parkland', 'parliament',
       'parliamentary', 'participate', 'particularly', 'parties',
       'partner', 'partnership', 'parts', 'party', 'passed', 'passion',
       'past', 'paving', 'paying', 'people', 'period', 'person', 'place',
       'placed', 'plan', 'planned', 'planning', 'plans', 'play', 'played',
       'point', 'pointing', 'points', 'police', 'policy', 'political',
       'politically', 'politicians', 'politics', 'polls', 'pool',
       'position', 'positive', 'possible', 'power', 'powers', 'precinct',
       'preparations', 'prepared', 'presented', 'president', 'press',
       'pretty', 'prevent', 'pride', 'prime', 'private', 'probably',
       'problem', 'process', 'processes', 'procurement', 'progress',
       'project', 'projects', 'promise', 'promised', 'promises',
       'property', 'proposal', 'protect', 'protection', 'protest',
       'protesters', 'protests', 'provide', 'provided', 'providing',
       'public', 'publicly', 'push', 'pushing', 'puts', 'putting', 'qsac',
       'quarter', 'question', 'queue', 'quickly', 'quite', 'radical',
       'radio', 'range', 'reached', 'reaching', 'reads', 'real', 'really',
       'receive', 'received', 'recent', 'recently', 'recognise',
       'recognition', 'recommendation', 'recommended', 'records',
       'reduce', 'regardless', 'region', 'regional', 'relation',
       'released', 'remaining', 'remains', 'remarkable', 'remove',
       'removed', 'removing', 'renewables', 'repeatedly', 'replaced',
       'report', 'reported', 'reporters', 'reporting', 'reports',
       'require', 'required', 'requirements', 'residents', 'resolved',
       'respect', 'responsibility', 'responsible', 'result', 'results',
       'retired', 'return', 'returned', 'revealed', 'revelations',
       'review', 'right', 'risk', 'risks', 'river', 'road', 'role',
       'roll', 'roma', 'room', 'rowing', 'royal', 'rules', 'run',
       'running', 'runs', 'sack', 'safe', 'safely', 'saltwater', 'sarah',
       'save', 'saved', 'say', 'saying', 'says', 'school', 'scrapped',
       'search', 'seat', 'secretary', 'section', 'sector', 'seen',
       'seine', 'self', 'senator', 'sense', 'separate', 'september',
       'seriously', 'serve', 'served', 'set', 'sets', 'shape', 'share',
       'shared', 'shift', 'shirt', 'shortly', 'showed', 'showgrounds',
       'showing', 'shown', 'significance', 'significant', 'signs',
       'similar', 'simply', 'single', 'site', 'sites', 'sitting',
       'situation', 'size', 'slightly', 'small', 'smaller', 'snake',
       'social', 'sold', 'sort', 'south', 'southern', 'space', 'speaks',
       'special', 'speech', 'spend', 'spending', 'split', 'spoken',
       'spokesperson', 'sport', 'sporting', 'sports', 'spring', 'st',
       'stadium', 'stadiums', 'staff', 'stage', 'stakeholders', 'stand',
       'standard', 'standing', 'star', 'statement', 'states', 'steven',
       'stolen', 'stood', 'story', 'strait', 'strange', 'stream',
       'street', 'struck', 'stuff', 'substantial', 'successful',
       'successor', 'suggested', 'suitable', 'support', 'supported',
       'sure', 'surrounding', 'swimming', 'sydney', 'table', 'taken',
       'takes', 'taking', 'talent', 'talk', 'target', 'teachers', 'team',
       'tell', 'telling', 'tells', 'temporary', 'tennis', 'term', 'thing',
       'things', 'think', 'thinks', 'thought', 'thrown', 'thursday',
       'tight', 'tim', 'time', 'timeline', 'today', 'told', 'took',
       'tool', 'torres', 'town', 'track', 'trade', 'traffic', 'training',
       'transform', 'transport', 'trees', 'trying', 'tuesday', 'turn',
       'uncertainty', 'understand', 'understanding', 'understands',
       'undertaken', 'uneasy', 'unionist', 'unique', 'unlawful',
       'unlikely', 'upgraded', 'use', 'used', 'usually', 've', 'venue',
       'venues', 'victoria', 'video', 'village', 'vision', 'visitors',
       'vote', 'voters', 'vowed', 'walking', 'want', 'wanted', 'wants',
       'water', 'watt', 'way', 'wednesday', 'week', 'weekly', 'went',
       'west', 'whilst', 'white', 'wide', 'win', 'woman', 'women', 'won',
       'words', 'work', 'working', 'works', 'world', 'wouldn', 'writing',
       'written', 'year', 'years', 'yes'], dtype=object)

In [10]:
# Create a new dataframe with the matrix - use titles for the index and terms for the columns
count_df = pd.DataFrame(count_dt_matrix.toarray(), index = terms_df.index, columns=feature_names)
count_df

,000,10,100,11,12,15,1980s,1990s,1bn,20,...,work,working,works,world,wouldn,writing,written,year,years,yes
"Believe, belong, become, boring, bizarre: Brisbane Olympics motto panned as ‘lazy and weirdly evangelical’ [2025-12-04T06:05:28Z]",2,0,0,0,0,0,0,0,0,0,...,0,0,0,3,0,0,0,0,0,0
"Behind the scenes of Brisbane’s 2032 Olympics, a 19th-century story of politics and gay love [2026-01-02T14:00:13Z]",0,0,0,0,0,0,1,0,0,0,...,0,0,0,1,0,0,0,0,2,0
Queensland to repeal diversity quotas for Brisbane Olympics board [2025-06-19T14:43:14Z],0,0,1,0,0,1,0,0,0,0,...,0,0,1,1,0,0,1,0,0,0
First Nations group launches federal appeal to block construction of main Brisbane 2032 Olympics stadium [2025-08-05T03:39:12Z],2,1,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,3,0,0
AOC appoints Mark Arbib as CEO for run-in to 2032 Brisbane Olympic Games [2025-04-01T23:52:32Z],0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,1,2,0
‘Lovely gentle dinosaurs’: Brisbane 2032 Olympic rowing may be held in saltwater crocodile habitat [2025-03-25T08:31:39Z],1,0,0,0,0,2,1,1,0,0,...,0,1,0,5,1,0,0,1,3,0
Federal government throws support behind LNP’s controversial new Olympic Games venue at Brisbane’s Victoria Park [2025-07-03T07:13:33Z],2,0,0,0,0,0,0,0,1,0,...,1,0,1,0,0,0,0,2,0,0
‘Uneasy alliance’: why Brisbane’s Olympics has a former LNP premier and Greens radical fighting on the same side [2025-10-11T23:00:36Z],2,1,0,0,0,1,0,0,0,0,...,0,0,1,2,0,1,1,1,0,1
LNP denies decision has been made on Brisbane Olympic venues – as it happened [2025-01-23T06:55:26Z],6,21,1,18,11,2,0,0,0,4,...,17,7,1,9,1,1,0,16,14,1
Brisbane Olympics 2032: David Crisafulli breaks election promise and announces controversial new stadium [2025-03-25T02:26:54Z],5,0,0,0,2,0,0,0,2,1,...,1,0,0,2,0,0,0,2,1,0
How the architect who made modern Brisbane shaped the city’s 2032 Olympics stadium plans [2025-03-30T14:00:23Z],0,0,1,0,1,0,0,0,0,2,...,0,0,0,0,0,0,0,2,3,0
Brisbane Olympics infrastructure body urges LNP to fast-track controversial venues with special laws [2025-03-26T14:00:02Z],0,0,3,0,0,0,1,0,1,0,...,1,0,0,0,0,0,0,0,2,0
Brisbane Olympics 2032: why these Games could turn out nothing like we had planned [2025-03-24T14:01:00Z],0,0,1,1,0,0,1,0,0,0,...,0,0,0,2,0,0,0,1,3,0

In [11]:
#For each doc, get the 10 columns with the largest counts
for idx in terms_df.index:
    counts = dict(count_df.loc[idx].sort_values(ascending=False).head(10))
    #print(counts)
    terms_df.at[idx,'count'] = list(counts.keys()) # Just the list of terms

terms_df

,count,tfidf
"Believe, belong, become, boring, bizarre: Brisbane Olympics motto panned as ‘lazy and weirdly evangelical’ [2025-12-04T06:05:28Z]","[words, says, believe, search, passion, video,...",NaN
"Behind the scenes of Brisbane’s 2032 Olympics, a 19th-century story of politics and gay love [2026-01-02T14:00:13Z]","[says, story, people, history, men, today, com...",NaN
Queensland to repeal diversity quotas for Brisbane Olympics board [2025-06-19T14:43:14Z],"[board, women, committee, planning, indigenous...",NaN
First Nations group launches federal appeal to block construction of main Brisbane 2032 Olympics stadium [2025-08-05T03:39:12Z],"[park, aboriginal, stadium, heritage, victoria...",NaN
AOC appoints Mark Arbib as CEO for run-in to 2032 Brisbane Olympic Games [2025-04-01T23:52:32Z],"[arbib, aoc, sports, executive, athletes, comm...",NaN
‘Lovely gentle dinosaurs’: Brisbane 2032 Olympic rowing may be held in saltwater crocodile habitat [2025-03-25T08:31:39Z],"[crocodile, rowing, crocodiles, river, world, ...",NaN
Federal government throws support behind LNP’s controversial new Olympic Games venue at Brisbane’s Victoria Park [2025-07-03T07:13:33Z],"[new, park, site, victoria, bleijie, stadium, ...",NaN
‘Uneasy alliance’: why Brisbane’s Olympics has a former LNP premier and Greens radical fighting on the same side [2025-10-11T23:00:36Z],"[park, victoria, stadium, people, plan, save, ...",NaN
LNP denies decision has been made on Brisbane Olympic venues – as it happened [2025-01-23T06:55:26Z],"[police, people, australia, day, sydney, nsw, ...",NaN
Brisbane Olympics 2032: David Crisafulli breaks election promise and announces controversial new stadium [2025-03-25T02:26:54Z],"[new, stadium, centre, build, crisafulli, priv...",NaN
How the architect who made modern Brisbane shaped the city’s 2032 Olympics stadium plans [2025-03-30T14:00:23Z],"[park, city, says, victoria, venues, plans, st...",NaN
Brisbane Olympics infrastructure body urges LNP to fast-track controversial venues with special laws [2025-03-26T14:00:02Z],"[review, venues, time, infrastructure, procure...",NaN
Brisbane Olympics 2032: why these Games could turn out nothing like we had planned [2025-03-24T14:01:00Z],"[city, new, stadium, venues, host, public, ide...",NaN

## 3. Term Frequency / Inverse Document Frequency (TF/IDF)

In [12]:
# Set parameters appropriate to your data
tfidf_vectorizer = TfidfVectorizer(
    max_df=0.80, min_df=2, max_features=10000, stop_words="english"
)

In [13]:
# Get the document vectors
tfidf_dt_matrix = tfidf_vectorizer.fit_transform(articles_filtered.values())

# Display the vector for the first document
tfidf_dt_matrix.toarray()[0]

array([0.07189895, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.0585578 ,
       0.        , 0.        , 0.        , 0.04678316, 0.05192666,
       0.        , 0.        , 0.        , 0.        , 0.0585578 ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.05192666, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.04258061,
       0.        , 0.        , 0.05192666, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.17567339,
       0.        , 0.        , 0.        , 0.0585578 , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.0585578 , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.04258061, 0.        ,
       0.        , 0.03080597, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.05192666, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.05192666,
       0.        , 0.02860905, 0.0390274 , 0.05192666, 0.        ,
       0.        , 0.        , 0.0585578 , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.29278898, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.05192666, 0.        , 0.0585578 , 0.        ,
       0.        , 0.        , 0.        , 0.03080597, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.10385333,
       0.        , 0.        , 0.        , 0.        , 0.0585578 ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.04258061, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.0585578 , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.04258061, 0.        , 0.0585578 , 0.        ,
       0.        , 0.        , 0.        , 0.0585578 , 0.        ,
       0.        , 0.        , 0.07189895, 0.        , 0.0585578 ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.05192666, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.04258061, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.0585578 , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.0390274 ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.04258061, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.04678316, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.09356631, 0.10385333, 0.        ,
       0.        , 0.05192666, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.11711559, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.0585578 ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.0585578 , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.05192666,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.05192666,
       0.        , 0.0585578 , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.03323455,
       0.        , 0.        , 0.0585578 , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.0585578 , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.0585578 ,
       0.        , 0.        , 0.11711559, 0.        , 0.        ,
       0.        , 0.        , 0.05192666, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.05192666,
       0.        , 0.        , 0.        , 0.03323455, 0.        ,
       0.04258061, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.03594947, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.0585578 , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.0585578 , 0.        , 0.        , 0.        ,
       0.        , 0.0664691 , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.0390274 ,
       0.        , 0.        , 0.        , 0.        , 0.03594947,
       0.04258061, 0.        , 0.        , 0.        , 0.05192666,
       0.        , 0.        , 0.04678316, 0.0585578 , 0.10385333,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.10385333, 0.        , 0.        , 0.03594947,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.11711559, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.0585578 , 0.        , 0.0585578 ,
       0.        , 0.04258061, 0.        , 0.        , 0.0585578 ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.02860905, 0.        , 0.        , 0.        ,
       0.        , 0.04678316, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.0585578 ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.03594947, 0.        , 0.        , 0.11711559, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.0780548 ,
       0.05192666, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.04258061, 0.        , 0.17567339, 0.        ,
       0.        , 0.0585578 , 0.06161194, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.05192666, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.04678316, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.0390274 , 0.04678316,
       0.05192666, 0.        , 0.05192666, 0.        , 0.        ,
       0.        , 0.        , 0.03594947, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.0585578 , 0.        , 0.        , 0.        , 0.        ,
       0.0585578 , 0.        , 0.        , 0.0585578 , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.0585578 , 0.        ,
       0.        , 0.10385333, 0.05192666, 0.0585578 , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.0390274 , 0.        ,
       0.23416441, 0.10385333, 0.        , 0.17567339, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.05192666, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.11711559,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.03323455, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.0585578 , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.04678316, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.0585578 , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.0585578 , 0.        ,
       0.        , 0.        , 0.        , 0.05192666, 0.        ,
       0.        , 0.05192666, 0.05192666, 0.        , 0.        ,
       0.        , 0.0585578 , 0.        , 0.05192666, 0.        ,
       0.0585578 , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.04678316, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.0390274 ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.0585578 , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.07189895, 0.        ,
       0.        , 0.        , 0.05192666, 0.        , 0.        ,
       0.0572181 , 0.        , 0.        , 0.        , 0.        ,
       0.0585578 , 0.        , 0.        , 0.        , 0.        ,
       0.0585578 , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.0585578 ,
       0.        , 0.0585578 , 0.04678316, 0.0585578 , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.0585578 , 0.0780548 , 0.        , 0.        ,
       0.        , 0.17567339, 0.        , 0.15577999, 0.0585578 ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.05192666, 0.        , 0.        ,
       0.0585578 , 0.        , 0.        , 0.        , 0.11711559,
       0.        , 0.        , 0.05192666, 0.        , 0.        ,
       0.        , 0.        , 0.46846237, 0.        , 0.        ,
       0.        , 0.09970365, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        ])

#### Update the terms matrix

In [14]:
# list of feature names
feature_names = tfidf_vectorizer.get_feature_names_out()

# create a df to combine matrix with feature names
tfidf_df = pd.DataFrame(tfidf_dt_matrix.toarray(), index=articles_filtered.keys(), columns=feature_names)
tfidf_df

,000,10,100,11,12,15,1980s,1990s,1bn,20,...,work,working,works,world,wouldn,writing,written,year,years,yes
"Believe, belong, become, boring, bizarre: Brisbane Olympics motto panned as ‘lazy and weirdly evangelical’ [2025-12-04T06:05:28Z]",0.071899,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.099704,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
"Behind the scenes of Brisbane’s 2032 Olympics, a 19th-century story of politics and gay love [2026-01-02T14:00:13Z]",0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.047781,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.033944,0.000000,0.000000,0.000000,0.000000,0.067887,0.000000
Queensland to repeal diversity quotas for Brisbane Olympics board [2025-06-19T14:43:14Z],0.000000,0.000000,0.045773,0.000000,0.000000,0.050291,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.050291,0.035727,0.000000,0.000000,0.062949,0.000000,0.000000,0.000000
First Nations group launches federal appeal to block construction of main Brisbane 2032 Olympics stadium [2025-08-05T03:39:12Z],0.068617,0.049556,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.049556,0.000000,0.000000,0.088199,0.000000,0.000000
AOC appoints Mark Arbib as CEO for run-in to 2032 Brisbane Olympic Games [2025-04-01T23:52:32Z],0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.058108,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.030570,0.065959,0.000000
‘Lovely gentle dinosaurs’: Brisbane 2032 Olympic rowing may be held in saltwater crocodile habitat [2025-03-25T08:31:39Z],0.023403,0.000000,0.000000,0.000000,0.000000,0.060912,0.030456,0.038122,0.000000,0.000000,...,0.000000,0.038122,0.000000,0.108180,0.033805,0.000000,0.000000,0.020055,0.064908,0.000000
Federal government throws support behind LNP’s controversial new Olympic Games venue at Brisbane’s Victoria Park [2025-07-03T07:13:33Z],0.066247,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.047845,0.000000,...,0.043106,0.000000,0.043106,0.000000,0.000000,0.000000,0.000000,0.056769,0.000000,0.000000
‘Uneasy alliance’: why Brisbane’s Olympics has a former LNP premier and Greens radical fighting on the same side [2025-10-11T23:00:36Z],0.061066,0.044103,0.000000,0.000000,0.000000,0.039734,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.039734,0.056454,0.000000,0.049735,0.049735,0.026164,0.000000,0.049735
LNP denies decision has been made on Brisbane Olympic venues – as it happened [2025-01-23T06:55:26Z],0.022784,0.115186,0.004498,0.111339,0.060336,0.009883,0.000000,0.000000,0.000000,0.021940,...,0.084010,0.043299,0.004942,0.031595,0.005485,0.006186,0.000000,0.052065,0.049148,0.006186
Brisbane Olympics 2032: David Crisafulli breaks election promise and announces controversial new stadium [2025-03-25T02:26:54Z],0.140903,0.000000,0.000000,0.000000,0.081410,0.000000,0.000000,0.000000,0.081410,0.040705,...,0.036673,0.000000,0.000000,0.052105,0.000000,0.000000,0.000000,0.048297,0.026052,0.000000
How the architect who made modern Brisbane shaped the city’s 2032 Olympics stadium plans [2025-03-30T14:00:23Z],0.000000,0.000000,0.033080,0.000000,0.040341,0.000000,0.000000,0.000000,0.000000,0.080682,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.047865,0.077458,0.000000
Brisbane Olympics infrastructure body urges LNP to fast-track controversial venues with special laws [2025-03-26T14:00:02Z],0.000000,0.000000,0.112576,0.000000,0.000000,0.000000,0.041229,0.000000,0.045762,0.000000,...,0.041229,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.058578,0.000000
Brisbane Olympics 2032: why these Games could turn out nothing like we had planned [2025-03-24T14:01:00Z],0.000000,0.000000,0.035395,0.048676,0.000000,0.000000,0.038888,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.055252,0.000000,0.000000,0.000000,0.025607,0.082878,0.000000

In [15]:
for idx in terms_df.index:
    tfidf = dict(tfidf_df.loc[idx].sort_values(ascending=False).head(10))
    terms_df.at[idx,'tfidf'] = list(tfidf.keys()) 

terms_df

,count,tfidf
"Believe, belong, become, boring, bizarre: Brisbane Olympics motto panned as ‘lazy and weirdly evangelical’ [2025-12-04T06:05:28Z]","[words, says, believe, search, passion, video,...","[words, believe, says, advertising, passion, s..."
"Behind the scenes of Brisbane’s 2032 Olympics, a 19th-century story of politics and gay love [2026-01-02T14:00:13Z]","[says, story, people, history, men, today, com...","[says, story, men, history, jones, england, to..."
Queensland to repeal diversity quotas for Brisbane Olympics board [2025-06-19T14:43:14Z],"[board, women, committee, planning, indigenous...","[board, women, directors, committee, planning,..."
First Nations group launches federal appeal to block construction of main Brisbane 2032 Olympics stadium [2025-08-05T03:39:12Z],"[park, aboriginal, stadium, heritage, victoria...","[park, aboriginal, heritage, federal, victoria..."
AOC appoints Mark Arbib as CEO for run-in to 2032 Brisbane Olympic Games [2025-04-01T23:52:32Z],"[arbib, aoc, sports, executive, athletes, comm...","[arbib, aoc, sports, executive, experience, at..."
‘Lovely gentle dinosaurs’: Brisbane 2032 Olympic rowing may be held in saltwater crocodile habitat [2025-03-25T08:31:39Z],"[crocodile, rowing, crocodiles, river, world, ...","[crocodile, rowing, crocodiles, river, behavio..."
Federal government throws support behind LNP’s controversial new Olympic Games venue at Brisbane’s Victoria Park [2025-07-03T07:13:33Z],"[new, park, site, victoria, bleijie, stadium, ...","[bleijie, new, victoria, park, site, king, dea..."
‘Uneasy alliance’: why Brisbane’s Olympics has a former LNP premier and Greens radical fighting on the same side [2025-10-11T23:00:36Z],"[park, victoria, stadium, people, plan, save, ...","[park, victoria, stadium, save, people, newman..."
LNP denies decision has been made on Brisbane Olympic venues – as it happened [2025-01-23T06:55:26Z],"[police, people, australia, day, sydney, nsw, ...","[police, people, australia, sydney, nsw, man, ..."
Brisbane Olympics 2032: David Crisafulli breaks election promise and announces controversial new stadium [2025-03-25T02:26:54Z],"[new, stadium, centre, build, crisafulli, priv...","[new, private, sector, build, stadium, arena, ..."
How the architect who made modern Brisbane shaped the city’s 2032 Olympics stadium plans [2025-03-30T14:00:23Z],"[park, city, says, victoria, venues, plans, st...","[park, says, city, victoria, idea, venues, par..."
Brisbane Olympics infrastructure body urges LNP to fast-track controversial venues with special laws [2025-03-26T14:00:02Z],"[review, venues, time, infrastructure, procure...","[procurement, review, required, special, proce..."
Brisbane Olympics 2032: why these Games could turn out nothing like we had planned [2025-03-24T14:01:00Z],"[city, new, stadium, venues, host, public, ide...","[city, idea, new, stadium, paris, building, la..."

## 4. Compare approaches

In [16]:
# Sample 5 random articles
samples = random.sample(range(0,len(terms_df)),5)

for sample in samples:
    doc = terms_df.iloc[sample]
    print(f"[{sample}] {doc.name}")
    print("\t>> Counts:\t",doc['count'])
    print("\t>> TFIDF:\t",doc['tfidf'])
    print()

[11] Brisbane Olympics infrastructure body urges LNP to fast-track controversial venues with special laws [2025-03-26T14:00:02Z]
	>> Counts:	 ['review', 'venues', 'time', 'infrastructure', 'procurement', 'planning', 'park', 'victoria', 'special', 'processes']
	>> TFIDF:	 ['procurement', 'review', 'required', 'special', 'processes', 'projects', 'case', 'infrastructure', 'victoria', 'venues']

[1] Behind the scenes of Brisbane’s 2032 Olympics, a 19th-century story of politics and gay love [2026-01-02T14:00:13Z]
	>> Counts:	 ['says', 'story', 'people', 'history', 'men', 'today', 'community', 'jones', 'know', 'england']
	>> TFIDF:	 ['says', 'story', 'men', 'history', 'jones', 'england', 'today', 'people', 'unlawful', 'reads']

[5] ‘Lovely gentle dinosaurs’: Brisbane 2032 Olympic rowing may be held in saltwater crocodile habitat [2025-03-25T08:31:39Z]
	>> Counts:	 ['crocodile', 'rowing', 'crocodiles', 'river', 'world', 'just', 'international', 'city', 'australia', 'behaviour']
	>> TFIDF:	 ['crocodile', 'rowing', 'crocodiles', 'river', 'behaviour', 'lovely', 'international', 'world', 'just', 'north']

[6] Federal government throws support behind LNP’s controversial new Olympic Games venue at Brisbane’s Victoria Park [2025-07-03T07:13:33Z]
	>> Counts:	 ['new', 'park', 'site', 'victoria', 'bleijie', 'stadium', 'federal', 'planned', 'infrastructure', 'king']
	>> TFIDF:	 ['bleijie', 'new', 'victoria', 'park', 'site', 'king', 'deal', 'arena', 'stadium', 'planned']

[12] Brisbane Olympics 2032: why these Games could turn out nothing like we had planned [2025-03-24T14:01:00Z]
	>> Counts:	 ['city', 'new', 'stadium', 'venues', 'host', 'public', 'idea', 'paris', 'building', 'review']
	>> TFIDF:	 ['city', 'idea', 'new', 'stadium', 'paris', 'building', 'la', 'review', 'venues', 'clear']

## Refine your analysis

Once you have worked through the process. Try tweaking the parameters in the Count and TF/IDF vectorizers to try and obtain better results for your data.

#### Advanced

You may obtain better results by doing the following:

- Creating smaller documents (e.g. article paragraphs)
- Pre-processing the text by Stemming or Lemmatizing, and by removing additional stop words.
- ???

## Reflections

Based on your exploration, reflect on the following questions:

- Considering The Guardian focuses on stories with national or global significance, what kinds of articles can you find using the Guardian API? 
- Based on the articles you retrieved, what kind of narratives can you build, and which ones are impossible to support with this dataset?
- To enhance the narrative, what visualisations would you consider?