<div style="background:#E9FFF6; color:#440404; padding:8px; border-radius: 4px; text-align: center; font-weight: 500;">IFN619 - Data Analytics for Strategic Decision Makers</div>

# IFN619 :: C1-UnstructuredAnalytics

For this session, the focus will be on analysis of unstructured text. However, the thinking required is similar to approaches to analysing images, video, sound and other unstructured data. Primarily, the analysis is based on the notion that there are useful patterns in the unstructured data which can be obtained mathematically. By converting the data to a mathematical structure, various algorithms can be applied to the structure with the aim of identifying patterns. 

In the case of the `topic modelling` approaches below, the techniques are *stochastic* - that is they include a level of randomness and mathematically identify the probability or *likelihood* that a feature might be important. Thus, they are never deterministic, repeatable or 100% accurate, and their use needs to be mediated by a more pragmatic *useful or not* approach, rather than *right or wrong*.

In [1]:
# Import the necessary libraries
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.decomposition import LatentDirichletAllocation, NMF
import pandas as pd
import json
import random

### Accessing the data via The Guardian API

See the `Accessing_the_Guardian_API.ipynb` notebook file for details on getting the data. **Note:** This approach may be used for additional data for Assignment 2.

### Read in pre-saved data

To save time, we're loading in pre-saved data that was fetched using the Guardian API.

In [2]:
# Load the data - articles from The Guardian about the Winter Olympics
file_path = "data/"
file_name = "winter_olympics_articles.json"

with open(f"{file_path}{file_name}",'r', encoding='utf-8') as fp:
    articles = json.load(fp)

print(f"Loaded {len(articles)} articles from {file_name}")

Loaded 13 articles from winter_olympics_articles.json

Each dictionary entry includes the *title [date]* as `key` and the *body text* from the article as `value`.

So the values gives us a list of documents that we can analyse.

In [3]:
# Get a list of documents
documents = list(articles.values())

# View first 400 characters of the 1st document
documents[0][:400]

'When do the 2026 Winter Olympics start? The 2026 Winter Olympics officially open in the early hours of Saturday 7 February, Australian time, with the opening ceremony at Milan’s San Siro stadium. The Games run for two weeks, culminating in the closing ceremony on 23 February in Verona at the same time of 6am AEDT. Several sports with packed schedules, including curling and ice hockey, begin a coup'

### Term Count and TF/IDF as vector inputs for Topic Modelling

Recall from B3 that we created bag of words vectors using `CountVectorizer` and `TfidfVectorizer`.

In this lecture will use these vectors as inputs for our topic modelling algorithms.

All of these analyses, approach the document as a [Bag of Words](https://en.wikipedia.org/wiki/Bag-of-words_model) model. In this approach, the order of the words don't matter. A popular approach that takes into account order is [Word embedding](https://en.wikipedia.org/wiki/Word_embedding). This session does not explore word embedding.

In [4]:
# Only count terms that in maximum of 80% of documents, and a minimum of 2 documents. 
# Count a maximum of 10000 terms, and remove common english stop words
count_vectorizer = CountVectorizer(max_df=0.80,min_df=2,max_features=10000,stop_words="english")
count_dt_matrix = count_vectorizer.fit_transform(articles.values())

In [5]:
# Get the 1000 terms identified during the vectorization process
feature_names = count_vectorizer.get_feature_names_out()
feature_names

array(['000', '10', '10th', '12', '15', '16', '17', '1994', '1998', '20',
       '2002', '2006', '2010', '2022', '2024', '2025', '2026', '20th',
       '21', '23', '25', '26', '27', '28', '30', '31', '50', '53', 'able',
       'accepted', 'according', 'accused', 'achieve', 'acknowledged',
       'acl', 'action', 'actually', 'added', 'adelaide', 'advertiser',
       'advice', 'aedt', 'aerial', 'aerials', 'afternoon', 'age', 'ago',
       'ahead', 'ahmad', 'air', 'alisa', 'allegedly', 'alongside',
       'alpine', 'alps', 'america', 'american', 'amid', 'annual',
       'anthony', 'appeal', 'arms', 'arrived', 'asian', 'assessment',
       'athlete', 'athletes', 'attack', 'attempt', 'attention',
       'australians', 'awarded', 'away', 'backed', 'baff', 'base',
       'based', 'battling', 'bearer', 'beat', 'beating', 'began', 'begin',
       'beijing', 'ben', 'best', 'better', 'bid', 'big', 'biggest', 'bit',
       'blood', 'blow', 'body', 'bradbury', 'brain', 'breadth',
       'breakthrough', 'briefing', 'bring', 'british', 'broken', 'bronze',
       'brought', 'brown', 'brutal', 'cabinet', 'called', 'calm', 'came',
       'camp', 'camplin', 'canada', 'canadian', 'capital', 'captain',
       'career', 'catch', 'celebrated', 'ceremony', 'challenge',
       'champion', 'champions', 'chance', 'change', 'chasing', 'chef',
       'child', 'children', 'china', 'circuit', 'city', 'claim',
       'claiming', 'claims', 'climate', 'close', 'closer', 'closing',
       'club', 'coach', 'coady', 'coast', 'collecting', 'come', 'coming',
       'compete', 'competed', 'competing', 'competition', 'competitions',
       'competitor', 'concerns', 'consciousness', 'considered',
       'consistent', 'contest', 'continue', 'continues', 'control',
       'cool', 'cooper', 'corner', 'correspondent', 'costs', 'couldn',
       'country', 'couple', 'course', 'covered', 'covid', 'crash',
       'crashed', 'cross', 'crossword', 'crosswords', 'crown', 'cruel',
       'cryptic', 'currently', 'daisy', 'day', 'days', 'debut', 'decades',
       'december', 'decision', 'decorated', 'deep', 'defend', 'defending',
       'definitely', 'degrees', 'depth', 'despite', 'did', 'didn',
       'different', 'discipline', 'distance', 'does', 'doesn', 'doing',
       'dominated', 'don', 'donald', 'double', 'dream', 'dropped', 'dual',
       'earlier', 'early', 'ease', 'edged', 'editor', 'efforts', 'eighth',
       'elite', 'elizabeth', 'email', 'end', 'ensure', 'entered',
       'entertained', 'entirely', 'etched', 'europe', 'event', 'events',
       'excited', 'expectations', 'expected', 'explains', 'extend',
       'face', 'failing', 'failure', 'family', 'far', 'fashion',
       'favourite', 'favourites', 'february', 'federal', 'feeling',
       'feels', 'fellow', 'field', 'final', 'finalists', 'finally',
       'finals', 'financial', 'finding', 'finish', 'finished',
       'finishing', 'flag', 'flying', 'follow', 'following', 'football',
       'foreign', 'forest', 'form', 'foundation', 'fourth', 'france',
       'freeski', 'freestyle', 'french', 'friday', 'friends', 'funding',
       'future', 'game', 'germany', 'given', 'glide', 'global', 'glory',
       'going', 'good', 'got', 'government', 'graham', 'great',
       'greatest', 'green', 'grew', 'growing', 'guardian', 'gun',
       'guseli', 'half', 'halfpipe', 'hamilton', 'happened', 'happening',
       'hard', 'harder', 'haul', 'having', 'head', 'heading', 'heating',
       'heavy', 'help', 'high', 'higher', 'highest', 'highly', 'hiking',
       'hill', 'historic', 'history', 'hit', 'home', 'hope', 'hopes',
       'host', 'hours', 'huge', 'ice', 'imagine', 'immigration',
       'improved', 'inbox', 'include', 'including', 'individual', 'indra',
       'injured', 'injury', 'instead', 'interactive', 'international',
       'invested', 'involves', 'involving', 'italy', 'jaelin', 'jakara',
       'james', 'january', 'japan', 'job', 'joined', 'josie', 'journey',
       'judged', 'judges', 'jump', 'jumping', 'jumps', 'just', 'kauf',
       'key', 'knee', 'knew', 'know', 'known', 'laffont', 'lake',
       'landed', 'landing', 'lara', 'largest', 'late', 'later', 'latest',
       'launching', 'laura', 'lead', 'leading', 'league', 'learn',
       'leave', 'leaving', 'led', 'left', 'legs', 'lemley', 'let',
       'liberal', 'life', 'like', 'likely', 'line', 'little', 'live',
       'livigno', 'living', 'll', 'local', 'long', 'looking', 'losing',
       'lost', 'lot', 'love', 'luge', 'mail', 'make', 'makes', 'making',
       'man', 'mark', 'martin', 'matt', 'matter', 'medallist',
       'medallists', 'medals', 'media', 'medical', 'meet', 'melbourne',
       'member', 'men', 'metres', 'milan', 'minister', 'minutes', 'miss',
       'missed', 'missing', 'mission', 'mix', 'mixed', 'mogul', 'moguls',
       'moment', 'moments', 'month', 'months', 'morning', 'moscow',
       'mother', 'mount', 'mountain', 'mountaineering', 'mountains',
       'nailed', 'nation', 'national', 'neck', 'need', 'needed', 'needs',
       'nervous', 'new', 'news', 'newsletter', 'nice', 'night',
       'northern', 'norway', 'nsw', 'number', 'occasion', 'officials',
       'ok', 'olympian', 'open', 'opening', 'opportunity', 'overall',
       'overcame', 'overcome', 'overcoming', 'overnight', 'pace', 'pain',
       'pair', 'parents', 'partner', 'pass', 'past', 'peak', 'peel',
       'pegan', 'people', 'perfect', 'performance', 'perisher', 'perrine',
       'peter', 'pictures', 'place', 'playing', 'podium', 'podiums',
       'point', 'points', 'political', 'politics', 'position',
       'possibility', 'power', 'practice', 'pre', 'pressure',
       'prestigious', 'pretty', 'prices', 'pride', 'process',
       'professional', 'program', 'progress', 'progression', 'proud',
       'public', 'pulled', 'push', 'pyeongchang', 'qualifying', 'quarter',
       'queensland', 'quick', 'quickly', 'quite', 'race', 'raised',
       'ranked', 'rare', 'realised', 'really', 'receive', 'recent',
       'record', 'recorded', 'recover', 'refused', 'reged', 'regrets',
       'regular', 'reigning', 'related', 'relay', 'remains', 'remarkable',
       'repeat', 'reports', 'rest', 'results', 'return', 'returning',
       'richard', 'right', 'rise', 'round', 'rounds', 'roundup', 'row',
       'run', 'running', 'runs', 'ruptured', 'said', 'sarah', 'saturday',
       'saw', 'say', 'says', 'schedule', 'school', 'score', 'scoring',
       'scotty', 'season', 'second', 'secured', 'seen', 'semi', 'set',
       'seven', 'seventh', 'shadow', 'sharing', 'shock', 'short', 'shown',
       'sign', 'significant', 'signing', 'silver', 'single', 'singles',
       'site', 'skater', 'ski', 'skier', 'skiers', 'skiing', 'skills',
       'skimo', 'skins', 'skis', 'slalom', 'slip', 'slopes', 'smile',
       'smith', 'snow', 'snowboard', 'snowboarder', 'snowboarders',
       'snowboarding', 'social', 'sort', 'south', 'speaks', 'special',
       'speed', 'sporting', 'sports', 'spot', 'spotlight', 'sprint',
       'staff', 'standing', 'star', 'start', 'started', 'starting',
       'starts', 'state', 'statement', 'stay', 'staying', 'step',
       'steven', 'stoked', 'story', 'strategy', 'strength', 'strong',
       'stuck', 'stuff', 'success', 'successful', 'summit', 'sun',
       'sunday', 'support', 'swept', 'switzerland', 'sydney', 'table',
       'taking', 'team', 'teammates', 'teaser', 'tech', 'teenager',
       'tess', 'thing', 'things', 'think', 'thomas', 'thought', 'threat',
       'thursday', 'time', 'times', 'title', 'today', 'told', 'tomorrow',
       'took', 'topalovic', 'total', 'tougher', 'town', 'track',
       'training', 'trick', 'triumph', 'trump', 'trumpland', 'try',
       'trying', 'turin', 'turn', 'turned', 'turns', 'twice', 'uk',
       'unable', 'unlikely', 'unprecedented', 'update', 'use',
       'valentino', 'valley', 've', 'veteran', 'victoria', 'victory',
       'wales', 'want', 'wanted', 'war', 'wasn', 'watch', 'water',
       'waterville', 'way', 'week', 'weekday', 'weeks', 'weight', 'went',
       'win', 'winner', 'winning', 'wins', 'woman', 'women', 'won',
       'woods', 'work', 'worst', 'years', 'yellow', 'youngest', 'zealand'],
      dtype=object)

In [6]:
# Take a look at the vocabulary which shows the total counts for whole collection
count_vectorizer.vocabulary_

{'2026': np.int64(16),
 'start': np.int64(624),
 'open': np.int64(464),
 'early': np.int64(211),
 'hours': np.int64(321),
 'saturday': np.int64(562),
 'february': np.int64(242),
 'time': np.int64(665),
 'opening': np.int64(465),
 'ceremony': np.int64(119),
 'milan': np.int64(421),
 'run': np.int64(556),
 'weeks': np.int64(712),
 'closing': np.int64(138),
 '23': np.int64(19),
 'aedt': np.int64(41),
 'sports': np.int64(617),
 'including': np.int64(329),
 'ice': np.int64(323),
 'begin': np.int64(82),
 'couple': np.int64(167),
 'days': np.int64(182),
 'mixed': np.int64(429),
 'team': np.int64(652),
 'just': np.int64(355),
 'missed': np.int64(425),
 'qualifying': np.int64(517),
 'despite': np.int64(194),
 'ranked': np.int64(525),
 'december': np.int64(185),
 'won': np.int64(721),
 'italy': np.int64(340),
 'final': np.int64(248),
 'event': np.int64(227),
 'men': np.int64(419),
 'game': np.int64(275),
 '12': np.int64(3),
 'related': np.int64(539),
 'youngest': np.int64(727),
 'olympian': np.int64(463),
 'indra': np.int64(331),
 'brown': np.int64(104),
 'love': np.int64(400),
 'feeling': np.int64(244),
 'flying': np.int64(258),
 'martin': np.int64(408),
 'pegan': np.int64(481),
 'place': np.int64(489),
 'northern': np.int64(456),
 'livigno': np.int64(391),
 'athletes': np.int64(66),
 '15': np.int64(4),
 'competing': np.int64(148),
 'host': np.int64(320),
 'turin': np.int64(684),
 '2006': np.int64(11),
 'interactive': np.int64(335),
 'watch': np.int64(706),
 'guardian': np.int64(291),
 'live': np.int64(390),
 'day': np.int64(181),
 '10': np.int64(1),
 'schedule': np.int64(566),
 'starts': np.int64(627),
 'local': np.int64(394),
 'sign': np.int64(584),
 'briefing': np.int64(98),
 'newsletter': np.int64(453),
 'best': np.int64(85),
 'come': np.int64(144),
 'new': np.int64(451),
 'ski': np.int64(592),
 'mountaineering': np.int64(441),
 'skimo': np.int64(597),
 'involves': np.int64(338),
 'skiing': np.int64(595),
 'skins': np.int64(598),
 'hiking': np.int64(312),
 'skis': np.int64(599),
 'athlete': np.int64(65),
 'events': np.int64(228),
 'sprint': np.int64(620),
 'women': np.int64(720),
 'relay': np.int64(540),
 'luge': np.int64(401),
 'jumping': np.int64(353),
 'freestyle': np.int64(269),
 'alpine': np.int64(53),
 '000': np.int64(0),
 'medals': np.int64(413),
 'hope': np.int64(318),
 'cross': np.int64(173),
 'country': np.int64(166),
 'running': np.int64(557),
 'french': np.int64(270),
 'alps': np.int64(54),
 'going': np.int64(281),
 'table': np.int64(650),
 'norway': np.int64(457),
 'spot': np.int64(618),
 'collecting': np.int64(143),
 '16': np.int64(5),
 'silver': np.int64(587),
 'bronze': np.int64(102),
 '2022': np.int64(13),
 'ahead': np.int64(47),
 'germany': np.int64(276),
 'beijing': np.int64(83),
 'dominated': np.int64(203),
 'europe': np.int64(226),
 'america': np.int64(55),
 'china': np.int64(129),
 'highest': np.int64(310),
 'asian': np.int64(63),
 'second': np.int64(572),
 'largest': np.int64(367),
 '53': np.int64(27),
 'recent': np.int64(530),
 'circuit': np.int64(130),
 'record': np.int64(531),
 'haul': np.int64(301),
 'years': np.int64(725),
 'ago': np.int64(46),
 'finished': np.int64(255),
 'zealand': np.int64(728),
 'great': np.int64(286),
 'coming': np.int64(145),
 'home': np.int64(317),
 'pictures': np.int64(488),
 'medallists': np.int64(412),
 'mogul': np.int64(430),
 'skier': np.int64(593),
 'jakara': np.int64(342),
 'anthony': np.int64(59),
 'snowboarders': np.int64(608),
 'scotty': np.int64(570),
 'james': np.int64(343),
 'tess': np.int64(657),
 'coady': np.int64(141),
 'missing': np.int64(426),
 'include': np.int64(328),
 'teenager': np.int64(656),
 'freeski': np.int64(268),
 'halfpipe': np.int64(295),
 'valentino': np.int64(695),
 'guseli': np.int64(293),
 'snowboard': np.int64(606),
 'mark': np.int64(407),
 'end': np.int64(220),
 'january': np.int64(344),
 'big': np.int64(88),
 'news': np.int64(452),
 'covid': np.int64(170),
 'far': np.int64(238),
 'sporting': np.int64(616),
 'competition': np.int64(149),
 'playing': np.int64(490),
 'continues': np.int64(158),
 'attempt': np.int64(68),
 'australians': np.int64(70),
 'expected': np.int64(231),
 'quite': np.int64(522),
 'wasn': np.int64(705),
 'cruel': np.int64(177),
 'moguls': np.int64(431),
 'left': np.int64(380),
 'field': np.int64(247),
 'podium': np.int64(491),
 'success': np.int64(641),
 'failure': np.int64(236),
 'hard': np.int64(299),
 'snow': np.int64(605),
 'defending': np.int64(190),
 'medallist': np.int64(411),
 'thursday': np.int64(664),
 'morning': np.int64(436),
 'week': np.int64(710),
 '27': np.int64(22),
 'recorded': np.int64(532),
 'score': np.int64(568),
 'round': np.int64(552),
 'didn': np.int64(196),
 'couldn': np.int64(165),
 'stay': np.int64(630),
 'course': np.int64(168),
 'slip': np.int64(601),
 'costs': np.int64(164),
 'title': np.int64(667),
 'flag': np.int64(257),
 'bearer': np.int64(78),
 'things': np.int64(659),
 'yellow': np.int64(726),
 'green': np.int64(288),
 'staff': np.int64(621),
 'training': np.int64(677),
 'base': np.int64(75),
 'began': np.int64(81),
 'officials': np.int64(461),
 'pre': np.int64(501),
 'entirely': np.int64(224),
 'medical': np.int64(415),
 'aerials': np.int64(43),
 'veteran': np.int64(698),
 'laura': np.int64(372),
 'peel': np.int64(480),
 'significant': np.int64(585),
 'knee': np.int64(358),
 'injury': np.int64(333),
 'doing': np.int64(202),
 'recover': np.int64(533),
 'compete': np.int64(146),
 'fourth': np.int64(266),
 'daisy': np.int64(180),
 'thomas': np.int64(661),
 'landed': np.int64(364),
 'jump': np.int64(352),
 'injured': np.int64(332),
 'right': np.int64(550),
 'pulled': np.int64(514),
 'hopes': np.int64(319),
 'air': np.int64(49),
 'discipline': np.int64(198),
 'broken': np.int64(101),
 'neck': np.int64(446),
 'snowboarder': np.int64(607),
 'hit': np.int64(316),
 'head': np.int64(303),
 'failing': np.int64(235),
 'assessment': np.int64(64),
 'looking': np.int64(396),
 'losing': np.int64(397),
 'control': np.int64(159),
 'hill': np.int64(313),
 'twice': np.int64(688),
 'leaving': np.int64(378),
 'reigning': np.int64(538),
 'champion': np.int64(121),
 'finalists': np.int64(249),
 'degrees': np.int64(192),
 'short': np.int64(582),
 'unlikely': np.int64(691),
 'bid': np.int64(87),
 'seventh': np.int64(578),
 'alongside': np.int64(52),
 'favourite': np.int64(240),
 '31': np.int64(25),
 'entered': np.int64(222),
 'performance': np.int64(484),
 'american': np.int64(56),
 'thought': np.int64(662),
 'told': np.int64(669),
 'think': np.int64(660),
 'peak': np.int64(479),
 'added': np.int64(37),
 'like': np.int64(386),
 'future': np.int64(274),
 'high': np.int64(308),
 'slopes': np.int64(602),
 'work': np.int64(723),
 'progress': np.int64(510),
 'secured': np.int64(573),
 'track': np.int64(676),
 '1994': np.int64(7),
 'remains': np.int64(541),
 'chef': np.int64(126),
 'mission': np.int64(427),
 'alisa': np.int64(50),
 'camplin': np.int64(111),
 'breadth': np.int64(96),
 'depth': np.int64(193),
 'international': np.int64(336),
 'months': np.int64(435),
 'dual': np.int64(209),
 'nation': np.int64(444),
 'consciousness': np.int64(153),
 'turn': np.int64(685),
 'lead': np.int64(373),
 'foundation': np.int64(265),
 'lara': np.int64(366),
 'hamilton': np.int64(296),
 'brought': np.int64(103),
 'sarah': np.int64(561),
 '21': np.int64(18),
 'professional': np.int64(508),
 'support': np.int64(646),
 'federal': np.int64(243),
 'government': np.int64(284),
 'make': np.int64(403),
 'opportunity': np.int64(466),
 'miss': np.int64(424),
 'foreign': np.int64(262),
 'winning': np.int64(717),
 'thing': np.int64(658),
 'appeal': np.int64(60),
 'moment': np.int64(432),
 'long': np.int64(395),
 'nice': np.int64(454),
 'brutal': np.int64(105),
 'known': np.int64(361),
 'little': np.int64(389),
 'claiming': np.int64(133),
 'national': np.int64(445),
 'turned': np.int64(686),
 'learn': np.int64(376),
 'overcoming': np.int64(470),
 'single': np.int64(588),
 'family': np.int64(237),
 'friends': np.int64(272),
 'teammates': np.int64(653),
 'later': np.int64(369),
 'smile': np.int64(603),
 'face': np.int64(234),
 'bit': np.int64(90),
 'happened': np.int64(297),
 'said': np.int64(560),
 'triumph': np.int64(679),
 'really': np.int64(528),
 'singles': np.int64(589),
 'came': np.int64(109),
 'chance': np.int64(123),
 'taking': np.int64(651),
 'step': np.int64(632),
 'elite': np.int64(217),
 'know': np.int64(360),
 'able': np.int64(28),
 'help': np.int64(307),
 'pretty': np.int64(504),
 'makes': np.int64(404),
 'special': np.int64(614),
 'arrived': np.int64(62),
 'history': np.int64(315),
 'following': np.int64(260),
 'set': np.int64(576),
 'rounds': np.int64(553),
 'prices': np.int64(505),
 'winner': np.int64(716),
 'amid': np.int64(57),
 'rare': np.int64(526),
 'worst': np.int64(724),
 'corner': np.int64(162),
 'decades': np.int64(184),
 'competed': np.int64(147),
 'half': np.int64(294),
 'heading': np.int64(304),
 'lot': np.int64(399),
 'glory': np.int64(280),
 'got': np.int64(283),
 'needed': np.int64(448),
 'different': np.int64(197),
 'trying': np.int64(683),
 'swept': np.int64(647),
 'judges': np.int64(351),
 'quarter': np.int64(518),
 'closer': np.int64(137),
 'pair': np.int64(474),
 'way': np.int64(709),
 'huge': np.int64(322),
 'statement': np.int64(629),
 'beating': np.int64(80),
 'elizabeth': np.int64(218),
 'lemley': np.int64(382),
 'semi': np.int64(575),
 'runs': np.int64(558),
 'win': np.int64(715),
 'jaelin': np.int64(341),
 'kauf': np.int64(356),
 'instead': np.int64(334),
 'etched': np.int64(225),
 'victory': np.int64(700),
 'making': np.int64(405),
 'successful': np.int64(642),
 'cooper': np.int64(161),
 'woods': np.int64(722),
 'josie': np.int64(348),
 'baff': np.int64(74),
 'ease': np.int64(212),
 'pain': np.int64(473),
 'shock': np.int64(581),
 'eighth': np.int64(216),
 'finish': np.int64(254),
 'given': np.int64(277),
 'overcome': np.int64(469),
 'started': np.int64(625),
 'child': np.int64(127),
 'parents': np.int64(475),
 'let': np.int64(383),
 'went': np.int64(714),
 'school': np.int64(567),
 'south': np.int64(612),
 'wales': np.int64(701),
 'town': np.int64(675),
 'perisher': np.int64(485),
 'children': np.int64(128),
 'debut': np.int64(183),
 'pace': np.int64(472),
 'says': np.int64(565),
 'saw': np.int64(563),
 'heavy': np.int64(306),
 'invested': np.int64(337),
 'stuff': np.int64(640),
 'knew': np.int64(359),
 'mountain': np.int64(440),
 'quickly': np.int64(521),
 'key': np.int64(357),
 'journey': np.int64(349),
 'race': np.int64(523),
 '17': np.int64(6),
 'ok': np.int64(462),
 'actually': np.int64(36),
 'good': np.int64(282),
 'better': np.int64(86),
 'sydney': np.int64(649),
 'results': np.int64(546),
 'point': np.int64(493),
 'starting': np.int64(626),
 'catch': np.int64(117),
 'highly': np.int64(311),
 'cool': np.int64(160),
 'try': np.int64(682),
 'distance': np.int64(199),
 'mix': np.int64(428),
 'need': np.int64(447),
 'life': np.int64(385),
 'pass': np.int64(477),
 'forest': np.int64(263),
 'say': np.int64(564),
 'sun': np.int64(644),
 'calm': np.int64(108),
 'coach': np.int64(140),
 '2025': np.int64(15),
 'improved': np.int64(326),
 'excited': np.int64(229),
 'finding': np.int64(253),
 'achieve': np.int64(32),
 'strong': np.int64(638),
 'state': np.int64(628),
 'feels': np.int64(245),
 'living': np.int64(392),
 'covered': np.int64(169),
 'funding': np.int64(273),
 'job': np.int64(346),
 'season': np.int64(571),
 'rest': np.int64(545),
 'challenge': np.int64(120),
 'called': np.int64(107),
 'progression': np.int64(511),
 'times': np.int64(666),
 'month': np.int64(434),
 'having': np.int64(302),
 'competitions': np.int64(150),
 'line': np.int64(388),
 'individual': np.int64(330),
 'does': np.int64(200),
 'stuck': np.int64(639),
 'don': np.int64(204),
 'snowboarding': np.int64(609),
 'star': np.int64(623),
 'landing': np.int64(365),
 'continue': np.int64(157),
 'fashion': np.int64(239),
 '20': np.int64(9),
 'unable': np.int64(690),
 'jumps': np.int64(354),
 'night': np.int64(455),
 '10th': np.int64(2),
 'japan': np.int64(345),
 'harder': np.int64(300),
 'wanted': np.int64(703),
 'regrets': np.int64(536),
 'stoked': np.int64(634),
 'competitor': np.int64(151),
 'canadian': np.int64(113),
 'man': np.int64(406),
 'repeat': np.int64(543),
 'pressure': np.int64(502),
 'number': np.int64(459),
 'nailed': np.int64(443),
 '50': np.int64(26),
 'wins': np.int64(718),
 'today': np.int64(668),
 'did': np.int64(195),
 'trick': np.int64(678),
 'ruptured': np.int64(559),
 'acl': np.int64(34),
 'late': np.int64(368),
 '2024': np.int64(14),
 'biggest': np.int64(89),
 'definitely': np.int64(191),
 'edged': np.int64(213),
 'total': np.int64(673),
 'points': np.int64(494),
 'contest': np.int64(156),
 'considered': np.int64(154),
 'blow': np.int64(92),
 'crash': np.int64(171),
 'coast': np.int64(142),
 'proud': np.int64(512),
 'aerial': np.int64(42),
 'crashed': np.int64(172),
 'switzerland': np.int64(648),
 'based': np.int64(76),
 'strength': np.int64(637),
 '20th': np.int64(17),
 'position': np.int64(497),
 'follow': np.int64(259),
 'sunday': np.int64(645),
 'consistent': np.int64(155),
 'global': np.int64(279),
 'seven': np.int64(577),
 'celebrated': np.int64(118),
 'moments': np.int64(433),
 'bradbury': np.int64(94),
 'steven': np.int64(633),
 'accepted': np.int64(29),
 'legs': np.int64(381),
 'speed': np.int64(615),
 'power': np.int64(499),
 'lake': np.int64(363),
 'city': np.int64(131),
 '2002': np.int64(10),
 'finals': np.int64(251),
 'higher': np.int64(309),
 '28': np.int64(23),
 'metres': np.int64(420),
 'took': np.int64(671),
 'arms': np.int64(61),
 'glide': np.int64(278),
 'claim': np.int64(132),
 'pride': np.int64(506),
 'breakthrough': np.int64(97),
 'prestigious': np.int64(503),
 'slalom': np.int64(600),
 'earlier': np.int64(210),
 'woman': np.int64(719),
 '1998': np.int64(8),
 'finishing': np.int64(256),
 'skiers': np.int64(594),
 'advice': np.int64(40),
 'double': np.int64(206),
 'overcame': np.int64(468),
 '2010': np.int64(12),
 'extend': np.int64(233),
 'skater': np.int64(591),
 'richard': np.int64(549),
 'backed': np.int64(73),
 'strategy': np.int64(636),
 'staying': np.int64(631),
 'battling': np.int64(77),
 'smith': np.int64(604),
 'change': np.int64(124),
 'canada': np.int64(112),
 'age': np.int64(45),
 'tech': np.int64(655),
 'claims': np.int64(134),
 'sort': np.int64(611),
 'scoring': np.int64(569),
 'leave': np.int64(377),
 'champions': np.int64(122),
 'joined': np.int64(347),
 'overnight': np.int64(471),
 'dropped': np.int64(208),
 'launching': np.int64(371),
 'favourites': np.int64(241),
 'bring': np.int64(99),
 'member': np.int64(418),
 'want': np.int64(702),
 've': np.int64(697),
 'mother': np.int64(438),
 'imagine': np.int64(324),
 'occasion': np.int64(460),
 'attention': np.int64(69),
 'minutes': np.int64(423),
 'captain': np.int64(115),
 'chasing': np.int64(125),
 'allegedly': np.int64(51),
 'melbourne': np.int64(417),
 'shown': np.int64(583),
 'away': np.int64(72),
 'spotlight': np.int64(619),
 'camp': np.int64(110),
 'meet': np.int64(416),
 'crown': np.int64(176),
 'pyeongchang': np.int64(516),
 'returning': np.int64(548),
 'regular': np.int64(537),
 'mountains': np.int64(442),
 'annual': np.int64(58),
 'mount': np.int64(439),
 'victoria': np.int64(699),
 'sharing': np.int64(580),
 'podiums': np.int64(492),
 'grew': np.int64(289),
 'push': np.int64(515),
 'realised': np.int64(527),
 'skills': np.int64(596),
 'close': np.int64(136),
 'leading': np.int64(374),
 'nervous': np.int64(450),
 'process': np.int64(507),
 'practice': np.int64(500),
 'standing': np.int64(622),
 'deep': np.int64(188),
 'quick': np.int64(520),
 'doesn': np.int64(201),
 'historic': np.int64(314),
 'overall': np.int64(467),
 'weight': np.int64(713),
 'currently': np.int64(179),
 'action': np.int64(35),
 'unprecedented': np.int64(692),
 'decorated': np.int64(187),
 'matt': np.int64(409),
 'graham': np.int64(285),
 'program': np.int64(509),
 'dream': np.int64(207),
 'peter': np.int64(487),
 'topalovic': np.int64(672),
 'ensure': np.int64(221),
 'queensland': np.int64(519),
 'water': np.int64(707),
 'explains': np.int64(232),
 'past': np.int64(478),
 'tougher': np.int64(674),
 'concerns': np.int64(152),
 'acknowledged': np.int64(33),
 'minister': np.int64(422),
 'blood': np.int64(91),
 'public': np.int64(513),
 'latest': np.int64(370),
 'financial': np.int64(252),
 'body': np.int64(93),
 'efforts': np.int64(215),
 'partner': np.int64(476),
 'possibility': np.int64(498),
 'summit': np.int64(643),
 '30': np.int64(24),
 'defend': np.int64(189),
 'greatest': np.int64(287),
 'fellow': np.int64(246),
 'decision': np.int64(186),
 'row': np.int64(555),
 'people': np.int64(482),
 '25': np.int64(20),
 'cabinet': np.int64(106),
 '26': np.int64(21),
 'awarded': np.int64(71),
 'raised': np.int64(524),
 'judged': np.int64(350),
 'turns': np.int64(687),
 'perfect': np.int64(483),
 'waterville': np.int64(708),
 'valley': np.int64(696),
 'france': np.int64(267),
 'perrine': np.int64(486),
 'laffont': np.int64(362),
 'threat': np.int64(663),
 'career': np.int64(116),
 'remarkable': np.int64(542),
 'form': np.int64(264),
 'media': np.int64(414),
 'expectations': np.int64(230),
 'likely': np.int64(387),
 'seen': np.int64(574),
 'll': np.int64(393),
 'nsw': np.int64(458),
 'friday': np.int64(271),
 'club': np.int64(139),
 'beat': np.int64(79),
 'use': np.int64(694),
 'lost': np.int64(398),
 'growing': np.int64(290),
 'tomorrow': np.int64(670),
 'rise': np.int64(551),
 'refused': np.int64(534),
 'site': np.int64(590),
 'social': np.int64(610),
 'matter': np.int64(410),
 'story': np.int64(635),
 'liberal': np.int64(384),
 'shadow': np.int64(579),
 'gun': np.int64(292),
 'according': np.int64(30),
 'editor': np.int64(214),
 'climate': np.int64(135),
 'attack': np.int64(67),
 'capital': np.int64(114),
 'donald': np.int64(205),
 'trump': np.int64(680),
 'involving': np.int64(339),
 'accused': np.int64(31),
 'moscow': np.int64(437),
 'uk': np.int64(689),
 'british': np.int64(100),
 'immigration': np.int64(325),
 'war': np.int64(704),
 'political': np.int64(495),
 'reged': np.int64(535),
 'ahmad': np.int64(48),
 'speaks': np.int64(613),
 'correspondent': np.int64(163),
 'ben': np.int64(84),
 'needs': np.int64(449),
 'heating': np.int64(305),
 'return': np.int64(547),
 'led': np.int64(379),
 'football': np.int64(261),
 'league': np.int64(375),
 'roundup': np.int64(554),
 'adelaide': np.int64(38),
 'reports': np.int64(544),
 'advertiser': np.int64(39),
 'happening': np.int64(298),
 'receive': np.int64(529),
 'mail': np.int64(402),
 'update': np.int64(693),
 'email': np.int64(219),
 'inbox': np.int64(327),
 'weekday': np.int64(711),
 'afternoon': np.int64(44),
 'politics': np.int64(496),
 'signing': np.int64(586),
 'trumpland': np.int64(681),
 'brain': np.int64(95),
 'teaser': np.int64(654),
 'finally': np.int64(250),
 'crosswords': np.int64(175),
 'entertained': np.int64(223),
 'crossword': np.int64(174),
 'cryptic': np.int64(178)}

In [7]:
# Create a new dataframe with the matrix - use titles for the index and terms for the columns
count_df = pd.DataFrame(count_dt_matrix.toarray(), columns=feature_names)
#count_df

Keep a list of the titles of the articles to make it easy to see the headline that relates to the topics. We can always go back to the original documents if we need to.

In [8]:
titles=list(articles.keys())
titles

['Winter Olympics 2026: what you need to know if following from Australia [2026-02-02T14:00:10Z]',
 'Australia’s upward trajectory slips off course as Winter Olympics medal search goes on | Jack Snape [2026-02-12T03:36:06Z]',
 '‘Even more special’: Jakara Anthony dusts off Winter Olympics heartbreak for historic triumph [2026-02-15T01:32:16Z]',
 'A part-time job and DJ gigs helped Lara Hamilton reach the Winter Olympics. Now she wants to put Australia on the map [2026-02-17T14:00:15Z]',
 'Valentino Guseli’s unexpected big air dream ends without a medal in all-or-nothing final: ‘I left it all out there’ [2026-02-08T00:27:13Z]',
 'From Bradbury to Bright: five of Australia’s best Winter Olympic moments | Martin Pegan [2026-02-03T14:00:08Z]',
 'Australia’s youngest Winter Olympian Indra Brown: ‘I just love the feeling of flying’ | Martin Pegan [2026-02-01T14:00:34Z]',
 'How did Australia – better known for its beaches than snow – become a consistent Winter Olympics performer? | Kieran Pender [2026-02-17T01:14:10Z]',
 '‘Put the blinders on’: how Jakara Anthony can make Winter Olympics history [2026-02-10T02:32:34Z]',
 'Ice in his veins: Australian skier Cooper Woods embraces pressure to realise Winter Olympic dream [2026-02-13T02:17:26Z]',
 'Australia’s Jakara Anthony clinches first ever dual moguls Olympics gold [2026-02-14T11:40:32Z]',
 'Morning Mail: Lake Cargelligo suspect’s past revealed, supermarket ‘per unit’ prices under scrutiny, shark attack spike [2026-02-18T20:23:22Z]',
 'Morning Mail: Taylor sets up Liberal spill, millionaires call for higher taxes, Australia’s skiing hope slips up [2026-02-11T19:40:12Z]']

By selecting a row from the dataframe and sorting the values (counts), we can identify the top 10 terms

In [9]:
# Sample 5 random article numbers
samples = random.sample(range(0,len(count_df)),5)

# View the associated terms
for sample in samples:
    doc = count_df.iloc[sample]
    title = titles[sample]
    top_terms = dict(count_df.iloc[sample].sort_values(ascending=False).head(10))
    print(f"[{sample}] {title}")
    print("\t- Top terms:",top_terms)
    print()

[11] Morning Mail: Lake Cargelligo suspect’s past revealed, supermarket ‘per unit’ prices under scrutiny, shark attack spike [2026-02-18T20:23:22Z]
	- Top terms: {'morning': np.int64(4), 'history': np.int64(3), 'including': np.int64(3), 'new': np.int64(3), 'government': np.int64(3), 'people': np.int64(3), 'day': np.int64(3), 'children': np.int64(3), 'crossword': np.int64(2), 'asian': np.int64(2)}

[1] Australia’s upward trajectory slips off course as Winter Olympics medal search goes on | Jack Snape [2026-02-12T03:36:06Z]
	- Top terms: {'team': np.int64(7), 'anthony': np.int64(7), 'final': np.int64(5), 'competition': np.int64(5), 'medals': np.int64(4), 'training': np.int64(4), 'event': np.int64(4), '000': np.int64(3), 'air': np.int64(3), 'big': np.int64(3)}

[7] How did Australia – better known for its beaches than snow – become a consistent Winter Olympics performer? | Kieran Pender [2026-02-17T01:14:10Z]
	- Top terms: {'medals': np.int64(8), 'moguls': np.int64(7), 'sports': np.int64(6), 'team': np.int64(5), 'funding': np.int64(5), 'olympian': np.int64(5), 'success': np.int64(4), 'aerial': np.int64(4), 'snow': np.int64(4), 'skiing': np.int64(4)}

[3] A part-time job and DJ gigs helped Lara Hamilton reach the Winter Olympics. Now she wants to put Australia on the map [2026-02-17T14:00:15Z]
	- Top terms: {'hamilton': np.int64(11), 'ski': np.int64(8), 'skimo': np.int64(7), 'just': np.int64(7), 'running': np.int64(7), 'says': np.int64(6), 'skiing': np.int64(5), 'going': np.int64(4), 'mountaineering': np.int64(4), 'good': np.int64(3)}

[4] Valentino Guseli’s unexpected big air dream ends without a medal in all-or-nothing final: ‘I left it all out there’ [2026-02-08T00:27:13Z]
	- Top terms: {'final': np.int64(11), 'guseli': np.int64(9), 'said': np.int64(5), 'time': np.int64(4), 'score': np.int64(4), 'air': np.int64(4), 'best': np.int64(4), 'big': np.int64(4), 'run': np.int64(4), 'round': np.int64(4)}

#### Create a top10 terms dataframe

Using the index from the documents, create a dataframe that can hold the top10 terms for each document. We also include columns for our other analysis (tfidf, lda, nmf)

In [10]:
# Create a dataframe to hold top terms for each analysis type
terms_df = pd.DataFrame(index=count_df.index,columns=['title','count','tfidf','lda','nmf'])
terms_df['title'] = titles
terms_df

                                                title count tfidf  lda  nmf
0   Winter Olympics 2026: what you need to know if...   NaN   NaN  NaN  NaN
1   Australia’s upward trajectory slips off course...   NaN   NaN  NaN  NaN
2   ‘Even more special’: Jakara Anthony dusts off ...   NaN   NaN  NaN  NaN
3   A part-time job and DJ gigs helped Lara Hamilt...   NaN   NaN  NaN  NaN
4   Valentino Guseli’s unexpected big air dream en...   NaN   NaN  NaN  NaN
5   From Bradbury to Bright: five of Australia’s b...   NaN   NaN  NaN  NaN
6   Australia’s youngest Winter Olympian Indra Bro...   NaN   NaN  NaN  NaN
7   How did Australia – better known for its beach...   NaN   NaN  NaN  NaN
8   ‘Put the blinders on’: how Jakara Anthony can ...   NaN   NaN  NaN  NaN
9   Ice in his veins: Australian skier Cooper Wood...   NaN   NaN  NaN  NaN
10  Australia’s Jakara Anthony clinches first ever...   NaN   NaN  NaN  NaN
11  Morning Mail: Lake Cargelligo suspect’s past r...   NaN   NaN  NaN  NaN
12  Morning Mail: Taylor sets up Liberal spill, mi...   NaN   NaN  NaN  NaN

Populate the count column with data created by the count vectorizer.

In [11]:
#For each doc, get the 10 columns with the largest counts
for idx in terms_df.index:
    counts = dict(count_df.loc[idx].sort_values(ascending=False).head(10))
    #print(counts)
    terms_df.at[idx,'count'] = list(counts.keys()) # Just the list of terms

terms_df

,title,count,tfidf,lda,nmf
0,Winter Olympics 2026: what you need to know if...,"[2026, ice, new, athletes, aedt, day, ski, wat...",NaN,NaN,NaN
1,Australia’s upward trajectory slips off course...,"[team, anthony, final, competition, medals, tr...",NaN,NaN,NaN
2,‘Even more special’: Jakara Anthony dusts off ...,"[moguls, anthony, dual, single, event, just, f...",NaN,NaN,NaN
3,A part-time job and DJ gigs helped Lara Hamilt...,"[hamilton, ski, skimo, just, running, says, sk...",NaN,NaN,NaN
4,Valentino Guseli’s unexpected big air dream en...,"[final, guseli, said, time, score, air, best, ...",NaN,NaN,NaN
5,From Bradbury to Bright: five of Australia’s b...,"[bradbury, event, high, bronze, skiing, way, s...",NaN,NaN,NaN
6,Australia’s youngest Winter Olympian Indra Bro...,"[just, indra, brown, time, says, want, halfpip...",NaN,NaN,NaN
7,How did Australia – better known for its beach...,"[medals, moguls, sports, team, funding, olympi...",NaN,NaN,NaN
8,‘Put the blinders on’: how Jakara Anthony can ...,"[anthony, moguls, says, ski, win, field, seaso...",NaN,NaN,NaN
9,Ice in his veins: Australian skier Cooper Wood...,"[woods, said, just, cooper, lot, final, win, t...",NaN,NaN,NaN
10,Australia’s Jakara Anthony clinches first ever...,"[anthony, second, moguls, james, halfpipe, tra...",NaN,NaN,NaN
11,Morning Mail: Lake Cargelligo suspect’s past r...,"[morning, history, including, new, government,...",NaN,NaN,NaN
12,"Morning Mail: Taylor sets up Liberal spill, mi...","[morning, smith, shock, australians, today, ab...",NaN,NaN,NaN

The [TF/IDF](https://en.wikipedia.org/wiki/Tf–idf) algorithm takes the term frequencies for a document and divides them by the frequencies of the terms in the whole collection.

In [12]:
# Only count terms that in maximum of 80% of documents, and a minimum of 2 documents. 
# Count a maximum of 10000 terms, and remove common english stop words
tfidf_vectorizer = TfidfVectorizer(
    max_df=0.80, min_df=2, max_features=10000, stop_words="english"
)

In [13]:
# Get the document vectors
tfidf_dt_matrix = tfidf_vectorizer.fit_transform(articles.values())

# Display the vector for the first document
tfidf_dt_matrix.toarray()[0]

array([0.05782947, 0.05782947, 0.        , 0.13860385, 0.07100469,
       0.03854199, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.05782947, 0.        , 0.10650704, 0.        ,
       0.        , 0.19692714, 0.        , 0.        , 0.10256164,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.05782947, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.2313179 , 0.        , 0.        , 0.        ,
       0.        , 0.042051  , 0.09240257, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.04620128, 0.05782947,
       0.05782947, 0.        , 0.        , 0.        , 0.03282119,
       0.        , 0.        , 0.        , 0.05782947, 0.        ,
       0.03854199, 0.17751174, 0.        , 0.05782947, 0.        ,
       0.042051  , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.04620128, 0.07100469, 0.        ,
       0.03282119, 0.        , 0.        , 0.03854199, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.05782947, 0.        ,
       0.        , 0.        , 0.08410201, 0.        , 0.09240257,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.12615301,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.05782947,
       0.05128082, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.05782947, 0.        ,
       0.        , 0.05782947, 0.        , 0.05782947, 0.042051  ,
       0.04620128, 0.        , 0.        , 0.08410201, 0.03550235,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.05782947, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.06084563, 0.042051  , 0.        , 0.        ,
       0.05782947, 0.        , 0.        , 0.03550235, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.13128476, 0.042051  , 0.        , 0.        ,
       0.05782947, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.03854199,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.05782947, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.05128082, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.05128082, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.05782947, 0.02825322, 0.07100469, 0.        ,
       0.        , 0.05782947, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.04620128, 0.        ,
       0.        , 0.        , 0.13860385, 0.        , 0.04620128,
       0.        , 0.        , 0.        , 0.02825322, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.042051  , 0.        , 0.        , 0.04620128, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.05782947, 0.03282119,
       0.04620128, 0.        , 0.        , 0.        , 0.        ,
       0.05782947, 0.05782947, 0.        , 0.        , 0.        ,
       0.        , 0.03550235, 0.        , 0.        , 0.        ,
       0.        , 0.042051  , 0.        , 0.        , 0.        ,
       0.        , 0.05128082, 0.        , 0.10256164, 0.        ,
       0.09846357, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.05782947, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.04620128, 0.        , 0.05128082, 0.        , 0.        ,
       0.        , 0.        , 0.03282119, 0.03854199, 0.        ,
       0.05782947, 0.15384245, 0.        , 0.25230603, 0.        ,
       0.        , 0.        , 0.        , 0.05782947, 0.07100469,
       0.        , 0.09240257, 0.        , 0.        , 0.        ,
       0.05128082, 0.        , 0.        , 0.05782947, 0.        ,
       0.14200939, 0.        , 0.03282119, 0.07100469, 0.05128082,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.05782947, 0.        ,
       0.12169126, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.05782947, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.05128082, 0.03550235, 0.        , 0.        , 0.05782947,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.05782947, 0.05782947, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.05128082, 0.05782947, 0.        ,
       0.        , 0.        , 0.11565895, 0.06084563, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.07100469,
       0.        , 0.05782947, 0.        , 0.        , 0.        ,
       0.05128082, 0.05782947, 0.        , 0.        , 0.11565895,
       0.04620128, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.17348842, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.15211407, 0.04620128, 0.05128082, 0.        ,
       0.        , 0.11565895, 0.05782947, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.03854199, 0.05128082,
       0.09240257, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.05782947, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.05782947, 0.04620128,
       0.05782947, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.04620128, 0.        , 0.        ,
       0.        , 0.        , 0.05782947, 0.        , 0.        ,
       0.08410201, 0.        , 0.        , 0.        , 0.        ,
       0.03854199, 0.042051  , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.05650644,
       0.09240257, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.05650644, 0.05128082, 0.        , 0.        ,
       0.        , 0.        , 0.03854199, 0.        , 0.        ,
       0.        , 0.05128082, 0.        , 0.        , 0.        ,
       0.03550235, 0.        , 0.02825322, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.04620128,
       0.        , 0.        , 0.09846357, 0.        , 0.        ,
       0.        , 0.        , 0.12169126, 0.03282119, 0.        ,
       0.12169126, 0.        , 0.05782947, 0.05782947, 0.05128082,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.07100469, 0.        , 0.05782947, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.042051  , 0.06564238, 0.05128082, 0.        ,
       0.10256164, 0.        , 0.        , 0.        , 0.05128082,
       0.        , 0.        , 0.05782947, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.17348842, 0.        , 0.08475966, 0.        , 0.        ,
       0.        , 0.05782947, 0.05782947, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.11301288, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.05782947,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.05782947, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.20512327, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.07708398, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.03550235, 0.03042281, 0.        , 0.        , 0.        ,
       0.03042281, 0.        , 0.05128082, 0.05782947])

In [14]:
# Create a dataframe for TF/IDF
tfidf_df = pd.DataFrame(tfidf_dt_matrix.toarray(), columns=tfidf_vectorizer.get_feature_names_out())
#tfidf_df

In [15]:
# Update the terms dataframe with TF/IDF
for idx in terms_df.index:
    tfidf = dict(tfidf_df.loc[idx].sort_values(ascending=False).head(10))
    #print(counts)
    terms_df.at[idx,'tfidf'] = list(tfidf.keys()) 

terms_df

,title,count,tfidf,lda,nmf
0,Winter Olympics 2026: what you need to know if...,"[2026, ice, new, athletes, aedt, day, ski, wat...","[ice, aedt, watch, 2026, athletes, table, moun...",NaN,NaN
1,Australia’s upward trajectory slips off course...,"[team, anthony, final, competition, medals, tr...","[anthony, team, competition, air, snowboarder,...",NaN,NaN
2,‘Even more special’: Jakara Anthony dusts off ...,"[moguls, anthony, dual, single, event, just, f...","[moguls, anthony, dual, single, course, event,...",NaN,NaN
3,A part-time job and DJ gigs helped Lara Hamilt...,"[hamilton, ski, skimo, just, running, says, sk...","[hamilton, skimo, running, ski, mountaineering...",NaN,NaN
4,Valentino Guseli’s unexpected big air dream en...,"[final, guseli, said, time, score, air, best, ...","[guseli, final, air, 50, landing, score, said,...",NaN,NaN
5,From Bradbury to Bright: five of Australia’s b...,"[bradbury, event, high, bronze, skiing, way, s...","[bradbury, smith, high, bronze, city, event, s...",NaN,NaN
6,Australia’s youngest Winter Olympian Indra Bro...,"[just, indra, brown, time, says, want, halfpip...","[indra, want, just, brown, says, ve, time, fam...",NaN,NaN
7,How did Australia – better known for its beach...,"[medals, moguls, sports, team, funding, olympi...","[medals, moguls, funding, aerial, sports, olym...",NaN,NaN
8,‘Put the blinders on’: how Jakara Anthony can ...,"[anthony, moguls, says, ski, win, field, seaso...","[anthony, says, moguls, field, makes, woman, s...",NaN,NaN
9,Ice in his veins: Australian skier Cooper Wood...,"[woods, said, just, cooper, lot, final, win, t...","[woods, cooper, said, just, lot, perisher, nsw...",NaN,NaN
10,Australia’s Jakara Anthony clinches first ever...,"[anthony, second, moguls, james, halfpipe, tra...","[anthony, ok, second, peel, james, moguls, sin...",NaN,NaN
11,Morning Mail: Lake Cargelligo suspect’s past r...,"[morning, history, including, new, government,...","[morning, children, government, history, peopl...",NaN,NaN
12,"Morning Mail: Taylor sets up Liberal spill, mi...","[morning, smith, shock, australians, today, ab...","[morning, shock, smith, today, australians, se...",NaN,NaN

In [16]:
# Compare Counts and TF/IDF

# Sample 5 random articles
samples = random.sample(range(0,len(terms_df)),5)

for sample in samples:
    doc = terms_df.iloc[sample]
    print(f"[{sample}] {doc['title']}")
    print("\t>> Counts:\t",doc['count'])
    print("\t>> TFIDF:\t",doc['tfidf'])
    print()

[12] Morning Mail: Taylor sets up Liberal spill, millionaires call for higher taxes, Australia’s skiing hope slips up [2026-02-11T19:40:12Z]
	>> Counts:	 ['morning', 'smith', 'shock', 'australians', 'today', 'able', 'sydney', 'set', 'action', 'week']
	>> TFIDF:	 ['morning', 'shock', 'smith', 'today', 'australians', 'set', 'cabinet', 'shadow', 'update', 'queensland']

[2] ‘Even more special’: Jakara Anthony dusts off Winter Olympics heartbreak for historic triumph [2026-02-15T01:32:16Z]
	>> Counts:	 ['moguls', 'anthony', 'dual', 'single', 'event', 'just', 'final', 'time', 'course', 'lot']
	>> TFIDF:	 ['moguls', 'anthony', 'dual', 'single', 'course', 'event', 'just', 'needed', 'special', 'help']

[10] Australia’s Jakara Anthony clinches first ever dual moguls Olympics gold [2026-02-14T11:40:32Z]
	>> Counts:	 ['anthony', 'second', 'moguls', 'james', 'halfpipe', 'training', 'event', 'won', 'peel', 'ok']
	>> TFIDF:	 ['anthony', 'ok', 'second', 'peel', 'james', 'moguls', 'singles', 'beating', 'ruptured', 'likely']

[6] Australia’s youngest Winter Olympian Indra Brown: ‘I just love the feeling of flying’ | Martin Pegan [2026-02-01T14:00:34Z]
	>> Counts:	 ['just', 'indra', 'brown', 'time', 'says', 'want', 'halfpipe', 've', 'family', 'ski']
	>> TFIDF:	 ['indra', 'want', 'just', 'brown', 'says', 've', 'time', 'family', 'trick', 'landing']

[9] Ice in his veins: Australian skier Cooper Woods embraces pressure to realise Winter Olympic dream [2026-02-13T02:17:26Z]
	>> Counts:	 ['woods', 'said', 'just', 'cooper', 'lot', 'final', 'win', 'time', 'perisher', 'people']
	>> TFIDF:	 ['woods', 'cooper', 'said', 'just', 'lot', 'perisher', 'nsw', 'man', 've', 'family']

### Topic modelling with Latent Dirichlet Allocation (LDA)

[LDA](https://en.wikipedia.org/wiki/Latent_Dirichlet_allocation) is an algorithm for obtaining *topics* (a list of terms) from a document-term matrix. It is a generative probabilistic approach to *decomposition* of the document-term matrix into 2 factor matrices: document-topic and topic-term.

![img](https://editor.analyticsvidhya.com/uploads/26864dtm.JPG)

*Source: [Analytics Vidhya](https://www.analyticsvidhya.com/blog/2021/06/part-2-topic-modeling-and-latent-dirichlet-allocation-lda-using-gensim-and-sklearn/)*

The LDA model requires the number of topics to be set in advance. As it is a generative model, it also runs over a number of iterations. These values usually need to be experimented with to obtain quality topics.

In [17]:
# Set number of topics
num_topics = 15
# Set max number of iteractions
max_iterations = 20

# Create the model
lda_model = LatentDirichletAllocation(n_components=num_topics,max_iter=max_iterations,learning_method='online')

# Fit the model to the data, and use the model to transform the data (do the decomposition)
doc_topic_matrix = lda_model.fit_transform(count_dt_matrix)

# Obtain the topics
topic_term_matrix = lda_model.components_

#### View the topics

In [18]:
# Get the topics and their terms
lda_topic_dict = {}
for index, topic in enumerate(topic_term_matrix):
    zipped = zip(feature_names, topic)
    top_terms=dict(sorted(zipped, key = lambda t: t[1], reverse=True)[:10])
    #print(top_terms)
    top_terms_list= {key : round(top_terms[key], 4) for key in top_terms.keys()}
    lda_topic_dict[f"topic_{index}"] = top_terms_list

# Print the topics with their terms    
for k,v in lda_topic_dict.items():
    print(k)
    print(v)
    print()

topic_0
{'anthony': np.float64(0.1747), 'moguls': np.float64(0.1659), 'medals': np.float64(0.1522), 'rounds': np.float64(0.1492), 'support': np.float64(0.1491), 'sports': np.float64(0.1491), 'northern': np.float64(0.1478), 'judges': np.float64(0.1478), 'haul': np.float64(0.1476), 'yellow': np.float64(0.147)}

topic_1
{'just': np.float64(17.7741), 'time': np.float64(13.0911), 'skiing': np.float64(12.1719), 'indra': np.float64(12.1524), 'medals': np.float64(11.2192), 'team': np.float64(10.3238), 'brown': np.float64(9.3795), 'halfpipe': np.float64(9.3725), 'ski': np.float64(9.3684), 'moguls': np.float64(8.4763)}

topic_2
{'anthony': np.float64(0.2468), 'moguls': np.float64(0.2164), 'final': np.float64(0.185), 'event': np.float64(0.1745), 'single': np.float64(0.1744), 'big': np.float64(0.167), 'win': np.float64(0.1659), 'dual': np.float64(0.1637), 'team': np.float64(0.1636), 'just': np.float64(0.1623)}

topic_3
{'bradbury': np.float64(0.2197), 'event': np.float64(0.2127), 'high': np.float64(0.186), 'years': np.float64(0.1853), 'later': np.float64(0.18), 'way': np.float64(0.1787), 'ski': np.float64(0.1745), 'city': np.float64(0.1732), 'short': np.float64(0.173), 'breakthrough': np.float64(0.1714)}

topic_4
{'just': np.float64(0.1799), 'hamilton': np.float64(0.1674), 'woods': np.float64(0.1659), 'skiing': np.float64(0.1632), 'topalovic': np.float64(0.1629), 've': np.float64(0.1559), 'said': np.float64(0.1542), 'running': np.float64(0.1506), 'don': np.float64(0.1501), 'snow': np.float64(0.1497)}

topic_5
{'final': np.float64(10.3804), 'guseli': np.float64(8.5106), 'said': np.float64(4.7852), 'time': np.float64(3.8611), 'big': np.float64(3.8603), 'air': np.float64(3.8575), 'best': np.float64(3.8546), 'score': np.float64(3.8543), '50': np.float64(3.8473), 'round': np.float64(3.8448)}

topic_6
{'just': np.float64(0.1682), 'funding': np.float64(0.1555), 'country': np.float64(0.155), 'week': np.float64(0.1518), 'live': np.float64(0.1515), 'host': np.float64(0.1515), 'change': np.float64(0.1514), 'face': np.float64(0.1504), 'follow': np.float64(0.1502), 'runs': np.float64(0.1486)}

topic_7
{'anthony': np.float64(26.939), 'moguls': np.float64(22.3523), 'second': np.float64(10.3313), 'dual': np.float64(8.4629), 'event': np.float64(8.4608), 'win': np.float64(8.4583), 'course': np.float64(7.5468), 'time': np.float64(7.5331), 'single': np.float64(7.5193), 'final': np.float64(6.6549)}

topic_8
{'state': np.float64(0.1517), 'morning': np.float64(0.1511), 'host': np.float64(0.1496), 'northern': np.float64(0.1469), 'national': np.float64(0.1466), 'climate': np.float64(0.146), 'hope': np.float64(0.1459), 'tougher': np.float64(0.1457), '2010': np.float64(0.1457), 'chasing': np.float64(0.1449)}

topic_9
{'morning': np.float64(4.8454), 'government': np.float64(3.2674), 'people': np.float64(3.2663), 'day': np.float64(3.1082), 'children': np.float64(3.1071), 'new': np.float64(2.9563), 'including': np.float64(2.8946), 'history': np.float64(2.88), 'crossword': np.float64(2.5127), 'update': np.float64(2.5053)}

topic_10
{'woods': np.float64(10.3191), 'just': np.float64(6.6421), 'said': np.float64(6.6195), 'skiing': np.float64(5.6483), 'bradbury': np.float64(5.5832), 'lot': np.float64(4.7653), 'win': np.float64(4.7644), 'final': np.float64(4.7509), 'snow': np.float64(4.7485), 'cooper': np.float64(4.7465)}

topic_11
{'alisa': np.float64(0.1496), 'teammates': np.float64(0.1464), 'weekday': np.float64(0.1464), 'event': np.float64(0.1462), 'mogul': np.float64(0.1459), 'months': np.float64(0.1457), 'seven': np.float64(0.1447), 'anthony': np.float64(0.1441), 'achieve': np.float64(0.1436), 'attempt': np.float64(0.1432)}

topic_12
{'hamilton': np.float64(11.2106), 'ski': np.float64(9.4212), 'anthony': np.float64(6.7725), 'team': np.float64(6.6689), 'just': np.float64(6.6629), 'competition': np.float64(6.617), 'running': np.float64(6.5981), 'skimo': np.float64(6.5861), 'says': np.float64(5.75), 'skiing': np.float64(4.7939)}

topic_13
{'skiing': np.float64(0.2125), 'athletes': np.float64(0.1946), 'ice': np.float64(0.1901), 'bradbury': np.float64(0.1841), 'snowboard': np.float64(0.1836), 'new': np.float64(0.1824), '2026': np.float64(0.1804), 'aedt': np.float64(0.1729), 'silver': np.float64(0.1705), 'bronze': np.float64(0.164)}

topic_14
{'just': np.float64(0.1993), 'indra': np.float64(0.192), 'time': np.float64(0.1848), 'final': np.float64(0.178), 'high': np.float64(0.171), 'run': np.float64(0.1706), 'says': np.float64(0.1681), 'halfpipe': np.float64(0.1675), 'ski': np.float64(0.1666), 'brown': np.float64(0.1663)}

#### List of topics for each document

In [19]:
doc_topic_matrix

array([[2.64550266e-04, 9.96296294e-01, 2.64550267e-04, 2.64550267e-04,
        2.64550266e-04, 2.64550778e-04, 2.64550266e-04, 2.64550667e-04,
        2.64550266e-04, 2.64550504e-04, 2.64550584e-04, 2.64550266e-04,
        2.64551248e-04, 2.64550268e-04, 2.64550267e-04],
       [2.29095076e-04, 2.29095556e-04, 2.29095077e-04, 2.29095076e-04,
        2.29095076e-04, 2.29095548e-04, 2.29095076e-04, 2.29095607e-04,
        2.29095076e-04, 2.29095256e-04, 2.29095417e-04, 2.29095076e-04,
        9.96792667e-01, 2.29095076e-04, 2.29095076e-04],
       [2.76625175e-04, 2.76625810e-04, 2.76625176e-04, 2.76625175e-04,
        2.76625175e-04, 2.76625492e-04, 2.76625174e-04, 9.96127245e-01,
        2.76625174e-04, 2.76625433e-04, 2.76625703e-04, 2.76625174e-04,
        2.76625684e-04, 2.76625175e-04, 2.76625175e-04],
       [2.86123034e-04, 2.86123497e-04, 2.86123035e-04, 2.86123035e-04,
        2.86123035e-04, 2.86123297e-04, 2.86123034e-04, 2.86123398e-04,
        2.86123034e-04, 2.86123306e-04, 2.86123456e-04, 2.86123034e-04,
        9.95994276e-01, 2.86123035e-04, 2.86123035e-04],
       [2.71002711e-04, 2.71003026e-04, 2.71002711e-04, 2.71002711e-04,
        2.71002711e-04, 9.96205961e-01, 2.71002711e-04, 2.71003044e-04,
        2.71002711e-04, 2.71002849e-04, 2.71002971e-04, 2.71002711e-04,
        2.71003028e-04, 2.71002711e-04, 2.71002711e-04],
       [2.84900286e-04, 2.84900808e-04, 2.84900287e-04, 2.84900289e-04,
        2.84900286e-04, 2.84900508e-04, 2.84900286e-04, 2.84900653e-04,
        2.84900286e-04, 2.84900481e-04, 9.96011394e-01, 2.84900286e-04,
        2.84900716e-04, 2.84900287e-04, 2.84900287e-04],
       [2.29095076e-04, 9.96792667e-01, 2.29095076e-04, 2.29095077e-04,
        2.29095076e-04, 2.29095372e-04, 2.29095076e-04, 2.29095505e-04,
        2.29095076e-04, 2.29095265e-04, 2.29095476e-04, 2.29095076e-04,
        2.29095558e-04, 2.29095076e-04, 2.29095077e-04],
       [2.27531287e-04, 9.96814560e-01, 2.27531288e-04, 2.27531288e-04,
        2.27531287e-04, 2.27531626e-04, 2.27531287e-04, 2.27531877e-04,
        2.27531287e-04, 2.27531539e-04, 2.27531912e-04, 2.27531287e-04,
        2.27531713e-04, 2.27531288e-04, 2.27531287e-04],
       [2.38095239e-04, 2.38095610e-04, 2.38095240e-04, 2.38095240e-04,
        2.38095239e-04, 2.38095474e-04, 2.38095239e-04, 9.96666665e-01,
        2.38095239e-04, 2.38095361e-04, 2.38095602e-04, 2.38095239e-04,
        2.38095578e-04, 2.38095240e-04, 2.38095240e-04],
       [2.64550266e-04, 2.64550707e-04, 2.64550266e-04, 2.64550266e-04,
        2.64550266e-04, 2.64550673e-04, 2.64550266e-04, 2.64551479e-04,
        2.64550266e-04, 2.64550463e-04, 9.96296294e-01, 2.64550266e-04,
        2.64550658e-04, 2.64550266e-04, 2.64550266e-04],
       [2.78940029e-04, 2.78940503e-04, 2.78940030e-04, 2.78940030e-04,
        2.78940029e-04, 2.78940540e-04, 2.78940029e-04, 9.96094838e-01,
        2.78940029e-04, 2.78940272e-04, 2.78940415e-04, 2.78940029e-04,
        2.78940467e-04, 2.78940030e-04, 2.78940030e-04],
       [2.75482095e-04, 2.75482422e-04, 2.75482095e-04, 2.75482095e-04,
        2.75482095e-04, 2.75482317e-04, 2.75482095e-04, 2.75482351e-04,
        2.75482095e-04, 9.96143249e-01, 2.75482293e-04, 2.75482095e-04,
        2.75482339e-04, 2.75482095e-04, 2.75482095e-04],
       [2.61437911e-04, 7.03683912e-01, 2.61437912e-04, 2.61437911e-04,
        2.61437911e-04, 2.61438217e-04, 2.61437912e-04, 2.61438399e-04,
        2.61437911e-04, 2.92917393e-01, 2.61438321e-04, 2.61437911e-04,
        2.61438322e-04, 2.61437911e-04, 2.61437911e-04]])

#### Update the terms matrix

In [20]:
for idx,topic in enumerate(doc_topic_matrix):
    topic_num = topic.argmax()
    top_topic = lda_topic_dict[f"topic_{topic_num}"]
    terms_df.at[idx,'lda'] = list(top_topic.keys())

terms_df

,title,count,tfidf,lda,nmf
0,Winter Olympics 2026: what you need to know if...,"[2026, ice, new, athletes, aedt, day, ski, wat...","[ice, aedt, watch, 2026, athletes, table, moun...","[just, time, skiing, indra, medals, team, brow...",NaN
1,Australia’s upward trajectory slips off course...,"[team, anthony, final, competition, medals, tr...","[anthony, team, competition, air, snowboarder,...","[hamilton, ski, anthony, team, just, competiti...",NaN
2,‘Even more special’: Jakara Anthony dusts off ...,"[moguls, anthony, dual, single, event, just, f...","[moguls, anthony, dual, single, course, event,...","[anthony, moguls, second, dual, event, win, co...",NaN
3,A part-time job and DJ gigs helped Lara Hamilt...,"[hamilton, ski, skimo, just, running, says, sk...","[hamilton, skimo, running, ski, mountaineering...","[hamilton, ski, anthony, team, just, competiti...",NaN
4,Valentino Guseli’s unexpected big air dream en...,"[final, guseli, said, time, score, air, best, ...","[guseli, final, air, 50, landing, score, said,...","[final, guseli, said, time, big, air, best, sc...",NaN
5,From Bradbury to Bright: five of Australia’s b...,"[bradbury, event, high, bronze, skiing, way, s...","[bradbury, smith, high, bronze, city, event, s...","[woods, just, said, skiing, bradbury, lot, win...",NaN
6,Australia’s youngest Winter Olympian Indra Bro...,"[just, indra, brown, time, says, want, halfpip...","[indra, want, just, brown, says, ve, time, fam...","[just, time, skiing, indra, medals, team, brow...",NaN
7,How did Australia – better known for its beach...,"[medals, moguls, sports, team, funding, olympi...","[medals, moguls, funding, aerial, sports, olym...","[just, time, skiing, indra, medals, team, brow...",NaN
8,‘Put the blinders on’: how Jakara Anthony can ...,"[anthony, moguls, says, ski, win, field, seaso...","[anthony, says, moguls, field, makes, woman, s...","[anthony, moguls, second, dual, event, win, co...",NaN
9,Ice in his veins: Australian skier Cooper Wood...,"[woods, said, just, cooper, lot, final, win, t...","[woods, cooper, said, just, lot, perisher, nsw...","[woods, just, said, skiing, bradbury, lot, win...",NaN
10,Australia’s Jakara Anthony clinches first ever...,"[anthony, second, moguls, james, halfpipe, tra...","[anthony, ok, second, peel, james, moguls, sin...","[anthony, moguls, second, dual, event, win, co...",NaN
11,Morning Mail: Lake Cargelligo suspect’s past r...,"[morning, history, including, new, government,...","[morning, children, government, history, peopl...","[morning, government, people, day, children, n...",NaN
12,"Morning Mail: Taylor sets up Liberal spill, mi...","[morning, smith, shock, australians, today, ab...","[morning, shock, smith, today, australians, se...","[just, time, skiing, indra, medals, team, brow...",NaN

#### Compare approaches

In [21]:
# Sample 5 random articles
samples = random.sample(range(0,len(terms_df)),5)

for sample in samples:
    doc = terms_df.iloc[sample]
    print(f"[{sample}] {doc['title']}")
    print("\t>> Counts:\t",doc['count'])
    print("\t>> TFIDF:\t",doc['tfidf'])
    print("\t>> LDA:\t\t",doc['lda'])
    print()

[12] Morning Mail: Taylor sets up Liberal spill, millionaires call for higher taxes, Australia’s skiing hope slips up [2026-02-11T19:40:12Z]
	>> Counts:	 ['morning', 'smith', 'shock', 'australians', 'today', 'able', 'sydney', 'set', 'action', 'week']
	>> TFIDF:	 ['morning', 'shock', 'smith', 'today', 'australians', 'set', 'cabinet', 'shadow', 'update', 'queensland']
	>> LDA:		 ['just', 'time', 'skiing', 'indra', 'medals', 'team', 'brown', 'halfpipe', 'ski', 'moguls']

[6] Australia’s youngest Winter Olympian Indra Brown: ‘I just love the feeling of flying’ | Martin Pegan [2026-02-01T14:00:34Z]
	>> Counts:	 ['just', 'indra', 'brown', 'time', 'says', 'want', 'halfpipe', 've', 'family', 'ski']
	>> TFIDF:	 ['indra', 'want', 'just', 'brown', 'says', 've', 'time', 'family', 'trick', 'landing']
	>> LDA:		 ['just', 'time', 'skiing', 'indra', 'medals', 'team', 'brown', 'halfpipe', 'ski', 'moguls']

[10] Australia’s Jakara Anthony clinches first ever dual moguls Olympics gold [2026-02-14T11:40:32Z]
	>> Counts:	 ['anthony', 'second', 'moguls', 'james', 'halfpipe', 'training', 'event', 'won', 'peel', 'ok']
	>> TFIDF:	 ['anthony', 'ok', 'second', 'peel', 'james', 'moguls', 'singles', 'beating', 'ruptured', 'likely']
	>> LDA:		 ['anthony', 'moguls', 'second', 'dual', 'event', 'win', 'course', 'time', 'single', 'final']

[11] Morning Mail: Lake Cargelligo suspect’s past revealed, supermarket ‘per unit’ prices under scrutiny, shark attack spike [2026-02-18T20:23:22Z]
	>> Counts:	 ['morning', 'history', 'including', 'new', 'government', 'people', 'day', 'children', 'crossword', 'asian']
	>> TFIDF:	 ['morning', 'children', 'government', 'history', 'people', 'update', 'reports', 'allegedly', 'uk', 'asian']
	>> LDA:		 ['morning', 'government', 'people', 'day', 'children', 'new', 'including', 'history', 'crossword', 'update']

[3] A part-time job and DJ gigs helped Lara Hamilton reach the Winter Olympics. Now she wants to put Australia on the map [2026-02-17T14:00:15Z]
	>> Counts:	 ['hamilton', 'ski', 'skimo', 'just', 'running', 'says', 'skiing', 'going', 'mountaineering', 'good']
	>> TFIDF:	 ['hamilton', 'skimo', 'running', 'ski', 'mountaineering', 'says', 'just', 'skis', 'results', 'skiing']
	>> LDA:		 ['hamilton', 'ski', 'anthony', 'team', 'just', 'competition', 'running', 'skimo', 'says', 'skiing']

### Topic modelling with Non-negative Matrix Factorisation (NMF)


[NMF](https://en.wikipedia.org/wiki/Latent_Dirichlet_allocation) is a different algorithm for obtaining *topics* (a list of terms) from a document-term matrix. It also factorises the document-term matrix into 2 factor matrices: document-topic and topic-term.

In [22]:
# Set the number of topics
num_topics = 15

# Create the model
nmf_model = NMF(n_components=num_topics,init='random',beta_loss='frobenius')

# Fit the model to the data and use it to transform the data
doc_topic_nmf = nmf_model.fit_transform(tfidf_dt_matrix)

topic_term_nmf = nmf_model.components_

In [23]:
# Get the topics and their terms
nmf_topic_dict = {}
for index, topic in enumerate(topic_term_nmf):
    zipped = zip(feature_names, topic)
    top_terms=dict(sorted(zipped, key = lambda t: t[1], reverse=True)[:10])
    #print(top_terms)
    top_terms_list= {key : round(top_terms[key], 4) for key in top_terms.keys()}
    nmf_topic_dict[f"topic_{index}"] = top_terms_list

# Print the topics with their terms    
for k,v in nmf_topic_dict.items():
    print(k)
    print(v)
    print()

topic_0
{'moguls': np.float64(1.6981), 'anthony': np.float64(1.5484), 'dual': np.float64(0.9978), 'single': np.float64(0.9937), 'course': np.float64(0.61), 'event': np.float64(0.6096), 'just': np.float64(0.5211), 'help': np.float64(0.5001), 'needed': np.float64(0.5001), 'rounds': np.float64(0.5001)}

topic_1
{'anthony': np.float64(0.6397), 'ok': np.float64(0.4831), 'second': np.float64(0.472), 'peel': np.float64(0.4284), 'james': np.float64(0.3954), 'moguls': np.float64(0.3388), 'beating': np.float64(0.3221), 'ruptured': np.float64(0.3221), 'singles': np.float64(0.3221), 'likely': np.float64(0.3221)}

topic_2
{'hamilton': np.float64(1.4704), 'skimo': np.float64(0.9357), 'running': np.float64(0.8298), 'ski': np.float64(0.5626), 'mountaineering': np.float64(0.5347), 'says': np.float64(0.4924), 'just': np.float64(0.4923), 'results': np.float64(0.3556), 'skis': np.float64(0.3556), 'skiing': np.float64(0.3516)}

topic_3
{'indra': np.float64(2.0761), 'want': np.float64(1.5592), 'just': np.float64(1.5038), 'brown': np.float64(1.4533), 'says': np.float64(0.9572), 've': np.float64(0.9217), 'time': np.float64(0.8887), 'family': np.float64(0.8304), 'landing': np.float64(0.7796), 'trick': np.float64(0.7796)}

topic_4
{'guseli': np.float64(1.27), 'team': np.float64(0.9357), 'big': np.float64(0.7899), 'qualifying': np.float64(0.7173), 'run': np.float64(0.6997), 'final': np.float64(0.5624), 'great': np.float64(0.5207), 'far': np.float64(0.51), 'saturday': np.float64(0.4836), 'mark': np.float64(0.4547)}

topic_5
{'anthony': np.float64(1.1712), 'moguls': np.float64(1.1144), 'win': np.float64(0.5196), 'single': np.float64(0.4835), 'just': np.float64(0.4776), 'skier': np.float64(0.4248), 'athlete': np.float64(0.4034), 'course': np.float64(0.3716), 'sports': np.float64(0.341), 'time': np.float64(0.2957)}

topic_6
{'says': np.float64(0.6144), 'field': np.float64(0.5916), 'season': np.float64(0.4665), 'woman': np.float64(0.4546), 'january': np.float64(0.4146), '20': np.float64(0.4006), 'wins': np.float64(0.3995), 'anthony': np.float64(0.3958), 'makes': np.float64(0.3642), 'consciousness': np.float64(0.3336)}

topic_7
{'morning': np.float64(0.6349), 'children': np.float64(0.4762), 'government': np.float64(0.4334), 'people': np.float64(0.4334), 'history': np.float64(0.4334), 'crossword': np.float64(0.3974), 'liberal': np.float64(0.3974), 'update': np.float64(0.3974), 'according': np.float64(0.3974), 'allegedly': np.float64(0.3974)}

topic_8
{'ice': np.float64(1.0029), 'aedt': np.float64(0.9195), 'watch': np.float64(0.8154), '2026': np.float64(0.7421), 'athletes': np.float64(0.7056), 'mountaineering': np.float64(0.6896), 'table': np.float64(0.6896), 'hours': np.float64(0.6115), 'new': np.float64(0.6047), 'italy': np.float64(0.5645)}

topic_9
{'medals': np.float64(0.9706), 'moguls': np.float64(0.8439), 'funding': np.float64(0.8392), 'aerial': np.float64(0.8187), 'sports': np.float64(0.7841), 'olympian': np.float64(0.7681), 'success': np.float64(0.6153), 'federal': np.float64(0.614), 've': np.float64(0.614), 'snow': np.float64(0.5668)}

topic_10
{'morning': np.float64(0.5312), 'shock': np.float64(0.4987), 'smith': np.float64(0.4987), 'today': np.float64(0.3984), 'australians': np.float64(0.3626), 'appeal': np.float64(0.3325), 'cabinet': np.float64(0.3325), 'game': np.float64(0.3325), 'host': np.float64(0.3325), 'lead': np.float64(0.3325)}

topic_11
{'anthony': np.float64(0.5869), 'competition': np.float64(0.4535), 'snowboarder': np.float64(0.4432), '000': np.float64(0.4432), 'air': np.float64(0.4427), 'compete': np.float64(0.393), 'morning': np.float64(0.3541), 'training': np.float64(0.3354), 'days': np.float64(0.3223), 'team': np.float64(0.3122)}

topic_12
{'woods': np.float64(1.6812), 'cooper': np.float64(0.7642), 'said': np.float64(0.76), 'just': np.float64(0.7045), 'lot': np.float64(0.6375), 'man': np.float64(0.5089), 'nsw': np.float64(0.5089), 'perisher': np.float64(0.5089), 've': np.float64(0.5089), 'family': np.float64(0.4585)}

topic_13
{'bradbury': np.float64(1.8237), 'smith': np.float64(0.9119), 'high': np.float64(0.8841), 'bronze': np.float64(0.8841), 'city': np.float64(0.8086), 'event': np.float64(0.7425), 'later': np.float64(0.7285), 'nation': np.float64(0.7285), 'national': np.float64(0.7285), 'speed': np.float64(0.7285)}

topic_14
{'guseli': np.float64(1.323), 'final': np.float64(0.9921), 'air': np.float64(0.8824), '50': np.float64(0.7832), 'landing': np.float64(0.6624), 'score': np.float64(0.6423), 'said': np.float64(0.6266), 'round': np.float64(0.5887), 'medical': np.float64(0.5871), 'competitor': np.float64(0.4416)}

#### Update the terms matrix

In [24]:
for idx,topic in enumerate(doc_topic_nmf):
    topic_num = topic.argmax()
    top_topic = nmf_topic_dict[f"topic_{topic_num}"]
    terms_df.at[idx,'nmf'] = list(top_topic.keys())

terms_df

,title,count,tfidf,lda,nmf
0,Winter Olympics 2026: what you need to know if...,"[2026, ice, new, athletes, aedt, day, ski, wat...","[ice, aedt, watch, 2026, athletes, table, moun...","[just, time, skiing, indra, medals, team, brow...","[ice, aedt, watch, 2026, athletes, mountaineer..."
1,Australia’s upward trajectory slips off course...,"[team, anthony, final, competition, medals, tr...","[anthony, team, competition, air, snowboarder,...","[hamilton, ski, anthony, team, just, competiti...","[anthony, competition, snowboarder, 000, air, ..."
2,‘Even more special’: Jakara Anthony dusts off ...,"[moguls, anthony, dual, single, event, just, f...","[moguls, anthony, dual, single, course, event,...","[anthony, moguls, second, dual, event, win, co...","[moguls, anthony, dual, single, course, event,..."
3,A part-time job and DJ gigs helped Lara Hamilt...,"[hamilton, ski, skimo, just, running, says, sk...","[hamilton, skimo, running, ski, mountaineering...","[hamilton, ski, anthony, team, just, competiti...","[hamilton, skimo, running, ski, mountaineering..."
4,Valentino Guseli’s unexpected big air dream en...,"[final, guseli, said, time, score, air, best, ...","[guseli, final, air, 50, landing, score, said,...","[final, guseli, said, time, big, air, best, sc...","[guseli, final, air, 50, landing, score, said,..."
5,From Bradbury to Bright: five of Australia’s b...,"[bradbury, event, high, bronze, skiing, way, s...","[bradbury, smith, high, bronze, city, event, s...","[woods, just, said, skiing, bradbury, lot, win...","[bradbury, smith, high, bronze, city, event, l..."
6,Australia’s youngest Winter Olympian Indra Bro...,"[just, indra, brown, time, says, want, halfpip...","[indra, want, just, brown, says, ve, time, fam...","[just, time, skiing, indra, medals, team, brow...","[indra, want, just, brown, says, ve, time, fam..."
7,How did Australia – better known for its beach...,"[medals, moguls, sports, team, funding, olympi...","[medals, moguls, funding, aerial, sports, olym...","[just, time, skiing, indra, medals, team, brow...","[medals, moguls, funding, aerial, sports, olym..."
8,‘Put the blinders on’: how Jakara Anthony can ...,"[anthony, moguls, says, ski, win, field, seaso...","[anthony, says, moguls, field, makes, woman, s...","[anthony, moguls, second, dual, event, win, co...","[says, field, season, woman, january, 20, wins..."
9,Ice in his veins: Australian skier Cooper Wood...,"[woods, said, just, cooper, lot, final, win, t...","[woods, cooper, said, just, lot, perisher, nsw...","[woods, just, said, skiing, bradbury, lot, win...","[woods, cooper, said, just, lot, man, nsw, per..."
10,Australia’s Jakara Anthony clinches first ever...,"[anthony, second, moguls, james, halfpipe, tra...","[anthony, ok, second, peel, james, moguls, sin...","[anthony, moguls, second, dual, event, win, co...","[anthony, ok, second, peel, james, moguls, bea..."
11,Morning Mail: Lake Cargelligo suspect’s past r...,"[morning, history, including, new, government,...","[morning, children, government, history, peopl...","[morning, government, people, day, children, n...","[morning, children, government, people, histor..."
12,"Morning Mail: Taylor sets up Liberal spill, mi...","[morning, smith, shock, australians, today, ab...","[morning, shock, smith, today, australians, se...","[just, time, skiing, indra, medals, team, brow...","[morning, shock, smith, today, australians, ap..."

### Compare approaches

In [25]:
# Sample 5 random articles
samples = random.sample(range(0,len(terms_df)),5)

for sample in samples:
    doc = terms_df.iloc[sample]
    print(f"[{sample}] {doc['title']}")
    print("\t>> Counts:\t",doc['count'])
    print("\t>> TFIDF:\t",doc['tfidf'])
    print("\t>> LDA:\t\t",doc['lda'])
    print("\t>> NMF:\t\t",doc['nmf'])
    print()

[0] Winter Olympics 2026: what you need to know if following from Australia [2026-02-02T14:00:10Z]
	>> Counts:	 ['2026', 'ice', 'new', 'athletes', 'aedt', 'day', 'ski', 'watch', 'skiing', 'time']
	>> TFIDF:	 ['ice', 'aedt', 'watch', '2026', 'athletes', 'table', 'mountaineering', 'hours', 'new', 'italy']
	>> LDA:		 ['just', 'time', 'skiing', 'indra', 'medals', 'team', 'brown', 'halfpipe', 'ski', 'moguls']
	>> NMF:		 ['ice', 'aedt', 'watch', '2026', 'athletes', 'mountaineering', 'table', 'hours', 'new', 'italy']

[6] Australia’s youngest Winter Olympian Indra Brown: ‘I just love the feeling of flying’ | Martin Pegan [2026-02-01T14:00:34Z]
	>> Counts:	 ['just', 'indra', 'brown', 'time', 'says', 'want', 'halfpipe', 've', 'family', 'ski']
	>> TFIDF:	 ['indra', 'want', 'just', 'brown', 'says', 've', 'time', 'family', 'trick', 'landing']
	>> LDA:		 ['just', 'time', 'skiing', 'indra', 'medals', 'team', 'brown', 'halfpipe', 'ski', 'moguls']
	>> NMF:		 ['indra', 'want', 'just', 'brown', 'says', 've', 'time', 'family', 'landing', 'trick']

[3] A part-time job and DJ gigs helped Lara Hamilton reach the Winter Olympics. Now she wants to put Australia on the map [2026-02-17T14:00:15Z]
	>> Counts:	 ['hamilton', 'ski', 'skimo', 'just', 'running', 'says', 'skiing', 'going', 'mountaineering', 'good']
	>> TFIDF:	 ['hamilton', 'skimo', 'running', 'ski', 'mountaineering', 'says', 'just', 'skis', 'results', 'skiing']
	>> LDA:		 ['hamilton', 'ski', 'anthony', 'team', 'just', 'competition', 'running', 'skimo', 'says', 'skiing']
	>> NMF:		 ['hamilton', 'skimo', 'running', 'ski', 'mountaineering', 'says', 'just', 'results', 'skis', 'skiing']

[5] From Bradbury to Bright: five of Australia’s best Winter Olympic moments | Martin Pegan [2026-02-03T14:00:08Z]
	>> Counts:	 ['bradbury', 'event', 'high', 'bronze', 'skiing', 'way', 'speed', 'snowboard', 'snow', 'silver']
	>> TFIDF:	 ['bradbury', 'smith', 'high', 'bronze', 'city', 'event', 'speed', 'nation', 'national', 'later']
	>> LDA:		 ['woods', 'just', 'said', 'skiing', 'bradbury', 'lot', 'win', 'final', 'snow', 'cooper']
	>> NMF:		 ['bradbury', 'smith', 'high', 'bronze', 'city', 'event', 'later', 'nation', 'national', 'speed']

[10] Australia’s Jakara Anthony clinches first ever dual moguls Olympics gold [2026-02-14T11:40:32Z]
	>> Counts:	 ['anthony', 'second', 'moguls', 'james', 'halfpipe', 'training', 'event', 'won', 'peel', 'ok']
	>> TFIDF:	 ['anthony', 'ok', 'second', 'peel', 'james', 'moguls', 'singles', 'beating', 'ruptured', 'likely']
	>> LDA:		 ['anthony', 'moguls', 'second', 'dual', 'event', 'win', 'course', 'time', 'single', 'final']
	>> NMF:		 ['anthony', 'ok', 'second', 'peel', 'james', 'moguls', 'beating', 'ruptured', 'singles', 'likely']

### How should the 'best' approach be selected?

Keep in mind:

* Count and TF/IDF are deterministic, but LDA and NMF are stochastic
* Stochastic algorithms will always need some experimentation, and will change in effectiveness based on the kind of data that is being analysed
* As with all data analytics, we need to make decisions based on the Question and the context in which the question is asked. This means also considering the stakeholders
*